### ISSUE TITLE
Why allow iterative initialization of FMUs in BCS and not move this to HCS?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1055]
singled out from #1019 

In 4.1.1. Initialization Mode (https://fmi-standard.org/docs/3.0-dev/#_initialization_mode_2

>    If the slave is connected in loops with other models, iterations over the FMU equations are possible. Algebraic equations are solved in this mode.

Is this really intended for BCS? Or should we move this to HCS, where we may have iterations at events anyway? So I think this would be more symmetric and HCS is intended for advanvce co-simulation features, while BCS shall be simple.

Is iterative initialization of FMUs often used with FMI 2.0 CS FMUs?

**Comment by KarlWernersson** [comment]
This has been there since fmi 2 and the introduction of initializationMode

At initialization you solve the algebraic equations depending on start values and connection constraints. The modlestructure/initialUnknowns helps you setup the external equations for the fmu. How this is solved is no difference in modelExchange or co-simulation.

Once you enter stepMode the constraints/loops generated by connected FMU's are no trivial to solve as they generally depend on both states and input, where the states are controlled from inside of the fmu and are not accessible to set by the master who might need to do that to solve the constraint.

I cant say how often it is used in general, it is used when importing to Dymola (later versions)
It was introduced in fmi 2 as there were sever issues with FMI 1 with no workarounds if you could not iterate during initialization.

**Comment by andreas-junghanns** [comment]
@chrbertsch : I think we should leave this in BCS to keep BCS at least as powerful as CoSim 2.0. If you agree, please close this ticket.
