### ISSUE TITLE
 Better explain and improve graphics quality of Early return graphics

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1056]
singled out from #1019 

![grafik](https://user-images.githubusercontent.com/16363372/84565955-7be70680-ad6d-11ea-83d4-d5e0cf93dde7.png)

-- Do the plots for the different FMUs all have the same time axis?
-- What do the green, red, dashed, non-dashed lines mean?

**Comment by masoud-najafi** [comment]
In the section 4_1_co-simulation_math.adoc, I updated the text and the figure. Please let me know if it is clear now.
Thanks
Masoud

In the particular context of multi-FMU architectures, significant co-simulation speed-up may be obtained if the master can avoid waiting until the end of the slowest FMU step integration. 
If an FMU prematurely stops its current step integration computation due to an unpredictable internal event before the normal end of the step calculation, all other concurrently running FMUs may be stopped as soon as possible in order to minimize the time needed for the co-simulation master to resynchronize all the FMUs at the same event time.

In this context based on parallel multi-FMU calculations, the following figure illustrates different possibilities to synchronize FMUs at the same event time.

.Different possibilities to synchronize parallel FMUs at the same event time.

[caption="Figure 12: "]
image::images/earlyReturnFigure.png[width=100%, align="center"]

Each FMU starts co-simulation from communication point latexmath:[t_{i}] to reach the next communication point latexmath:[t_{i+1}].
Assuming an unexpected internal event is detected at latexmath:[t^{'}_{i+1}< t_{i+1}] inside FMU~1~, which immediately informs the master and asks for an early return. 
So now the master would like to avoid other FMUs exceed this event time, since all FMUs should be resynchronized at the event time which will be the next new communication point.

* In the case of FMU~1~, the FMU waits to get pushed into the event mode to handle the event at latexmath:[t^{'}_{i+1}].
* In the case of FMU~2~, since this FMU has already reached latexmath:[t_{i+1}], a complete rollback and a new co-simulation from latexmath:[t_{i}] to latexmath:[t^{'}_{i+1}] is necessary.
* In the case of FMU~3~, computation is immediately interrupted and only a partial rollback and integration is necessary to reach latexmath:[t^{'}_{i+1}] time.
* In the case of FMU~4~, the master immediately requests an early return at latexmath:[t^{'}_{i+1}] and the current integration step will been interrupted at latexmath:[t^{'}_{i+1}] and no rollback is necessary for this FMU.

Each running FMU stops its integration either exactly at the event time given by the master or immediately after its current intermediate step.
Afterwards, a new step integration done on the FMU returns and signals the premature stop (early-return) to the master.
![earlyReturnFigure](https://user-images.githubusercontent.com/33484393/89163498-f49c5f00-d575-11ea-81aa-023f6b65d486.png)

**Comment by andreas-junghanns** [comment]
This was fixed by #1119
