### ISSUE TITLE
Harmonize naming of discrete and continuous states

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1121]
I suggest to use

- "continuous states" for continuous time states
- "discrete states" for discrete states, and
- "derivatives" for derivatives of continuous time states w.r.t. time

consistently in order to avoid ambiguities (e.g. with states in the state diagram).

**Comment by andreas-junghanns** [comment]
* We might need to also have "states" as the combination of continuous-time and discrete states in one FMU.

**Comment by andreas-junghanns** [comment]
#1161 & #1171

**Comment by andreas-junghanns** [comment]
web-design meeting:
Clarify in glossary what a continuous state is.

**Comment by andreas-junghanns** [comment]
This waits for clarification on clocks and events.

**Comment by andreas-junghanns** [comment]
We use "discrete-time state" and "continuous state" in all texts we touched.
We only use "state" if we really mean both.
We use "FMU state" for the entire state of the FMU, including hidden states.
For the states of the state machine we use the name of the state.

We are closing this issue because it will be fixed with #1272, but cannot link for automatic closing because of the 10-link limitation.
