### ISSUE TITLE
Explicit definition of 0/1 based indexing for variableNamingConvention "structured"

### ISSUE THREAD

**Issue by fajansen** [modelica/fmi-standard#1128]
While the preamble states that arrays start with 1, and the examples for variableNamingConvention = structured also all start with 1, it is not clearly mentioned in the description.
It would reduce uncertainty to explicitly state the starting index for arrays for the structured naming convention.

**Comment by andreas-junghanns** [comment]
We have the clash of two indexing methods here: C that is 0-based and Modelica that is 1-based.

The examples are Modelica, not C.
We never explicitly say what the first index for structured naming convention is.
A C example would be 0-based.

Anyone?

**Comment by t-sommer** [comment]
I think the spec [is very clear regarding the indexing](https://fmi-standard.org/docs/3.0-dev/#_conventions_used_in_this_document).

@andreas-junghanns, @fajansen, can you make a PR to improve the current text?

**Comment by fajansen** [comment]
I do not agree that the section you quote is clear (and while it was correct in 2.0, it's even inconsistent with the rest of the standard in 3.0):

- There is a distinction between "end-user/logical view" and "implementation view" with no clear definition when which one is used
- In the "end-user/logical view" it is stated, that "the starting index is also explicitly mentioned at the respective definition of the array". There is no mention of the starting index in the section about the structured naming convention.
- The example given for the 1 based approach ("the set of exposed variables is defined as ordered sets where the first element is referenced with index one (these indices are, for example, used to define the sparseness structure of partial derivative matrices).") does not even make sense anymore, as with version 3.0 the "Derivative" element contains value references and not index of the ScalarVariable anymore - it may even start with 0 (unsignedInt)

If you ignore the "Conventions" section, in the definition of the "structured" variableNamingConvention,
[0] would be allowed:
`arrayIndices    = "[" unsignedInteger {"," unsignedInteger} "]"`
references unsignedInteger, which is defined as:
`unsignedInteger = digit { digit }`
where digit is defined as:
`digit           = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"`

I would strongly prefer to have a clear, unambiguous definition. This would ensure that all tool vendors use the same base and a simulation tool could perform something like "connect an array-output of FMU1 with an array-input of FMU2" in a meaningful way.

**Comment by chrbertsch** [comment]
> I think the spec is very clear regarding the indexing

For me it is not clear. The examples are 1-based but the spec does not seem to forbid zero-based arrays convention.

There can arise problems in the automatic connection of FMUs exported from tools using different  tools and possibly manual check, which convention the exporters follows.

There are different solution possibilities: 
1) + 2) either decide and document all array conventions either to be one or zero-based
3) define two different naming conventions "structured zero-based" and "structured one-based" which the whole FMU has to follow
4) provide an attribute for each variable using the structured array conventions which base is used

I would prefer 3)
But the most important thing is to decide for one of them and get rid of the ambiguity.

**Comment by andreas-junghanns** [comment]
No worries: I will clarify that for the structured naming convention, any indexing schema is allowed. I will also add a 0-based example to make sure this is easily understood.
I will need a few days as I am distracted with other work...

**Comment by chrbertsch** [comment]
> I will clarify that for the structured naming convention, any indexing schema is allowed.

It is also important for the importer to know, which indexing schema the exporter followed. @andreas-junghanns Will this be included in your proposal?

**Comment by nickbattle** [comment]
A couple of thoughts.

Indexing is used in fmi3GetVariableDependencies, when things like elementIndicesOfDependent are returned. These have a stated 1-relative semantics, because 0 has a special meaning (depending on all elements of the variable). So presumably this would not change, even if elsewhere the same variable's elements were 0-indexed?

I don't think this is being suggested anyway, but I would advise against changing the naming _syntax_ to solve this. The syntax should be able to accept arbitrary (positive decimal) numbers as indexes. Then rules about 1- or 0-relative addressing are enforced elsewhere, perhaps in a static check.

**Comment by andreas-junghanns** [comment]
To be clear: this is only about the naming schema of the variables.
This is not about the C-API.

**Comment by andreas-junghanns** [comment]
A remark during today´s FMI SC meeting made me wonder if I am wrongly assuming this is clear.
Therefore, I would like to clarify, what I think we should define:

The structured naming convention does not need to define if the indexing in the variable names are 0- or 1-based.
This can simply be deduced from the strings used.
If an importer needs to map between tools from different worlds (say Modelica and C), the mapping can be worked out "trivially", if the dimensions match otherwise.
The last is a big IF, because order of dimensions and their names are conventions and those differ between Math, m, C, Modelica , FORTRAN, Python, etc.

If the group decides that we need to be more strict here, then I suggest to declare 0-based indexing
and we should declare the index order should be used like we define for array variables.

**Comment by fajansen** [comment]
I disagree that the convention can be deduced from the strings used.
`It might be that not all elements of an array are present. If they are present, they are given in consecutive order in the XML file.`
So assuming the first variable has index 1, how do I know if I have a 1-based convention, or a 0-based with element 0 not being present?

An alternative to being more strict would be to allow different schemes, but provide a way to specify which scheme was used.

**Comment by pmai** [comment]
The structured naming convention is (intentionally, I'd say) way too lenient to allow automatically and rigorously doing the right thing in every case: Nothing in the spec even forces all elements of the array to be of the same type, or same substructure for that matter.

So I don't think it makes sense to try to partially improve this, especially for arrays, where we have a much more robust solution in FMI 3.0 if one so desires ...

If any clarification is done here I think it must remain compatible to the FMI 2.0 approach, because having two conventions for 2.0 and 3.0 + the new arrays just makes everything even more confusing.

Given that on the XML side FMI always was 1-based, I don't think switching to 0-based makes sense (the C API is 0-based because C necessarily is, not due to choice).

Just my two centi-euros.

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

Pierre: I would not do anything
Andreas: I would add an example for zero-based indexing. I will create a PR
Klaus: One motivation for the arrays was to get away with the ambiguity of the naming convention.
Pierre: We can put this in the implementers guide #1029

**Comment by t-sommer** [comment]
If 0-based indexing is allowed in the XML (which I think is not the case for FMI 2.0) the paragraph

> In the end-user/logical view, one- and two-dimensional arrays are used. Here the convention of linear algebra, the control community and the most important tools in this area is utilized. In other words the first element along one dimension starts at index one. In all these cases, the starting index is also explicitly mentioned at the respective definition of the array.

is misleading and should be removed. This should also be clarified for FMI 2.0.2.

**Comment by andreas-junghanns** [comment]
This issue was decided in the last web-design meeting: both 0- and 1-based is allowed.
@t-sommer : you promised a PR...
