### ISSUE TITLE
Clarify what discrete states are or find a better name

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1171]
( from regular design webmeeting)

**Comment by andreas-junghanns** [comment]
See #1161

**Comment by friedrichatgc** [comment]
If we want to rename it we can rename it to "internal states". If these are discrete or not is not relevant the term state here just means that these variables cannot be calculated from other variables since the value is part of the state of the FMU.

The only way to save and restore the state of a FMU is to use fmi3SetFMUstate/fmi3GetFMUState functions. Hence, I think its even not needed to declare that a variables is any state at all. So we may also skip a definition of discreate states.

**Comment by andreas-junghanns** [comment]
web-design meeting:
Clarify in glossary what a discrete state is.

**Comment by andreas-junghanns** [comment]
There are continuous states, as we defined them for ME: the solver drives those through time.

There are two kinds of discrete states:
 1. hidden discrete states, as defined in FMI 2.0: Anything defining the internal state of the FMU that changes only at events (still ME!)
   (in FMI 2.0 (ME and CS) they are handled internally, not listed in the modelDescription)
 2. Discretized continuous states in a clocked partition.
 3. True discrete state, like a counter.

While the concept for 1. is clear, 2. and 3. both are new and should not be called "discrete state", we propose to call them "clocked states" and list them in ModelStructure as <ClockedState>.

**Comment by KarlWernersson** [comment]
#1161

**Comment by andreas-junghanns** [comment]
See #1287.
#1272 defines DiscreteTimeState as subset of local variables. We decided against ClockedState, because clocked states are only a subset of DiscreteTimeState.
Closing ticket, because the maximal number of 10 linked issues per PR is reached for #1272.
