### ISSUE TITLE
Shouldn't TriggeredBy information be in the ModelStructure?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1183]
In the Standard we have this description for TriggeredBy:
_The optional attribute triggeredBy is used to define a tick relationship from an outputClock to an aperiodic inputClock 
(see [clock-relationships-for-communication-point-clocks]).
Only clocks with causality = input and clockType = communicationPoint can have this attribute. 
It is not allowed to combine output clocks with periodic or strict periodic input clocks based on triggeredBy._

First, we need to fix this because  TriggeredBy is used also in ME and CS.
Then, TriggeredBy defines a kind of clock union that adds an output-clock ticks to another clock tick and feeds to the input-clock of the FMU. This information is actually a kind of clock link and is used by the FMU importer to setup the simulation and may be better to put in the ModelStructure instead of being an attribute of a clock.

**Comment by andreas-junghanns** [comment]
I agree with the fix for triggeredBy, see #1190.

Moving the triggeredBy information to ModelStructure would require extensive changes.
Since this is a 1:m relationship, we cannot move it to ModelStructure/Output - one outputClock might trigger several inputClocks.
InputClocks are not part of ModelStructure yet - so we would need to introduce those.

I believe the PR is sufficient to address this issue and it will close once we merge #1190.
