### ISSUE TITLE
Table 1 modelExchange features

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1256]
Feature  Early Return  & Intermediate Update is marked as an X for model exchange, this should rather be a -, as you can actually do both there as it is included in its definitions of ME, however you not need the cumbersome additional features of co-simulation to do it.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : are you sure? So far, I thought that there is no need to have Intermediate Update Mode in ME because the master has complete control over how to advance time and when to set which input and read output. This is completely different in CS and SE where the control during a doStep() or activateModelPartition() must be handed back actively to the importer.

If you think ME can benefit from this, we need more than the table change. We would have to explain the MS use case in 2.3.3 State: Intermediate Update Mode at the beginning AND also fix the text that currently implicitly and likely also explicitly excludes ME from using Intermediate Update Mode.

**Comment by chrbertsch** [comment]
Coming back to Karls proposal, we should perhaps clarify  and add a legend explainging what "x" and "-" mean in that table: 

For me: 
"check": suppported
"x" not supported
"-" not relevant/does not make sense

For me that points that Karl mentions are "not relavant" for ME, as you do not need these features and can get the same or even better with ME-means.

So Karl does not propose to use the "check" as is realized in https://github.com/modelica/fmi-standard/pull/1258/files

**Comment by KarlWernersson** [comment]
@chrbertsch @andreas-junghanns 
yes Christian understood me correctly 
Form my understanding there should be  "-" as it is not relevant. An ME master can "return" whenever it want's and inquire values whenever it wants so it can do already all of this whit out the extra API's. But it does not use the exact features that are added to co-simulation.
sorry if I was unclear.

**Comment by andreas-junghanns** [comment]
> Form my understanding there should be "-" as it is not relevant. An ME master can "return" whenever it want's and inquire values whenever it wants so it can do already all of this whit out the extra API's. But it does not use the exact features that are added to co-simulation.

Current PR #1258 should reflect your concerns now. Please check again.
