### ISSUE TITLE
Allow arbitrary get/set sequences in *Step Mode*

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1281]
The rest of the functionality remains the same, we only drop this artifical restriction (which did effectively introduce an internal state machine to Step Mode).

This way, one can get and set variables and only when doStep is called, time advances and the new get calls produce new values.

**Comment by chrbertsch** [comment]
> _[Calling `fmi3Get{VariableType}` for outputs without <<fmi3DoStep>> will return the same values, regardless of what `fmi3Set{VariableType}` calls where made.]_

This is non-normative text. Are calculations in fmi3Get dependent on an fmi3Set without an fmi3DoStep (contrary to this non-normative statement) allowed or forbidden?

I would explicitly forbid this, as we have event mode to do something like this. Otherwise I fear that some exporters will create "direct feedthrough CS FMUs without events".

**Comment by andreas-junghanns** [comment]
Thank you for the feedback - clarified and changed to normative text.

**Comment by andreas-junghanns** [comment]
@pmai : Agreed, we go back to 2.0 restrictions.
