### ISSUE TITLE
drop calculatedParameter

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1286]
We propose to remove the special causality calculatedParameter - these are simply local variables, like many others.

Is there a good reason to keep them singled out?

**Comment by KarlWernersson** [comment]
I would rather say that calculated parameters are fixed or tunable outputs, which currently isn't an allowed combination.
So if we drop them we should allow output with the variability fixed and tunable.

Next comes the model description.

Currently one must list calculated parameters in the initialUnknown section to list their dependencies.

For initial Unknowns
> - causality = output and (initial = approx or calculated), and
>
>- causality = calculatedParameter and
>
>- all continuous-time states and all state derivatives (defined with elements <ModelStructure><Derivative>) with initial = approx or calculated [if a Co-Simulation FMU does not define the <ModelStructure><Derivative> elements, (3) cannot be present].

For output the current rule is that all outputs must be listed there.

> Ordered list of all outputs, in other words, a list of value references where every corresponding variable must have causality = output (and every variable with causality = output must be listed here).

Now if we change calculated parameters to fixed/tunable outputs, they will still be listed in initial unknowns so that is not a problem.
The issue I see is that this could clutter the <ModelStructure><Output> section with many empty dependencies as the fixed/tunable outputs will not have any dependencies during continuous or discrete time.

to this problem i woudl say there is two solutions.

- Ignore it, it doesn't matter that we list a bunch of empty fixed outputs, and we already lists constants.
- Modify the rule so that we only list the continuous and the discrete output, not the fixed/tunalbe/constant.
  these you will have to find by examining the model variables.


Of course calculated parameter that you don't want to treat as outputs and you aren't interested in the modlestructre of shod be treated as locals, but this also applies to FMI 2.0

**Comment by chrbertsch** [comment]
> that calculated parameters are fixed or tunable outputs, which currently isn't an allowed combination.

@KarlWernersson : I do not get it:
Why should (calculated) parameters be outputs? Outputs are typically connected to inputs of other models or FMUs.
And why should calculated paramters be tunable? I see tunable parameters as beeing set by user interaction during runtime.
And why should these outputs be fixed?

**Comment by KarlWernersson** [comment]
@chrbertsch 
First short awnsers then a longer

> Why should (calculated) parameters be outputs? Outputs are typically connected to inputs of other models or FMUs.

Calculated parameters can be used as parameters for the environment outside the fmu or as a fixed input.. They are required to have model structure so dependency information can be set up for them during initalization. They are equivalent to outputs with variability fixed or tunable.

> And why should calculated paramters be tunable? I see tunable parameters as beeing set by user interaction during runtime.

Say you have
```
 parameter p1 = a, p2 =b;
 calculated parameter cp,
 
 equation
  cp = p1*p2;
```
  If p1 or p2 has variability tunable. cp has to be tunable.



calculatedParameters are computed parameters intended to be available to be propagated to other FMU's or models. They can only have variability fixed or tunable. They can only have intial= aprox or calcualted, (fixed would imply that it is a parameter)
They are required to be declared at initialUnknowns in model structure. They do not have model structure for continuous time as they are not supposed to change then.

Outputs are variables that are intended to be connected to other variables or models (compared to locals that are not intended for connections). They are required to be listed in modelStructure/outputs, where their dependency is declared. Outputs that have initial=aprox or initial=calculated must also be declared at initial unknowns. outputs can only have the variability constant/discrete/continuous. 

The description why output cannot have variability fixed or tunable states

>A fixed or tunable output has exactly the same properties as a fixed or tunable calculatedParameter. For simplicity, only fixed and tunable calculatedParameters shall be defined.

So what I am trying to say is that calculatedParameters are not locals but corresponds to an output with variability fixed or 
tunable. So if we want to remove calculatedParameters we should allow outputs to have variability fixed or tunable to cover the loss of functionality by removing them.

**A parameter that is calculated that in not intended to be used outside of the model should not be declared as a calcualtedParmater but rather have the causality local**

An additional optimization would then be to only list continuous or discrete outputs in modelStructure/Outputs as a constant/fixed/tunable output would have an empty dependency list.

We might need to clarify if getOutputDerivatives are allowed for fixed/tunable if we introduce them

I don't have a strong opinion myself if we merge calculated parameters with outputs or keep them as calculated parameters, but if forced to choose I would prefer to remove them and replace with fixed/tunable outputs. I am against removing them whit out merging them with outputs.

**Comment by pmai** [comment]
I think we have calculatedParameters for the same reason we have parameters: Parameters are functionally equivalent to discrete inputs, tunable parameters are equivalent to discrete inputs; the same as calculatedParameters are functionally equivalent to fixed or discrete outputs (tunable is only needed due to the parameter vs. input split in 2.0, it is just like discrete in all respects).

However functionally equivalent is not the same as intentionally equivalent: Parameters (and calculated Parameters) are provided as something separate to inputs/outputs with restricted variability to communicate intent: One, that you should think about those as stuff that you normally "parametrize" or use for "parametrizing" other models, and two that they are less likely to change as frequently as normal inputs/outputs. For example a tunable integer parameter called "gear" and a discrecte input called "gear" are functionally equivalent, but you would expect the later to change more frequently than the former.

So one could do away with parameter and calculatedParameter causalities, but then you probably need another mechanism to communicate the intent, especially for user interfaces, where you usually present parameters in different ways than inputs/outputs.

However if we drop calculatedParameters we must also drop parameters, otherwise this does not make sense at all to me.

**Comment by andreas-junghanns** [comment]
Our proposal was an intend to simplification. We withdraw this proposal, following Pierre´s "intent vs. functional equivalent" explanation.

**Comment by KarlWernersson** [comment]
@pmai 
There is an important distinction between tunable/discrete.
A tunable calculatedParameter or local variable will **only** be changed if you have modified a tunable parameter.

While a discrete variable can change because of an event, changes in discrete input or changes of a tunable parameter.

**Comment by pmai** [comment]
@KarlWernersson that is true, however I think this distinction only latched onto the parameter/input schism, i.e. this could have been expressed more directly and more fine-grained with dependency information. So I would argue that the later is only a useful shortcut that latches onto the intentional differentiation of parameter vs. input...
