### ISSUE TITLE
How to express DiscreteTimeStates

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1287]
Currently, discrete-time states are local variables referenced in (new) <ModelStructure><DiscreteTimeState>.
This means, they cannot be set.

For model-based controll applications, setting discrete-time states is required.

We can think of 2 ways to express this:
 1. introduce a new causality `state` and paired with variability `discrete`.
 2. formulate exceptions for local variables to be set in certain states.

**Comment by KarlWernersson** [comment]
1. We should not limit it to discrete but also allow continuous as variability. 
   this would also have the consequence that the state/output combination is forbidden. It  could be a nice rule to simplify for importers.
2. Here we need to separate cs/me, for ME it is already allowed to set continuous states by local variables. For CS this is not allowed. 
 
So for ME i dont see any isuse with whatever way we chose, for CS are we not with the same problem as with continuous states? Some tools might not be able to modify the discrete state similar as they cannot modify the continuous states. 


Some possible solitons for CS
1. Continue forbidding setting continuous states in CS, and forbid setting discrete states in CS.
2. Continue forbidding setting continuous states in CS, and allow setting discrete states in CS.
  Tools that cant support this will have to hide their discreet states. Why one and not the other?
3. States listed in modelStructure can be set, if you don't want a state to be settable but include it in the model, list it as local without linking it to modelStructure. Negative aspect is that if you want the directional derivative of the derivative of the state you cannot get it.
4. Introduce a local flag for the states e.g. canBeSetInCS
5. Allow setting continuous states and discrete states in CS is not an option if i understand it since many tools cannot set continuous states for CS. 


Personally I would preferer 3, or possibly 4.

**Comment by andreas-junghanns** [comment]
(Andreas & TorstenB):

Continuous variables which are states have the attribute derivative pointing to their derivative listed in modelStructure StateDerivative. This allows defining states and their derivatives independently of their causality (e.g. local or output).

To be consistent with this approach, we propose the following:
 - A new (old!) attribute `previous` is introduced for variables with variability `discrete` pointing to another discrete variable of the same numeric type.
 - These previous, discrete variables are listed in the modelStructure (instead of the currently proposed DiscreteTimeStates).
This would allow an independent defintition of discrete states from their causality as well, see above.

@KarlWernersson : FMUs that cannot support setting discrete-time states simply do not publish them. If this is different for ME/CS of the same FMU, you have to export two FMUs, see standard 2.5.2: "Support of multiple interface types in one FMU is possible only, if the interface variables are identical."

**Comment by andreas-junghanns** [comment]
WEB design meeting: @TorstenBlochwitz + @KarlWernersson will create a PR (@andreas-junghanns will act as secretary).

**Comment by andreas-junghanns** [comment]
WEB meeting with TorstenB, Karl and AndreasJ: Introduce Clock elements in ModelStructure.
We considered two alternatives:
 2. Add Input elements and Local elements to have a place to add clock dependencies
 3. Add a clockReferences attribute to Variables in the XML
We believe these three approaches to be essentially equivalent, but 3. clutters the Variables list more and 2. requires more additional elements in ModelStructure, so we agreed on this proposal here.
