### ISSUE TITLE
Allow setting continuous states with reinit= false in event mode

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1290]
In fmi 2.0 reinit attribute was introduced so that one could se which states could be reinitialized by the master and which would be reinitialized by the FMU (and therefore not allowed to be reinitialized by the master)

In super state event mode 

This section needs to be updated

> Allowed Function Calls
> Function fmi3Set{VariableType}
> This function can be called for variables with causality == input and for variables with causality == parameter and variability == tunable.

**Proposal**

 Allowed Function Calls
 Function fmi3Set{VariableType}
 This function can be called for variables with causality == input, for variables with causality == parameter and variability == tunable and, in the case of ModelExchange, for continuous states with reinit == false.
 
 
**Question**
since we have event mode for co-simulation, should we support reinit attribute for co-simulation? 
Any tool that don't want to support it and is exposing its states in co-simulation can simply set reinit = true on all of those states. Thereby forbiting the master to change them during events. Then we could remove all the different comments about only alowing the state to be changed in ModelExchange

**Comment by TorstenBlochwitz** [comment]
Attribute "reinit" (see Table 24) is intended to signal if a continuous state might be reinitialized by the FMU. I dont see a use case in which the importer could reinitialize a continuous state (see also "valuesOfContinuousStates") in Event Mode.

I dont see a use case why we should open thebox to allow setting of continuous states for Co-Simulation at all (and especially in Event Mode).

**Comment by KarlWernersson** [comment]
@TorstenBlochwitz 
Importing an Me FMU into modelica and aply reinit operator on states that are ont internally reinitialized

From the test models that we developed to test functionality of the FMI 2.0 specification.

model WithFMUs "Solution with FMUs"
  extends Modelica.Icons.Example;
  FMUModels.SimpleNonlinearModel_fmu  simpleLinearReinit(x(fixed=false))

initial equation 
  der(simpleLinearReinit.x) = 0;
equation 
  when sample(0.1, 0.5) then
    reinit(simpleLinearReinit.x, 1);
  end when;

  connect(simpleLinearReinit.y, simpleLinearReinit.u) 
end WithFMUs;

**Comment by TorstenBlochwitz** [comment]
@Karl: What you describe would be contrary to the semantics of Model Exchange FMUs we are using since FMI 1.0: The importer is responsible to set continuous states in Continuous-Time mode (using the derivatives and an integration algorithm). The FMU is responsible to initialize continuous time states according to its internal initial equations in Initialization Mode, and to reinitialize them according to its internal equations. The continuous states are on the left-hand side of finit and of fevent.

It would be a new feature to change this and I don’t see practical use cases which justify its introduction at this late stage of the FMI 3.0 development.

Two additional remarks:
- only for very simple models, the complete state of an FMU is represented by continuous states. Proper reinitialization would require reinitializing discrete states too. In order to do so, an importer would need to know the internals of the FMU.
- what you want to achieve can be done keeping the FMU in Continuous Time Mode.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : Can we close this issue?

**Comment by KarlWernersson** [comment]
@andreas-junghanns Yes
`what you want to achieve can be done keeping the FMU in Continuous Time Mode.`
@TorstenBlochwitz  sorry I mixed up the modelica event at the master with internal FMU event.
The reinit of the state is fine and should be done in continues time mode of the FMU (event at the master level), this in turn could of course trigger a state event or event a step event, but that should then be handled by entering event mode directly after.
