### ISSUE TITLE
Tag Alpha.6

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1336]

**Comment by chrbertsch** [comment]
Here is  a draft for the release notes: 

*****

The following larger changes have been made since [v3.0-alpha.5](https://github.com/modelica/fmi-standard/releases/tag/v3.0-alpha.5) (for details see commit history)

- Refactoring and restructuring of the whole documentation  (#1272 #1222 )
- Clarification and unification of clocks API between different FMI interface types, allow for usage of clocks API in different sematics( #1272, #1314) 

- API Changes: 
-- Changes of arguments in doStep((#1320)
-- rename fmi3NewDiscreteStates to fmi3UpdateDiscreteStates (#1224 ) 
-- Adapt instantiation functions (#1195, #1169 , #1272  )
-- Move eventOccurred and clocksTicked to fmi3DoStep() (#1127) 
-- Improved Clocks API (#1272)

- Changed Schema files: 
-- Add Name to sourcefileset (#1302) 
-- Add fmi3ScheduledExecution to schema (#1176) 
-- Improved Clock Attributes (#1272 )
-- Rename Derivatives to StateDerivatives (#1272)
-- Introduce DiscreteTimeState(#1279)
-- Changes from xs:int to xs:long (#1272)  

- Unification and improvement of state charts, super states (#1315, #1204 ) 
--Clarifications for Intermediate Update mode including continuity requirements (#1302, #1149, #1142)

- Addition of extra directory and definition of layered standards (#1218)

*****
@andreas-junghanns , @TorstenBlochwitz , @t-sommer and others: please check and improve

**Comment by andreas-junghanns** [comment]
I have added what I missed in your comment directly in your comment.
Not sure how to check for completeness.

**Comment by t-sommer** [comment]
Before we tag v3.0-alpha.6 I suggest to make the following changes:

- [ ] fix indentations in fmi3FunctionTypes.h
- [ ] fix parameters names in `fmi3GetShiftDecimal()`
- [ ] limit the line length of included sources, so we don't have to scroll horizontally in the HTML

I will prepare a PR.

**Comment by t-sommer** [comment]
I've tagged `v3.0-alpha.6` and created a [draft for the release](https://github.com/modelica/fmi-standard/releases/tag/untagged-7671627bb75fdee008df).
Please give it a check and make changes if there is anything wrong.

**Comment by chrbertsch** [comment]
> I've tagged `v3.0-alpha.6` and created a [draft for the release](https://github.com/modelica/fmi-standard/releases/tag/untagged-7671627bb75fdee008df).
> Please give it a check and make changes if there is anything wrong.

Looks good to me. (I made two minor changes: mentioning also smaller changes in the first line and removing mention of the extra directory in the last, as this was already present in alpha.5

shall your proposed changes  be done after alpha.6 ?
- fix parameters names in fmi3GetShiftDecimal()
- limit the line length of included sources, so we don't have to scroll horizontally in the HTML
- Unify StateDerivative, Derivative, ContinuousState in API and XML
Shall we create separate tickets for them?

**Comment by t-sommer** [comment]
> shall your proposed changes be done after alpha.6 ?
> Shall we create separate tickets for them?

Yes. It would have taken too long to fix them before alpha.6.
