### ISSUE TITLE
Unify naming of "continues states" and "derivatives" in API, XML, and docs

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1343]
Currently we have 

- `<StateDerivative>` in the Model Structure
- `fmi3GetContinuousStates()` and `fmi3GetDerivatives()` in the API
- a mix of "continuous-time states", "states" and "continuous states" in the docs

I suggest to call them "continuous state" and "continuous state derivative" to clearly distinguish them from state diagram states, discrete states and output derivatives.

see also #1336

**Comment by andreas-junghanns** [comment]
The FMU "state" is more than "continunuous-time state". It contains also "discrete-time states" and hidden states (not visible, nor setable, unless you use fmi3SetFMUState/fmi3SetFMUState.

"continuous state" (without "-time") should not be used because of ambiguous interpretations (continuous-time vs. continuous-value).

We refrained from renaming fmi3GetContinuousStates() to keep this as it was in 2.0.

**Comment by t-sommer** [comment]
> We refrained from renaming fmi3GetContinuousStates() to keep this as it was in 2.0.

I'm not proposing to rename `fmi3GetContinuousStates()` but `fmi3GetDerivatives()` to `fmi3GetContinuousStateDerivatives()`.

**Comment by andreas-junghanns** [comment]
@TorstenBlochwitz , @KarlWernersson : Do you care to comment here?

**Comment by KarlWernersson** [comment]
Although fmi3GetContinuousStateDerivatives() is more explicit, I haven't seen anyone misunderstand fmi3GetDerivatives() in the context it is used so we don't rely have a problem to fix there. It is much shorter to say and write and think GetDerivatives vs GetContinuousStateDerivatives which makes it better.

**Comment by TorstenBlochwitz** [comment]
I fully agree to Karl, I dont see any reason for a change.

**Comment by andreas-junghanns** [comment]
@t-sommer : if you have concrete change proposals, please create a PR and reopen here.

**Comment by t-sommer** [comment]
I'm on it...
