### ISSUE TITLE
_Bool is not defined

### ISSUE THREAD

**Issue by meisenmann77** [modelica/fmi-standard#1350]
Hi

I tried to compile my FMUs with alpha6. I was not able to compile with g++ on ubuntu (version 9.3) because _Bool is not defined.
It is used for fmi3Boolean and fmi3Clock in fmi3PlatformTypes.h

**Comment by chrbertsch** [comment]
If your compiler does not support C99 (with _Bool), you are free to redefine data types in a modified local version of https://github.com/modelica/fmi-standard/blob/master/headers/fmi3PlatformTypes.h

**Comment by beutlich** [comment]
This is not about g++ 9.3 not being C99 compliant, it is about compiling FMUs as C or C++. Thus, we should ask ourselves if we want to support FMUs being compiled as C++ out of the box and do not want to tell them about the mandatory inclusion of stdbool.h before any FMI3 header (e.g. fmi3PlatformTypes.h).

Here's my experimental setup. Try to set the compiler options "-x c", "-x c++" or leave them empty.

https://godbolt.org/z/K96ja1

It definitely would be an improvement to support C++ applications, e.g. have something like

```c
#if __STDC_VERSION__ >= 199901L
typedef _Bool fmi3Boolean;
#elif defined(__cplusplus)
typedef bool fmi3Boolean;
#else
typedef char fmi3Boolean;
#endif
```

in fmi3PlatformTypes.h (or similar).

Please be aware that in MAP-Lib we also support C++ compilation out of the box, e.g. https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaUtilities.h#L50-L52.

Reopening to encourage the discussion.

**Comment by andreas-junghanns** [comment]
@t-sommer & @pmai : Could you please comment?

**Comment by pmai** [comment]
I agree that this is about the level of support we want to provide with those headers out of the box; the simplest solution if we want to do this BTW would be to include stdbool.h and use bool instead of _Bool, which should work for both C99 and C++ (similar to the way we already include stdint). Support for C89 is not needed, since this is already broken by the use of stdint.

Given that we already provide extern "C" auto-wrapping in the headers, hence acknowledging the existence of C++, we might want to provide support for C++ for the boolean type as well.

That being said, the more I reflect on the situation, the more I feel we might _not_ want to use _Bool/bool in the first place: While C support for _Bool is now common enough, actual ABI compatibility for binary FMUs is probably something that might be more hit-and-miss, especially on non-common platforms, and we might want to avoid that...

**Comment by pmai** [comment]
Which though would re-raise the question of whether fmi3Boolean should be int/uint32_t or char/uint8_t or something else... Bah...

**Comment by andreas-junghanns** [comment]
Why do we include stdint.h?
Can´t we try to make our fmi3PlatformTypes.h to be as liberal as possible about compiler dependencies?
To require C99 compatibility of the compiler removes quite a number of compiler versions from what can be used.
We should have very good reasons to be so restrictive.
What are those reasons?

**Comment by andreas-junghanns** [comment]
> Which though would re-raise the question of whether fmi3Boolean should be int/uint32_t or char/uint8_t or something else... Bah...

Well, it seems we have that discussion anyway, albeit from a different angle.
Delegating this decition to the compiler seems to invite even more trouble: potential incompatibilities because of differences in ABI.
Would we not do better as an enabling standard to fix that with our own definition to a base type that removes the ABI from the equation?

**Comment by pmai** [comment]
> Why do we include stdint.h?

Because of the decision to use uint8_t & friends for the numeric data types. If we didn't use C99 (and hence stdint.h), we'd need to define those types ourselves, which would then quickly make the definitions non-portable (you'd redo the whole work of stdint for all possible compilers...), or require users to provide their own (and in the later case they can obviously just as well change the definitions from stdint to their own anyway).

> To require C99 compatibility of the compiler removes quite a number of compiler versions from what can be used.

Actually not anymore, I'd argue, since nearly all actively maintained compilers support C99, even for embedded platforms. It is hard to acknowledge this, but actually some progress has been made in the C world in the last 20 years. Minute, but noticeable.

**Comment by pmai** [comment]
>  Would we not do better as an enabling standard to fix that with our own definition to a base type that removes the ABI from the equation?

That was why I made the comment I did. However all of this started with the discussion of whether fmi3Boolean should be char/uint8_t (as it was in FMI 2.0) or int/uint32_t (as it was in FMI 1.0, and nicer for the Modelica FFI, it seems); so we are back to square one in that case.

**Comment by meisenmann77** [comment]
The changes from cstdbool.zip solved the issue. For me this looks like the most generic solution to support c++.

[cstdbool.zip](https://github.com/modelica/fmi-standard/files/6146602/cstdbool.zip)

**Comment by meisenmann77** [comment]
Or let me phrase it better - To reenable the c++ support as it was there in alpha5.

**Comment by t-sommer** [comment]
> char/uint8_t (as it was in FMI 2.0) or int/uint32_t (as it was in FMI 1.0, and nicer for the Modelica FFI, it seems);

It was actually the other way around.

fmiPlatformTypes.h (FMI 1.0):

```C
typedef char fmiBoolean;
```

fmi2TypesPlatform.h (FMI 2.0):

```C
typedef int fmi2Boolean;
```

**Comment by pmai** [comment]
> 
> 
> > char/uint8_t (as it was in FMI 2.0) or int/uint32_t (as it was in FMI 1.0, and nicer for the Modelica FFI, it seems);
> 
> It was actually the other way around.
> 
> fmiPlatformTypes.h (FMI 1.0):
> 
> ```c
> typedef char fmiBoolean;
> ```
> 
> fmi2TypesPlatform.h (FMI 2.0):
> 
> ```c
> typedef int fmi2Boolean;
> ```

You are of course right, my memory is going slowly... ;).

**Comment by andreas-junghanns** [comment]
> 
> 
> Or let me phrase it better - To reenable the c++ support as it was there in alpha5.

Note: We are trying to keep the FMI C API straight C (last time I checked, this is one of our fundamental rules).
If someone wants to use C++, they can try, but to make this work is not our primary objective.

**Comment by andreas-junghanns** [comment]
WEB Design meeting (AJ + TB): We support the "simple solution" to #include "stdbool.h" as it does not worsen the compiler dependency on C99 and use bool instead of _Bool.

@pmai or @t-sommer : Can you please provide a PR? Is this still compatible with Alpha.6?
