### ISSUE TITLE
Scheduled Execution of virtual ECUs using FMI 3.0 for Co-Simulation with Event Mode

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1400]
Possible topic for the implementer's guide: 

To simulate externally scheduled virtual ECUs in virtual time, the FMI for Co-Simulation with Event Mode is a viable alternative to the FMI for Scheduled Execution. Using CS instead of SE for the virtual ECU has benefits when it comes to integration with the CS-FMUs of the remaining system.

Consider a virtual ECU as FMU for CS that is implemented such that
(1) No computation is done in StepMode, i.e. doStep() only advances internal simulation time.
(2) All computations are done in Event Mode by way of clocks activating model partitions.

Then, the effect of the call sequence
`doStep(dt to activationTime), enterEventMode(), setClock (clock), updateDiscreteStates(), enterStepMode()` of CS
becomes analogous to the call
`activateModelPartition (clock, activationTime)` of SE
and thus, for this use case, the FMIs for SE and CS become interchangeable in virtual time simulation.

**Comment by andreas-junghanns** [comment]
@oliverkotte : for restricted use cases, what you propose works certainly (we are packaging vECUs since 2010 into FMUs).

However: This does not work for the general case with preemption and multiple FMUs contributing to a single vECU.

I suggest to move your observation/use case into #1029 - there we collect topics for the Implementer´s Guide.
If you agree, please close here.

**Comment by oliverkotte** [comment]
ok, I have moved the use case into #1029.
