### ISSUE TITLE
Synchronous Clocks: Clarify what happens when a clock is de-activated by the Importer

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1402]
One of the rules the FMI is clear about clocks is: 
 When a clock is inactive, and a corresponding clocked variable is read, then the value returned is the one corresponding to the clock’s last activation time (the sample and hold).

First, let's define a clock C’s activation time to be the time in between a call to setClock(C, active) and fmi3UpdateDiscreteStates.
As a consequence, two sequential calls 
  setClock(C, active); …; setClock(C, inactive);
do not represent an activation time.

Therefore, to abide by the sample and hold rule, we must conclude that when a clock is deactivated prematurely, then we need the following rule (discussed in Torsten slides a while ago)
“Active input clocks can be deactivated by the Importer, with a call to fmi3SetClock(…, fmi3False). Variables depending on such a clock need to return to the values they had before the activation. Clocks that cannot be deactivated signal this by the clock
attribute canBeDeactivated=false (default=true).”

The following needs to be done:
1. The above rule must be explicit in the standard (the only reference to it that I could find is in a table: `Reset respective clocked variables to their previous values`).
2. We need to agree on who is responsible for restoring the variables to their previous values: is it the Importer, or the FMU?
3. The xml attribute canBeDeactivated needs to be added for Clocks.

**Comment by KarlWernersson** [comment]
Its a good point you take up.

But what happens to clocked inputs that has been set? Tunable parameters?
Will the FMU require buffers on them so they can be reset when the clock is deactivated. Or should they keep their value as it was set by the master?
If the input isn't reset should a "reseted" value of an output be based on the new inputs?

Is this a feature we need? Or is it a consequence of previous decisions? 
If we need it can we make it mandatory for Clocks?
We do have setState/getState, this is of course for the whole FMU but if possible cant they be used instead?

An alternative solution would be to leave the values undefined when the clock is inactive is that worse?
If I remember the reason to enforce the hold was simplicity, it is not as simple any more.

**Comment by clagms** [comment]
Thank you @KarlWernersson for having seen what I overlooked indeed!

> Is this a feature we need? Or is it a consequence of previous decisions?

It seems like both: 
- It is a consequence of the sample and hold semantics (if one takes a strict interpretation of that rule, as I explained above)
- It is a feature we need: when solving algebraic loops that span the previous and the next value of a clocked variable, there is a need to enable rollback (each new iteration of the algebraic loop needs to start from a fixed previous value, and reach a better next value)

> But what happens to clocked inputs that has been set? Tunable parameters?

I haven't thought deeply about this, but I guess the FMU does not have to buffer inputs. It would be up to the Importer to restore these. As for tunable parameters, I haven't thought about them much (can we even have a tunable parameter change happening at the same time that a clock is ticking?)

> If we need it can we make it mandatory for Clocks?

Right now, it is optional in the sense that FMUs that do not support this, can declare it through the canBeDeactivated attribute.

> An alternative solution would be to leave the values undefined when the clock is inactive is that worse?

I'm not sure this would solve the problem, as we still might have the need to solve algebraic loops.

An easy way out is to leave the restoring of values at the mercy of the Importer, thus simplifying the FMU implementation. But the FMU would have to disclose all the clocked variables.

**Comment by TorstenBlochwitz** [comment]
> But what happens to clocked inputs that has been set? Tunable parameters?
Inputs and parameters are set by the importer, they stay, where they are from the FMUs point of view.

> Will the FMU require buffers on them so they can be reset when the clock is deactivated. Or should they keep their value as it was set by the master?
See above: the FMU needs to buffer only the values it is responsible for.

> If the input isn't reset should a "reseted" value of an output be based on the new inputs?
No, reset means: go back to the state before as if the activation did not happen.

> Is this a feature we need? Or is it a consequence of previous decisions?
As far as I remeber this feature was required by Masoud and Claudio in order to solve algebraic loops which include clocks (yes, I mean clocks her, not clocked variables!). And it allows and simplifies Rüdigers demand to set clocked states to preliminary values for his model predictive control applications.

> If we need it can we make it mandatory for Clocks?
No, there there might be "legacy" code inside a clocked partition, which cannot be reset.

> We do have setState/getState, this is of course for the whole FMU but if possible cant they be used instead?
In principle yes. But get/SetFMUState works for the whole FMU. Allowing this for clocked partitions enables this feature also for FMUs whose state cannot be stored completely, it should be faster and simpler to use.

> An alternative solution would be to leave the values undefined when the clock is inactive is that worse?
> If I remember the reason to enforce the hold was simplicity, it is not as simple any more.
I do not see, how this canhelp. The question is then: what is the state of the clocked partition, after re-activation.

I assume, we need some more clarification in the specification text? We tried to be as precise as possible. Our hope was, the formulas and the descriptions are clear enough.

**Comment by KarlWernersson** [comment]
>Inputs and parameters are set by the importer, they stay, where they are from the FMUs point of view.
OK, this is different from fmi3Reset and fmiSetState but they have different scope so its fine.
> No, reset means: go back to the state before as if the activation did not happen.
So in practice that would require that all computed values are buffered not only the clocked states with its previous value, or any external sources that can affect the computation are bufferd (inputs, parameters)

**Comment by KarlWernersson** [comment]
> It is a feature we need: when solving algebraic loops that span the previous and the next value of a clocked variable, there is a need to enable rollback (each new iteration of the algebraic loop needs to start from a fixed previous value, and reach a better next value)

But the previous value will not be updated until newDiscreteState is called, so I don't fully understand why the rollback is needed

**Comment by KarlWernersson** [comment]
> I do not see, how this canhelp. The question is then: what is the state of the clocked partition, after re-activation.

It is computed form the previous value and possibly inputs when requested and the clock is activated.

**Comment by masoud-najafi** [comment]
Just two side remarks. 
--What is an algebraic loop including a clock variable (not a clocked variable)? Is that even possible?
--Then, solving an algebraic loop on clocked-variables is an "atomic" operation, i.e., no independent clock can be activated or deactivated during solving the algebraic equation. But a dependent clock such as output clock of a conditional sampler (if-then-else) may be activated or deactivated. In any case, if solving algebraic equations, requires saving or buffering an intermediate variable, it is up to the importer to deal with that. It is not FMU's business. The FMU may not save any variable except previous-values-of-discrete variables. 
Just my two cents that may be again off topic.

**Comment by andreas-junghanns** [comment]
> So in practice that would require that all computed values are buffered not only the clocked states with its previous value, or any external sources that can affect the computation are bufferd (inputs, parameters)

Yes, at least the states we need the previous values, inputs are under importer control (so ok).
But this should not be new as changes to states are only "locked-in" during fmi3UpdateDiscreteStates (changing previous values).

**Comment by KarlWernersson** [comment]
Sorry I will reopen here again. I want to make sure I understand you correctly. And that this is really what we want. If so we can close it again soon.

say that you have a clock
x = previous(x)*100 +u;
y = previous(x)*1000+u*10;

previous(x) = 1;
previous(previous(x)) = 1/100; (normally not in buffer)
u = 0;

a call to getY before we activate the clock shuld return 10 (1/100*1000+0*10)

now we call set clock.
getY will return 1000.  (1*1000+0*10)
now we call setU(2)  
new call to getY returns 1020 (1*100+2*10);

now we disalbe the clock.

now we call getY
If I understand you correctly @TorstenBlochwitz @clagms y should now return 10 the computed value at the previous clock tick.
This cannot be computed from the current previous values, and if it had bufferd the prepre u has been changed so that doesn't help either.
So this will require a buffer on y and **all other computed variable.**

Why do we need this? How does this helps in solving loops? To solve loops we only need to be able to re-compute y washout updating the previous variables which are done at new discrete states.

Any subsequent call set clock and then get y would immediately return 1020 (if u hasn't been changed). it is the value at activation that are of interest retrieving the value when the clock is disabled is just a convenience

Can't it suffice that disabling a clock inactivates the buffer update.

So if a master has a conditional clock that gets activated and then deactivated. The master knows this, it should not inquire values from this clock until it actives it again.

**Comment by KarlWernersson** [comment]
What i am trying to say is that once you update your previous values, other values that are computed based on them cannot be recomputed without having their own buffers.

This is fine as long as you don't do any computations i.e. don't activate a clock as you can just return the current value.
But once you activate a clock you will start computing and overwriting these values.
As the previous value used for computing the original value as ben overwritten when you updated your buffers. You can only restore these values if you have buffers on them to not only the states. This will then infect require buffers on all computed values.

Thinking a bit more this can probably be handled without extra buffers by doing some different things in your implementation.

But we still have the issue of the inputs.
We have changed them but we shall revert to a state before they were changed. 
This will require buffer on anything that can be affected by the input, or dual memory locations and messy logic to handle this particular case.

Could the master be responsible for restoring them? It would be happy. or will you need buffers for all inputs to a clock to handle this case.

As Masoud says, I would assume that the FMU only would be required to saves the previous values of the states.

**Comment by andreas-junghanns** [comment]
Why should the mechanism for a clocked partition of the model be different than for the non-clocked part?
Previous values of clocked states should also only change in fmi3UpdateDiscreteStates.
If that clock changes a state, say it increments a counter, and then the clock is deactivated before fmi3UpdateDiscreteStates, the FMU can easily set the counter back to its previous value. All dependent outputs can be recomputed when fmi3GetXXX is called on them, including their dependency on the current inputs.

What am I missing?

If the FMU cannot deactive a clock once activated (e.g. executes code with unknown states, i.e. previous values not known), it must declare this by setting the clock variable attribute `canBeDeactivated == false`.

**Comment by KarlWernersson** [comment]
canBeDeactivated == false is of course the soliton if we have this feature, but I would like to avoid optional features if possible. So i need to understand why this is needed. We don't normally do computations and then , oops i changed my mind lest reset everything to before I did my changes but keep some of the changes, but don't let them affect the solution that I computed before my new computations. If this is needed we have Get/SetFMUstate, I understand that this solutions is smaller and more light weight but does it warrant this specific feature.

Disabling a clock is no problem, the problem is requiring results of an past overwritten solution when the clock is inactive. After disabling it.
This requires extra buffers besides the previous of the clocked states.
 If we just state something like the result of variables in a manually disabled clock portion is undefined or invlaid/not to be trusted until activated again. I would be fine.

If this is really what you all want then ok, I will back down.
I just feel it strange especially since I don't fully understand the use case or why its so important to use this instead of GetSetFMU state. 

Another question can you manually disable a triggered clock?
Technically I don't se a problem, but why would you?

**Comment by clagms** [comment]
I hope we can discuss this today at the meeting.

**Comment by clagms** [comment]
> But the previous value will not be updated until newDiscreteState is called, so I don't fully understand why the rollback is needed.

I still need to go over carefully what you wrote, but this assumption is not true @KarlWernersson.
If a clock is active, the corresponding equations are active, and therefore if the Importer queries the value of the discrete variable, then it's value should be computed.

Here's the highlighted rule, from @TorstenBlochwitz 's slides:
![image](https://user-images.githubusercontent.com/871103/114683046-f971ff00-9d0f-11eb-91ee-5b09ec0ea8e0.png)

**Comment by clagms** [comment]
There were some markdown issues with the example you provided @KarlWernersson , so I remade it, and added assertions representing what is true:
```
Clock equation:
  x = previous(x)*100 + u              (Eq. 1)
  y = previous(x)*1000 + u*10

Algorithm: 
  previous(x) == 1 
  previous(previous(x)) == 1/100   (normally not in buffer)
  u == 0
  assert y == 1*1000
  setClock(true)
  assert y == 1*1000
  setReal(u, 2)
  assert u == 2
  assert y == 1*100+2*10
  assert getReal(x) == 1*100 + u    // returns this, but does not commit the value of x and consequently does not erase previous(x)
  assert getReal(y) == 1*100+2*10  // This is still computed from previous(x)
  setClock(false)  // Since no commit was made, this just disables  (Eq. 1)  
  assert getReal(x) == previous(x) == 1
  // Importer is responsible for calling setReal(u, 0) here, so that the following works
  assert getReal(y) == 1*1000
```

The Importer is responsible for buffering u, the FMU is responsible for buffering (i.e., not committing) its internal state.
If UpdateDiscreteStates were called instead of setClock(false), then the value of previous(x) would be updated.

**Comment by KarlWernersson** [comment]
Thanks claudio this is how I would like it to work to, but as I understand, this is not completely true.

First 
the assert before set clock should return y = 10 as that was computed at the last successful clock. (we have implemented a hold on output values)

So this has the effect that in the end you should also. 10 as that was the last successful time point.
To do this you will need one additional buffer on the previous value. Which I think is overkill.
But maybe I have just completely misunderstood your proposal.

**Comment by KarlWernersson** [comment]
I realized it was a bad idea of me to use all those numbers.
I try an algebraic example here

```
setClock(t(1), true)
 previous(x) = x0;
 y(1) = f(x0,u(t1),...)
 x(1) = f(x0,u(t1),...)
new discrete state.
//clock i disabled (internally by fmu since computation is done.

getXXX y -> y1;

//do other things advance time etc.
next tick
setClock(t2, true)
 previous(x) = x1;
 y2 = f(x1,u(t2),...)
 x2 = f(x0,u(t2),...);

getXXX y -> y2;

setClock(t2, false)

//we manually disabled our clock we have to revert the solution to last valid solution.
get Value y -> y1.
```

how to compute y1 now? x0 has been replaced by x1, u(t2) =! u(t1)
you require additional buffer bedside previous(x)

**Comment by clagms** [comment]
FMI Design Meeting:
Main for the ability to disable a clock: a clock c may depends on some variable v that is involved in an algebraic loop. Imagine that as part of the iterations to solve the algebraic loop, v acquires a value that activates the clock. Then imagine that the final value of v no longer activates the clock. Such clock needs to be de-activated by the Importer.
