### ISSUE TITLE
Wrong labels on overview data-flow images

### ISSUE THREAD

**Issue by traversaro** [modelica/fmi-standard#1422]
I was reading the latest dev version of the FMI 3.0 spec (from  https://fmi-standard.org/docs/3.0-dev/#_overview, commit https://github.com/modelica/fmi-standard/commit/02bef77cf908940182099e59be73759018aa6758):

![schemes](https://user-images.githubusercontent.com/1857049/116356176-3bfd0680-a7fb-11eb-97e7-fcef7da464d9.PNG)

and I noticed the following aspects that are not clear to me in Section 1.2.1, 1.2.2 and 1.2.3 (that I was not able to find tracked in any open issue or PR):

1. **z** is used to indicate both *even indicators* and *hidden states*, but given the symbol defined in https://fmi-standard.org/docs/3.0-dev/#mathematical-definitions I guess *hidden states* should be indicated with **b** .
2. In section 1.2.2, the variable **h** (communication step size) is not explained with a short description, as the other variables in the scheme.

**Comment by chrbertsch** [comment]
1. The buffers (currently **z**, shall be renamed to **b**) are present in ME, CS and SE, but in the description in 1.2.2. they are only defined for ME.
![grafik](https://user-images.githubusercontent.com/16363372/116465996-41dfff80-a86e-11eb-902c-d6575b3c74e0.png)
Shall they be removed for CS and SE, or shall we adapt the description of **b** to " A number of hidden data the FMU needs to manage during Continuous-Time Mode. [For example, delay buffers]." (i.e., deleting the reference to ME)

2. @traversaro : 
> In section 1.2.2, the variable h (communication step size) is not explained with a short description, as the other variables in the scheme

you mean 2.1 instead of 1.2.2, right?

**Comment by traversaro** [comment]
>     2\. @traversaro :
> 
> 
> > In section 1.2.2, the variable h (communication step size) is not explained with a short description, as the other variables in the scheme
> 
> you mean 2.1 instead of 1.2.2, right?

Actually I meant 1.2.2, in particular Figure 2. All the variables have a short description inside the blue box, but h does not have it.

**Comment by traversaro** [comment]
Thanks @t-sommer, @chrbertsch and @andreas-junghanns .
