### ISSUE TITLE
ExecutionTime argument for activateModelPartition & pre-condition on SE behavior

### ISSUE THREAD

**Issue by oliverkotte** [modelica/fmi-standard#1439]
**Suggestion**

activateModelPartition() gets an additional argument executionTime, which the importer

- does not use if the FMU can access the same independent variable as the importer, e.g. system real-time.
- may use otherwise, in order to convey to the FMU the time instant when code execution starts

**Reasoning**

For SE to work as described in the spec, the **necessary pre-condition must hold that importer and FMU access the same independent variable**, e.g. system real time (to allow for this, an SE-FMU lacks an internal representation of simulation time).

For SE to work as described in the spec, with each call to activateModelPartition(), information about three time instants (of the common independent variable) must be exchanged between importer and FMU.

1. **activation time point**: "the point of time when the task was scheduled". Passed as argument activationTime.
2. **time point when a task starts execution**: Implicitly passed as time instant of the activateModelPartition() call itself.
3. **time point when a task terminates execution**: Implicitly passed as time instant when activateModelPartition() returns. 

When the above pre-condition does not hold, informations 2 and 3 are not exchanged. When using SE in such a setting, e.g. in SiL on a PC where the importer uses controlled simulation time as independent variable, the FMU has no way of knowing the instant in simulation time when the code in one of its model partitions starts execution (unless the activationTime argument is "overloaded"/"hacked" to convey information 2. instead of 1.). Depending on use case, this may or may not be a problem. The suggestion above would allow the importer to pass information 2. to the FMU in case it needs it.

But the underlying question seems to be, how (defined) shall SE behave in use cases where the above pre-condition does not hold (and which may therefore fall in the Co-Simulation with Events domain)?

**Comment by andreas-junghanns** [comment]
I don´t think I should be the one answering - leaving this to @IZacharias and @MBlesken ...

**Comment by andreas-junghanns** [comment]
I don´t think we need more time stamps: in an RTOS, tasks do not get the current time with their activation either. A task that needs that time needs to be programmed to get it through other means.

**Comment by pmai** [comment]
I don't know about SE, but in co-simulation with clocks I would expect the clock that activates a time partition to get the actual time it is activated (what is called information 2 in the above), not information 1, which seems imaginary. Similarly, I would expect a clock for the end of execution of a "task" (or any other time in between that is relevant for data-exchange) to be "triggered" (either internally from the FMU, if it has an execution time model, or externally from the simulator/some other FMU if the execution time model resides outside/is synchronized somewhere else) at the actual point in time that the execution is supposed to end.

Given that SE is just a way to control resource usage for real-time systems from the outside, I would expect the same to be true there, i.e. the clock that coincides with the activation of the partition gets the actual time the partition gets executed, and additional clocks are triggered for end of calculation (rather sharing of outputs) purposes again at the actual points in time that this is supposed to happen (in other words simulation time and real-time must be made to coincide for real-time simulations).

Given that this topic is so fraught with questions and design choices for the interface, maybe this warrants implementer's guide documentation and/or even a layered standard on how to do the clocks...

**Comment by oliverkotte** [comment]
To me, it seems

- CS is designed for simulation of systems where the independent variables can be controlled.
- SE is designed for systems where there is one "independent variable", e.g. system real-time, that cannot be controlled but that can be accessed.

SE is by design well suited for real-time use cases, but when SE is applied to controlled simulation time use cases for which it was not designed, limitations/questions arise that are not present if CS would have been used instead. These could be mitigated by extensions such as the one suggested above. If such extensions are not desired then, as stated in #1440, SE seems mainly to be usable for realtime simulation, and this should be clearly stated.

**Comment by andreas-junghanns** [comment]
I do not see only real-time use cases for SE. We would need to put the scheduler outside the FMU to achieve real-time capabilities, less dramatic means would have allowed that.

SE externalizes the scheduler to combine tasks from different FMUs into the control of a single scheduler (including variable exchange at the appropriate points in time). This is completely orthoganal to the real-time aspects. If that is not clear, it needs to be clarified in the text.

**Comment by oliverkotte** [comment]
An external scheduler that combines tasks from different FMUs into the control of a single scheduler can be wrapped as an FMI for CS as well, with clock connections to model partitions in the other thus controlled FMUs for CS - why not?

In my understanding, what is needed for simulation of virtual ECUs in controlled simulation time is clocks and model partitions, not SE. So I would argue it is the other way round, SE enables real-time use cases, and the externalization of the scheduler is orthogonal (in the sense it can be done either with SE or CS, the choice is determined by realtime / controlled time).

**Comment by andreas-junghanns** [comment]
> An external scheduler that combines tasks from different FMUs into the control of a single scheduler can be wrapped as an FMI for CS as well, with clock connections to model partitions in the other thus controlled FMUs for CS - why not?

Yes, agreed. But what is that point? You can wrap multiple ME FMUs into a single CS FMU, we still have ME as interface.

> ... is the other way round ... the scheduler is orthogonal ...

I don´t understand - orthogonality does not imply causality.

dSPACE has contributed heavily to the design of SE and they want to use it for real-time and non-real-time applications and think it can be done. The use case that comes to my mind (much more limited, or course) is also possible (proven by brain-simulation).

I do not understand why we need additional time information and which use case is currently not possible.

I suggest we stop this ping pong here and discuss this at the next Web-Design meeting. Please.

**Comment by MBlesken** [comment]
@oliverkotte @andreas-junghanns I would also suggest that we take the discussion on the use cases to the design meeting.

Maybe it helps to distinguish vocabulary here: SE is designed to improve the simulation of realtime scenarios. But realtime scenarios are not only simulated on realtime simulators. **Running realtime scenarios on offline simulators is a very important use case.**

Other than that, I understand that @oliverkotte's original intention of this issue was to discuss whether the importer needs to provide the FMU with a **_current time_**. Concerning this matter: This _current time_, if I understand the intended semantic correctly, cannot be handed over as an argument when calling the activateModelPartition. (In “reality” it would hardly ever be different from the activationTime.) A new API provided by the importer to evaluate the _current time_ could be a valuable feature. (Idea: Align it to AUTOSAR_SWS_TimeService)

BUT: We should question the importance of the feature with respect to the FMI 3.0 release.  I am in favor to postpone this to a 3.1 or 3.2 version of the FMI.

**Comment by chrbertsch** [comment]
Regular Design Webmeeting: 

Oliver: Figure 46 in https://fmi-standard.org/docs/3.0-dev/#example-scheduled-execution makes sense in realtime.
What happens with SE non-realtime? The intention of figure 46 could be realized with CS with events.

Andreas: in CS you cannot preemt a task. One could with SE split such a setup in mutliple FMUs

Oliver: You can event mode activate clocks/tasks. This is possible since the new clocks in January. They can react to unforseen events. An external scheduler can trigger execuation of tasks. 

Matthias: SE is designed to simulate realtime scenrios, can also be in non-reatlime

Klaus: do you slow it down to realtime?

Matthias: you could do it in non-realtime, as fast as possible

Klaus: I do not see how one can meaningfully simulate preemption in non-realtime

Andreas: Use case: one can use an SE in non-realtime

Andreas: in a zero execution time model you would not have this problem

Matthias: but with intermediate update  [...]

Andreas: RTOS use cases might be easier to simulate in SE than in CS with lots of clocks. We do not have triggerdBy attribute. SE is more effificient, you do not have event handling.

Klaus: Every SE FMU could be realized as a CS FMU with clocks. But one would need to transform it. 

Andreas: in a CS FMU: if you trigger a clock, you can only do it in event mode. Any time a task is computing, you would be in event mode (real part of time advancing is stopped)

Klaus: in CS the doStep is empty, just advances time.

Christian: (from a discussion with Pierre): The important concepts are the clocks, not SE. We need  clocks at every time instant where a communication takes place

Andreas: in chip simulation

Andreas: if every SE FMU can be transformed to a SE FMU ...

Klaus: ... or a ME FMU ...

Andreas: even then, can you run a SE in non-realTime ....

Andreas: do you want to forbid non-realtime usage of SE

Christian: For what would you need the "StartOfExecution time"?

Oliver: if the code itself needs it (currently I do not need it)

Andreas: normally RT SW  gets time from the OS with a call.

Andreas: Using SE in non-realtime can make sense, if you do not want to export it as CS FMU.

Oliver: in offline simulation to my understanding one needs start and end clocks.  With this in mind one does not have a difference in SE and CS. Matthias would use it differently

Matthias: ... I am not so familiar with event model in CS. I will discuss it with Irina.

Oliver: the main intention of the ticket was not the additional time argument, but more the difference or usage of SE for non-realtime.

Andreas / Christian: let's table this discussion, and discuss it again with @pmai .

**Comment by andreas-junghanns** [comment]
Is this issue still relevant? Or can we close?

**Comment by chrbertsch** [comment]
Perhaps this could be discussed as a side-topic on the discussion between @MBlesken  and @oliverkotte on 30.9. (invitation went to fmi-design). @pmai : will you join that discussion?

**Comment by oliverkotte** [comment]
I would second @chrbertsch 's suggestion, as in my view this issue is even closely related to our Ref-FMU discussion on 30.9

**Comment by MBlesken** [comment]
**Meeting notes "Controlled Clocks FMU with CS and SE"**, September 30th, 2021 11:00-12:00 (UTC+01:00) 

**Participants**: Oliver Kotte, Matthias Blesken, Andreas Junghans, Laura Beermenn, Christian Bertsch, Jorge Bernal, Masoud Najafi, Patrick Täuber, Pierre R. Mai, Klaus Schuch, Tortsen Blochwitz (@oliverkotte @MBlesken @andreas-junghanns @chrbertsch @pmai @klausschuch @TorstenBlochwitz ...)

**Conclusion**: SE doesn't seem to fit for Oliver's use case (-> [Controlled Clocks with CS and SE](https://github.com/modelica/Reference-FMUs/pull/109)) We want to identify were the standard could be improved so that the reader gets  a better understanding of the different interface types and time concepts. (The challenge will be at the same time not to limit potential users down what they consider the standard to be useful for.) We already decided that Klaus will provide concrete feedback on the the current standard. We would also like Oliver to take part in it.

**Comment by chrbertsch** [comment]
@oliverkotte : after merging https://github.com/modelica/fmi-standard/pull/1546: do you still see necessary changes, or can this issue be closed? Could you otherwise please propose concrete wording?

**Comment by oliverkotte** [comment]
#1546 has addressed this issue and much more
