### ISSUE TITLE
Allow Clock variables to have a previous attribute?

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1444]
From the document, it's not explicitly forbidden to have a Clock variable with a previous attribute.
I think this should not be allowed, and, if so, the constraint might be added somewhere near text:
```
only clocked variables (i.e. variables with the attribute clocks) may have the previous attribute
```

PS - Issue identified by @nickbattle while upgrading the [FMI check tool](https://github.com/INTO-CPS-Association/FMI-VDM-Model)

**Comment by andreas-junghanns** [comment]
"... this should not be allowed..." : Can you propose what we should write in the text as to why this should be forbidden?
Is it a matter of semantic inconsistency (e.g. "a clock cannot be a state and therefore cannot have a previous value").

This is related to #1442, because only clocked variables can have previous variables and if a Clock variable is a clocked variable, it could be a state. I will remark in #1442 w.r.t. to this.

**Comment by clagms** [comment]
Thanks for the quick feedback @andreas-junghanns . 
I will try to provide PRs for these and the other recent issues I've opened, by the next weekend.
Just need your sanity check on them to make sure they are issues indeed.

**Comment by andreas-junghanns** [comment]
> 
> 
> Thanks for the quick feedback @andreas-junghanns .
> I will try to provide PRs for these and the other recent issues I've opened, by the next weekend.
> Just need your sanity check on them to make sure they are issues indeed.

@clagms : Did this get solved with the recent changes?

**Comment by clagms** [comment]
Thanks for the reminder @andreas-junghanns .
This kind of depends on https://github.com/modelica/fmi-standard/issues/1442 because it could be fixed by simply disallowing `clocks` attribute for Clocks:
```
The following constraints [to the previous attribute] apply: only clocked variables (i.e. variables with the attribute <<clocks>>) may have the <<previous>> attribute; 
```

**Comment by t-sommer** [comment]
FMI Design Meeting: remove "previous" attribute for Clocks.
