### ISSUE TITLE
Evaluation of outputs only in clocked partitions

### ISSUE THREAD

**Issue by rfranke** [modelica/fmi-standard#1450]
Let a clocked partition be described with state equations (1) and output equations (2)
```
xd(k) = f[xd(k-1), u(k), t(k)],     (1)
yd(k) = g[xd(k), u(k), t(k)]        (2)
```
Sometimes it is needed to only evaluate output equations (2) for given states xd(k). This is similar to the initialization of clocked continuous-time models, where equation (1) above is replaced with xd(k)=xd(k-1).

The concept [Franke, Mattsson, Otter, Wernersson, Olsson, Ochel, Blochwitz: Discrete-time models for control applications with FMI, Modelica Conference 2017](https://ep.liu.se/ecp/132/057/ecp17132507.pdf) introduced the argument `subactive` to `fmi2SetClock`. 

The current documentation of FMI 3 defines
```
typedef fmi3Status fmi3SetClockTYPE  (fmi3Instance instance,
                                      const fmi3ValueReference valueReferences[],
                                      size_t nValueReferences,
                                      const fmi3Clock values[],
                                      size_t nValues);
```
with
```
typedef            bool fmi3Clock;    /* Data type to be used with fmi3ClockActive and
                                         fmi3ClockInactive */

/* Values for fmi3Clock */
#define fmi3ClockActive   true
#define fmi3ClockInactive false
```

How can the evaluation be restricted to output equations?

**Comment by clagms** [comment]
Thank you for laying out the equations in the issue @rfranke . Makes it possible to be more precise.

> How can the evaluation be restricted to output equations?

Maybe I misunderstand the problem, but isn't this done by the FMU, when `getReal( yd )` is invoked, and the clock `d` is active?

In other words. Suppose clock `d` is active at super-dense time instant `(t, i)`, then the FMU knows that equations (1) and (2) have become active (active equations means part of them will be computed when `getReal` is called for one of the variables).
When the importer invokes `getReal( yd )`, then `f` is computed (because `g` depends on `xd` and then `g` gets computed).

If the importer did not trigger the update of all variables in `xd` or `yd`, then the FMU will do so anyway, when the `UpdateDiscreteStates` function is called.

As far as I understood, this "lazy" evaluation model no longer requires the use of the subactive flag, but I might be wrong of course, and there was quite some confusion regarding this flag.
See also: https://github.com/modelica/fmi-standard/issues/890

**Comment by rfranke** [comment]
> In other words. Suppose clock d is active at super-dense time instant (t, i), then the FMU knows that equations (1) and (2) have become active (active equations means part of them will be computed when getReal is called for one of the variables).
> When the importer invokes getReal( yd ), then f is computed (because g depends on xd and then g gets computed).
> 

That's exactly the difference with `subactive`. Only equation (2) should be computed in this case.
Think of a simple use case: apply finite differences to obtain the Jacobian dg/dxd(k) by perturbing elements of xd(k) and re-evaluating g.

**Comment by rfranke** [comment]
The already defined type `fmi3Clock` could be extended as follows:
```
typedef            int fmi3Clock;    /* Data type to be used with fmi3ClockActive,
                                         fmi3ClockInactive  and fmi3ClockSubactive */

/* Values for fmi3Clock */
#define fmi3ClockInactive 0
#define fmi3ClockActive   1
#define fmi3ClockSubactive 2
```

**Comment by clagms** [comment]
> That's exactly the difference with subactive. Only equation (2) should be computed in this case.

So then, when `subactive=true`, equation (2) goes from:
```
yd(k) = g[xd(k), u(k), t(k)]        (2)
```
to
```
yd(k) = g[xd(k-1), u(k), t(k)]        (2)
```
Is that right @rfranke ?

**Comment by andreas-junghanns** [comment]
@KarlWernersson and @TorstenBlochwitz : Could you please comment? You are both authors of the paper and the current solution.

@rfranke : The importer has control over when equation (1) (or f()) is exectuted (only in `fmi3UpdateDiscreteStates()`).
So if you want to keep changing discrete states `xd` (and they are exposed), you can.
As long as the clock is active, `get(y)` calls will execute only equation (2) (or g()).
The standard states that active clocks will be deactived only during `fmi3UpdateDiscreteStates()` - so the equations belonging to this clock remain active until then.

I might not understand your initial question, but feel free to contact me directly to discuss this - it is high time we clarify this in case we need to make significant changes to the standard, we should make them yesterday.

**Comment by rfranke** [comment]
@clagms: You can also say that with subactive equation (1) changes to -- similar to initialization phase for clocked differential equations:
```
xd(k) = xd(k-1)         (1)
```
@andreas-junghanns: unfortunately the importer does not have this control. `fmi3ClockInactive` skips (1) and (2), `fmi3ClockActive` computes both as of today. `fmi3ClockSubactive` would allow the importer to only evaluate (2).

**Comment by clagms** [comment]
@rfranke I see what you mean. I think we still have to hammer out the exact semantics of these clocks.
Me, you, and Andreas, have three different interpretations of this, and one of them must be made explicit in the standard, to avoid misunderstandings.

The paper that you mentioned, while well written and a pleasant read, contradicts your equations, because it defines a model partition as 
```
xd(k) = f[xd(k-1), u(k), t(k)],     (1)
yd(k) = g[xd(k-1), u(k), t(k)]        (2)
```

Can you clarify what the end goal of subactive is?
If all you want is to enable the initialization of the clocked partition, then this is already supported in initialization model (see https://github.com/modelica/fmi-standard/issues/1407#issuecomment-819509403 and in particular review the merged PR to see if we missed anything)
Now let's just focus on clocks ticking in normal event mode, in the middle of a simulation.

If you want to be able to estimate partial derivatives when a clock is active, then this is already supported, if my interpretation is taken as valid (see recap of it below).

## My interpretation

The equations we support are of the form:
xd(k) = f[xd(k-1), u(k), t(k)],     (1)
yd(k) = g[xd(k), u(k), t(k)]        (2)
where `d` is the clock, and `k>0` (because we're in the middle of the simulation)

When clock d is active, both equations are active.
That means:
- `getReal(xd)` returns `f[xd(k-1), u(k), t(k)]`
- `getReal(yd)` returns `g[ f[xd(k-1), u(k), t(k)] , u(k), t(k)]`

If, before calling `updateDiscreteStates`, function `setClock(d, inactive)` is called, then the effects are not permanent.
That means: no assignment has been made to `xd(k)`

If function `updateDiscreteStates` is called, and clock `d` is active, then it
1. computes `xd_aux = f[xd(k-1), u(k), t(k)]` from equation (1)    (may have been cached)
2. commit changes: xd(k-1) = xd(k) ;   xd(k) = xd_aux 

Numerical derivatives can be computed while the clock is active. Then the clock can be deactivated if the changes are not meant to be permanent.
If the FMU does not support the ability to use some kind of double buffering to avoid making changes permanent for clock d, then it can use the canBeDeactivated=false attribute on clock d to state so.

**Comment by rfranke** [comment]
The requirement is to compute the output equations g independent of state equations f. As said above, the numerical determination of partial derivatives dg/dx is one use case -- at any time and not with respect to parameters, but with respect to states.
This would be no problem if clocked systems were defined more classically as
```
xd(k) = f[xd(k-1), u(k), t(k)],
yd(k) = g'[xd(k-1), u(k), t(k)]
```
But then the output equation g would always use "old" states, i.e. introduce a delay into the system response. This is avoided with
```
xd(k) = f[xd(k-1), u(k), t(k)],
yd(k) = g[xd(k), u(k), t(k)]
```
The remaining issue is the ability to compute g independently from f.

@andreas-junghanns: your interpretation of computing f only during `fmi3UpdateDiscreteStates` might work as well. Though this is not what we test implemented in Dymola and OpenModelica back in 2016/17 -- would need to be further investigated.

**Comment by chrbertsch** [comment]
@andreas-junghanns : 
What is not clear to me: can fmi3getXXX not also trigger the calculation of new discrete states according to 
![grafik](https://user-images.githubusercontent.com/16363372/122338567-2f19ab00-cf40-11eb-8a84-07a491bda6a2.png)
in https://fmi-standard.org/docs/3.0-dev/#EventMode?
How can this be distinguished from only evaluating the output equations?

**Comment by clagms** [comment]
Summary phone call between Andreas & Claudio:

Problem 1:

> apply finite differences to obtain partial derivatives dg/dxd(k) by perturbing elements of xd(k)

Claudio missed this in the description above. 
Also, how do you intend to perturb the clocked states?
Currently, in event mode, it is not allowed to set clocked states.

Problem 2:

If `f` is executed in `UpdateDiscreteStates`, then xd(k) cannot be read after invoking `UpdateDiscreteStates`, because the clock `d` is no longer active and, according to the current mechanisms, we can only read clocked variables when the clock is active.

**Comment by clagms** [comment]
@rfranke I'm sorry for having missed the detail about the derivative wrt to xd(k).
Can you clarify how you see the two above problems being solved?

**Comment by KarlWernersson** [comment]
Problem 1,
There is no point in setting the state as, it is overwritten by the f() equation.
If f() isnt evaluated during subacitve it would not be an issue to set the state, as the set would only affect the outputduring subative, it the clock is later set to active and state sets dring subactive  will be overwitten byt the f equations when the clock is actvie.

Problem 2:
I think there is some confusion here, who wants f to be evaluted during UpdateDiscreteStates. That's just a backup if it wasnt evaluted befure to dot missing getXXX calls

**Comment by KarlWernersson** [comment]
My proposal is to do a Rüdiger proposes. change to enumeration of inactive active and subactive.

During subactve, discrete states are not computed, only discrete outputs. 
During subactve discrete states can be set. (as long as the previous variables are not touched this is safe and will not affect computations if the clock is later set to act vie, especially since clocked variables are not valid when clock is disabled.)
Sub active clocks does not update buffer (state->previous) when newDiscreteState is called.

In addition
when a clock is set to inactive or newDiscreteState is called with subtractive
x[k+1]=x[k]  i.e x := previous of x.

This is to restore the state for eventual subative computations. Otherwise subative will not work if a clock i active->get(xxx)->inactive->subactive
As the value of x would now be unclear if we don't reset the state.

**Comment by KarlWernersson** [comment]
The reset of state could also be done at the call setClock(subactive) to be less restrictive on implementations.
(but must not be done during a getXX call as that would overwrite any setXXX tot the state)

**Comment by clagms** [comment]
Thank you for the input @KarlWernersson !

On problem 2 we are in agreement, but can you elaborate a bit more on Problem 1?
My understanding is that, in order to perturb the states `xd` , one has to have a function to set `xd`, before calling `getReal(yd)`.

I recognize the importance of Rüdiger's use case, but I'm having trouble identifying the mechanisms needed to make it work.
Let's assume that we allow the function `setReal(xd)` to be called. Then we have to redefine the semantics of event mode, to allow not just setting inputs, but also clocked states (recall the table in `2.3.5. State: Event Mode`). Moreover, this would have to be restricted only to clocked states of clocks that are currently subactive (otherwise, you have a variable that is written both by the FMU and by the importer, leading to a mess, imho).

Unfortunately, I don't have a proposal for anything 

> My proposal is to do a Rüdiger proposes. change to enumeration of inactive active and subactive.

This is unfortunately not enough, because for output triggered clocks, it's only the FMU that is allowed to setClock(k). In that case, what would the importer do, if it wanted to calculate numerical derivatives?


> In addition
> when a clock is set to inactive or newDiscreteState is called with subtractive
> x[k+1]=x[k] i.e x := previous of x.
> 
> This is to restore the state for eventual subative computations. Otherwise subative will not work if a clock i > active->get(xxx)->inactive->subactive
> As the value of x would now be unclear if we don't reset the state.

I can't understand this @KarlWernersson ...

**Comment by chrbertsch** [comment]
Part of the problem in trying to make Rüdigers proposal match with the the current fmi3beta text is, that one cannot  find f and g of 
```
xd(k) = f[xd(k-1), u(k), t(k)],
yd(k) = g[xd(k), u(k), t(k)]
```
in the standard text, only f_event, which seems to be the union of f and g. 
I think we have to make the distinction between f (state update) and g (output calculation) explicit, if we want to be describe a behaviour fulfilling Rüdiger's requirements.

**Comment by rfranke** [comment]
PR #1462 attempts to formulate this in the documentation.

**Comment by clagms** [comment]
# Discussion online design meeting 23-06-2021


Karl & Rued: the updateDiscreteStates function only copies the new state into the previous state.

## Current Interpretation

```
  xd(k) = f[xd(k-1), u(k), t(k)],     (1)
  yd(k) = g[xd(k), u(k), t(k)]        (2)
```

```
getRe(xd)
  return f[xd(k-1), u(k), t(k)]

// Not Allowed (and Pointless): setRe(xd, V) 

getRe(yd)
  return g[ f[xd(k-1), u(k), t(k)] , u(k), t(k)]
              -----xd(k)------------

updateDiscreteStates():
  xd(k) = f[xd(k-1), u(k), t(k)]
  xd(k-1) = xd(k)

```

Root of the problem:
- xd cannot be perturbed
  - it is ignored in getRe(yd)
  - it is overwritten in updateDiscreteStates()

## Desired Feature

Karl:
- Clocked states can be set by the Importer
- we need subactive because of the example below.

```
  xd(k) = f[xd(k-1), u(k), t(k)],     (1)
  yd(k) = g[xd(k), u(k), t(k)]        (2)
```

```
setClock(d, active)

xd_nom = getRe(xd)

setClock(d, subactive)

getRe(xd)
  implB:
    return xd(k) // possibly undefined
  implA:
    if (subactive){
      returns xd(k) // this requires that setClock(d, subActive) will initialize xd(k)=xd(k-1)
    } else {
      return f[xd(k-1), u(k), t(k)]
    }

setRe(xd, xd_nom + epsilon_0):
  xd(k) = xd_nom + epsilon_0

// assert getRe(xd) returns xd_nom + epsilon_0

yd_pert = getRe(yd)
  if (subactive){
    return g[xd(k), u(k), t(k)]
  } else {
    return g[ f[xd(k-1), u(k), t(k)] , u(k), t(k)]
              -----xd(k)------------
  }

dg/dx = (yd_pert - yd_nom)/epsilon_0

updateDiscreteStates()
updateDiscreteStates impl:
  xd(k) = f[xd(k-1), u(k), t(k)]
  xd(k-1) = xd(k)

```

## Questions

- From Pierre: subactive is "not clean". Maybe we can change the API to make it closes to the Model Exchange, giving control to the Importer over when xd is assigned.
  - We need Torsten B. et al.
- From Claudio&Andre: how do we set the state 𝑥?
- From Christian: how do we distinguish f and g?
- From Christian: how does this apply to co-simulation?
- From Christian: is this optional feature?

**Comment by pmai** [comment]
Further discussion in the meeting seemed to lead to the conclusion that a solution would probably be to make the point in time when discrete states are updated explicit through a function that does just that (could be a new function or could be updateDiscreteStates with a special flag that does the update, but does not do the deactivation, and hence allows further work on the updated state/accessing state and outputs).

Being explicit here would not only enable the use case for @rfranke, but could allow a number of other use cases, like e.g. changing inputs and calculating outputs with or without state update in between, etc. It would also make the specification much easier to write in understandable terms, because now the point in time when something is updated is much more explicit, and less implicit ("can update xd", "updates xd if it hasn't happened before").

The one concern was that this might make the API harder to support for FMUs that only have one-shot clock activation and state update (cf. controller code), but it was thought that much of that could actually be fairly unified and at the most a capability flag might be needed.

In any case going through the motions of designing such a solution would be worthwhile, because even if we decide against this for 3.0, it would be good to understand our current design better and to check whether we would understand an extension of this sort if introduced in 3.1 (could be a new optional function to force update, and if not present/used we fall back to 3.0 semantics).

Discussion to be continued at next design meeting.

**Comment by rfranke** [comment]
Updated PR #1462 accordingly. Removed `subactive` again (making it the standard for f_event) and introduced the new function `fmi3EvaluateDiscreteStates` instead that must be called at least once between clock activation and finalization with `fmi3UpdateDiscreteStates`.
This should reflect today's discussion. It is certainly not yet complete (e.g. regarding a possible capability flag).

**Comment by masoud-najafi** [comment]
The current FMI standard uses the following discrete equation set
  xd(k) = f[xd(k-1), u(k), t(k)],     (1)   //getReal(xd)
  yd(k) = g[xd(k), u(k), t(k)]        (2)   //getReal(yd)

This equation set can be transformed into the following well-studied CANONICAL discrete equation by replacing xd(k) in (1) into (2)
  xd(k) = F[xd(k-1), u(k), t(k)],     (3)
  yd(k) = G[xd(k-1), u(k), t(k)]      (4)

So my question is why instead of (3) and (4), which are theoretically well studied, (1) and (2) have been used in the standard? 
Using (1) and (2) leads to this SubActive issue, which is not present if using (3) ad (4).

**Comment by rfranke** [comment]
The intension was to separate state transitions/equations from output equations. See also the minutes of discussions in two FMI design webmeetings given in #1462. Your equation (4) would combine state and output equations into one:
yd(k) = G[xd(k-1), u(k), t(k)) = G'[F[xd(k-1), u(k), t(k)], u(k), t(k)]
SubActive remains removed. Instead, `fmi3EvateDiscreteStates` gives explicit access to the state transition.

**Comment by chrbertsch** [comment]
Reopened, as the PR #1462  was merged w/o documented approved review. 
Can be closed after some more approving comments on th already merged PR

**Comment by andreas-junghanns** [comment]
> The intension was to separate state transitions/equations from output equations. See also the minutes of discussions in two FMI design webmeetings given above. Your equation (4) would combine state and output equations into one:
> yd(k) = G[xd(k-1), u(k), t(k)) = G'[F[xd(k-1), u(k), t(k)], u(k), t(k)]
> SubActive remains removed. Instead, `fmi3EvateDiscreteStates` gives explicit access to the state transition.

Yes, yes, all present at the time discussed and agreed the intent is good to open a new use case with more control over which part of the equations in EventMode are computed.
What we are missing is more brains working through the mechanics of the changes to make sure that we do not break other things AND that the proposal achieves what is intended.
I agree that we need to be extra careful this late into the development to make sure we do not introduce unintended consequences. @TorstenBlochwitz : Please comment.

**Comment by masoud-najafi** [comment]
But having more equation control would lead to unnecessary complexity. Just consider the continuous-time case:
It is like you you want to use these equation 
x'=f(x,u)
y=g(x',x,u)
instead of 
well studied
x'=f(x,u)
y=h(x,u)

The first one would lead to DAE and brings in its problems and its complexities. I do not understand why this choice, may be I am missing something....

**Comment by andreas-junghanns** [comment]
I would also like to add that some tools might not be able to separate both sets of equations and we might have to guard the use of fmi3EvaluateDiscreteStates with a capability flags.

**Comment by rfranke** [comment]
Also having tools in mind that cannot separate state from output equations, we introduced (section 2.3.5. State: Event Mode, `fmi3UpdateDiscreteStates`):

"Evaluate f_disc, if no `fmi3EvaluateDiscreteStates` function was called in this instant of super-dense time."

This allows an importer to ignore `fmi3UpdateDiscreteStates` if no separate evaluation of state equations is needed.
This also means that an exporter does not necessarily have to provide this functionality. Just a capability flag might be needed to flag to importers requiring this functionality that they cannot use the respective FMU.

**Comment by clagms** [comment]
Although the original [PR](https://github.com/modelica/fmi-standard/pull/1462) was in decent shape, I've made a continuation of it in https://github.com/modelica/fmi-standard/pull/1484

The main changes are:
- I tried to unify the notation between the event mode semantics (Section `2.3.5. State: Event Mode`), and the notations used in Section `2.2.9. Clocks`.
- I changed the notation of the output function to depend only on the previous state, to avoid the confusion that @masoud-najafi mentioned could happen. I think the previous notation `yd(k) = g[xd(k), u(k), t(k)]` makes the reader think that evaluating the output function also triggers the update of the state. This is not the case. So I've update the notation to `yd(k) = g[xd(k-1), u(k), t(k)]` and explain that `f` can be embedded in `g`, to give it the same level of expressiveness. The other benefit for this is that it is easier to explain what `fmi3UpdateDiscreteStates` and `getReal(yd)` do, without having to make it explicit that the later does not depend on the former.

I would like to challenge the decision to make `fmi3UpdateDiscreteStates` not clock specific:
- Right now, its meaning is: update all clocked states of every clock that is active. 
This is not so clean because different clocks may have different limitations, as the way the function is defined now, means that the FMU has to bundle all active clocks into the same limitation. Example: a clock cannot have its clocked states updated separately from the outputs, and therefore the importer must not call fmi3UpdateDiscreteStates, meaning no other clocked states can be updated.
- In addition, what happens if a clock is activated after a call to fmi3UpdateDiscreteStates ? Should it be invoked again? What happens to the existing clocks that have transitioned state?

IMHO, the semantics of the standard needs an overall, and it would be nice to organize a write fest to try to tackle this (with a big ass whiteboard).
There are multiple dynamics inside the same fmu: the traditional event equations (with discrete states and active equations) and the clocks (each bringing its own set of discrete states and output equations).
Right now, it feels that some of these are bundled together in a function called f_event, and it is not clear what does function consists of.

**Comment by andreas-junghanns** [comment]
> x'=f(x,u)
> y=g(x',x,u)
> instead of well studied
> x'=f(x,u)
> y=h(x,u)
> 
> The first one would lead to DAE and brings in its problems and its complexities. I do not understand why this choice, may be I am missing something....

@masoud-najafi and @clagms : web-design meeting (Andreas+TorstenB): The propsed PR #1484 by @clagms addressing @masoud-najafi´s concerns, breaks @rfranke use case: @rfranke needs output computation to be dependent on the "current" state (x_k) such that he can disturb that state to see how the outputs change.

Tools that cannot separate f and g must indicate that by a (new) capability flag providesEvaluateDiscreteStates. If false, calling g triggers execution of f implicitly. If the flag is true, then you MUST call evaluateDiscreteStates() or is is automoatically executed in updateDiscreteStates().

**Comment by clagms** [comment]
web-design meeting (Andreas+Claudio): @andreas-junghanns and @TorstenBlochwitz are right: the output function must depend on the current state, and not on the previous, because it must be possible to perturb the current state and get the partial derivative of the output function with respect to it.
Andreas will work on a new PR, and I'll salvage small parts of my PR before closing it.

@masoud-najafi I agree with your comment about the extra complexity. But we had meetings in the past that showed that such complexity is sometimes needed for more advanced cases (like the model predictive controller, or the implementation of an implicit solver). These will introduce algebraic loops that the importer needs to handle (and the importer has access to the dependency information to determine this).
So, if it's too much complexity, an FMU can always export clocked partitions that only depend on the previous state. The mathematical notation covers both cases...

**Comment by masoud-najafi** [comment]
With respect to the original system
xd(k)=f(xd(k-1), u(k), t(k))
y(k)=g(xd(k-1), u(k), t(k))
I do not like

xd(k)=f(xd(k-1), u(k), t(k))
y(k)=G(xd(k), xd(k-1), u(k), t(k))

 for two reasons:
1) If the system has an input, the system's feed-through becomes systematically TRUE, regardless of presence of u(k) in g(.)
2) For any simple explicit system if you have feedback, the importer should solve a non-linear system to obtain xd(k). If the system is purely explicit,  you you SHOULD not solve a system it is very annoying for embedded systems to do iterations.
Take this system for example:
xd(k)=0.5*xd(k-1)+u(k)
y(k)=xd(k-1)
It is clear that the feed-through is FALSE, so if you add a feedback loop u(k)=K*y(k), you do not need to do any iteration for the simulation.
Now lets express the same system in your format
xd(k)=0.5*xd(k-1)+u(k)
y(k)=2*xd(k)-2*u(k)

You observe that the feed-through becomes TRUE. and having the same feedback loop u(k)=K*y(k), needs doing iterations.

Another important drawback of the new format is the requirement for a new API, which is not really needed.

Remember that the DAE for the continuous-time system has been dropped because only one tool needed it.

**Comment by andreas-junghanns** [comment]
@masoud-najafi : are you saying we just need to drop u(k) from G() to solve your issue of direct feedthrough?

@rfranke : do you need output computation to depend on current input settings? Or is it sufficient that y(k) = G(xd(k), xd(k-1), t(k))?

**Comment by masoud-najafi** [comment]
@andreas-junghanns 
This is not exactly what I mean. You cannot drop drop u(k) from G(). If you do it, the feed-through becomes ALWAYS False, regardless of the original feed-through.
 I mean introducing xd(k) in G turns "systematically" a non-feed-through system into a Feed-through system. That's bad.

**Comment by andreas-junghanns** [comment]
> @andreas-junghanns
> This is not exactly what I mean. You cannot drop drop u(k) from G(). If you do it, the feed-through becomes ALWAYS False, regardless of the original feed-through.
These formulas only say what can be *at most* influence the left-hand side. So you can of course have a system that ignores a parameter, such as u(k).

> I mean introducing xd(k) in G turns "systematically" a non-feed-through system into a Feed-through system. That's bad.
How? We just split the previous mechanisms into two equations.
For a full state evaluation, both f() and g() must be executed.
And again: simply ignore u(k) to have a system without direct feedthrough.

**Comment by TorstenBlochwitz** [comment]
@masoud-najafi : From my point of view, allowing xd(k) to appear in G does not mean that ALL clocked partitions systematically become direct feed through systems. I do not understand why y(k)=xd(k-1) becomes y(k)=2xd(k)-2*u(k). To my understanding, this is a completely different system. If y(k) does not depend on xd(k), then G is simply empty for xd(k).

Please take a look at the current pull request of @andreas-junghanns. We tried to allow both representations and a way for the FMU to signal what is inside.

**Comment by masoud-najafi** [comment]
@andreas-junghanns 
You cannot simply ignore u(k) to have a system without direct-feed-through. Just consider this example:
xd(k)=0.5xd(k-1)+u(k)
y(k)=xd(k-1)+u(k)
which has a direct-feed-throught.  Now if you represent it in the new form, you will have

xd(k)=0.5xd(k-1)+u(k)
y(k)=2*xd(k)-u(k)
This system has also direct-feed-through. Now, if you simply drop u(k), you lose this information. You cannot do it.
My point is  1)the new form is always direct-feed-through 2 )converting a non-direct-feed-through to a feed-through system increases the cost and requires iterations where it is not needed.

**Comment by masoud-najafi** [comment]
@TorstenBlochwitz 
>> I do not understand why y(k)=xd(k-1) becomes y(k)=2xd(k)-2*u(k).
If you allow tools represent a discrete system in the form of 
y(k)=G(xd(k), xd(k-1), u(k))
then this system

xd(k)=0.5xd(k-1)+u(k)
y(k)=xd(k-1)

can be presented by a tool represent 

xd(k)=0.5xd(k-1)+u(k)
y(k)=2*xd(k)-2*u(k)

this two systems are perfectly identical, because replacing xd(k) in the second results in the first. 
the only difference is their direct-feed-through. the second becomes unnecessarily an implicit system.

**Comment by rfranke** [comment]
Yes, outputs can directly depend on inputs for direct feed through.
@masoud-najafi:

> For any simple explicit system if you have feedback, the importer should solve a non-linear system to obtain xd(k). If the system is purely explicit, you you SHOULD not solve a system it is very annoying for embedded systems to do iterations.
> Take this system for example:
> xd(k)=0.5xd(k-1)+u(k)
> y(k)=xd(k-1)

Your example fits into the current definition. NO NEED to iterate if you prefer this formulation.
Other people prefer (or need) a system response without delay.
  xd(k)=0.5xd(k-1)+u(k)
  y(k)=xd(k)

Both is possible with the current definitions of f_disc and f_event.

**Comment by TorstenBlochwitz** [comment]
@masoud-najafi : From my point of view, you cannot simply transform:
xd(k)=0.5xd(k-1)+u(k)
y(k)=xd(k-1)

to:
xd(k)=0.5xd(k-1)+u(k)
y(k)=2xd(k)-2u(k)

xd(k-1) is a constant at clock tick k. It was computed at the last tick (k-1).

Please take a look at the current (just updated) pull request (#1485) of @andreas-junghanns. We tried to allow both representations and a way for the FMU to signal what is inside:
- FMUs with `providesEvaluateDiscreteStates = True` are able to split computation of discrete states from computation of outputs,
- otherwise: state computation happens explicitly together with the first computation of outputs.
The second case is equal to what was defined before @rfranke 's request.

**Comment by andreas-junghanns** [comment]
@masoud-najafi : please review and approve PR #1485

**Comment by masoud-najafi** [comment]
Would you please show me the way I can get the rendered document, it is hard to read and check it by looking into the file changed in the PR.

**Comment by chrbertsch** [comment]
> Would you please show me the way I can get the rendered document, it is hard to read and check it by looking into the file changed in the PR.

@masoud-najafi : 
In the PR: Click on the "check" of the latest commit
![grafik](https://user-images.githubusercontent.com/16363372/127215277-17018c1f-bc72-495b-bd7f-c40e76920b8a.png)
Click on the "Details" of the "build_spec"
![grafik](https://user-images.githubusercontent.com/16363372/127215681-79f5d199-0e7c-4a21-bda4-70f69aba17af.png)
(if not already done: log in to CircleCI with your Github credentials)
Click on "Artefacts" to Download the zip file with the generated html-spec
![grafik](https://user-images.githubusercontent.com/16363372/127215588-a6c70c2e-8184-4700-9823-d0feab5819be.png)
