### ISSUE TITLE
Revisit modelIdentifier description and source-code PREFIX handling

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1498]
- modelIdentifier really only useful for static linking
 - what is the default in the FMUs source code we support?
 - move examples to Implementer´s Guide

**Comment by MBlesken** [comment]
@andreas-junghanns meanwhile I had a chance to talk to @APillekeit abou this issue. (@IZacharias is not and will not be available for an unknown period of time.) Since you discussed the same questions in issue #420 and PR #549 extensively for more than half a year in several meetings and since boundary conditions have not changed (still the same requirements towards tools and specifications, still the same technical options) and especially since we are intending to publish the 3.0 soon I am closing this issue.

@pmai if needed please find another issue to set a marker "move examples to Implementer´s Guide". Thanks.
