### ISSUE TITLE
Clarification for IntervalQualifier 

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1513]
It is not clear in the specification the IntervalQualifier argument in fmi3GetIntervalXX should be used for which type of clocks? Only in SE it has been explained. For example, there is no definition for fmi3IntervalNotYetKnown at all even for SE.

**Comment by andreas-junghanns** [comment]
Only `countdown` clocks are asked during every Event Mode about their next interval and that is because only these `countdow clocks may change their mind about when the next activation will be.
All other clocks must announce exactly when they will tick next.
Asking more than once should return the same interval plus the `fmi3IntervalUnchanged` to indicate that the interval did not change.
Otherwise we would need to define that the interval value still refers to the last tick of that clock or worse, recompute the remaining time until tick with all the floating point issues that would cause.
The API does not allow asking again for `changing` clocks (only query during the Event Mode when this `changing` clock ticked).
