### ISSUE TITLE
fmi3GetShiftX for "fixed" interval periodic clock

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1516]
Unlike other periodic clocks it is not mentioned that fmi3GetShiftX is allowed to be called in initialization, see table 5 (Overview of Clock types).  I wonder if there is a reason for that?

**Comment by andreas-junghanns** [comment]
This is because `fixed` clocks only allow setting. As it states, SetInverval can be done. Setting the initial shift period seems kind of odd - the first clock tick is triggered by the importer anyway, why would the FMU need to know?

If we have a use case to also tell the FMU about the shift, we could easily add this function and then define it useable for `fixed` clocks.

**Comment by masoud-najafi** [comment]
Suppose the shift values are not changed by the user. The importer should be able to get the shift value either from XML or from binaries? If it is not allowed to call fmi3GetShiftDEcimal in the initialization, the importer SHOULD use XML to get the shift value.

**Comment by andreas-junghanns** [comment]
> 
> 
> Suppose the shift values are not changed by the user. The importer should be able to get the shift value either from XML or from binaries? If it is not allowed to call fmi3GetShiftDEcimal in the initialization, the importer SHOULD use XML to get the shift value.

Agreed, that would sound a bit strange to force the importer to read the value from the XML and not allow reading it from the FMU. I will create a PR.
