### ISSUE TITLE
clarify "coinciding"

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1519]
"Only time-based Clocks must not be active for more than one call of fmi3UpdateDiscreteStates per Event Mode. 
The importer must ensure that coinciding time-based Clocks are activated at the same instant of super-dense time."

1) I have a hard to time to understand this statement, rephrasing may help.
2) What does "coinciding" means? Does it mean two clock ticks are "synchronous" (i.e., have the same clock origin) or "simultaneous" (i.e., having the same activation time)?
I guess it should be "synchronous", because the simulator may activate "simultaneous" clock ticks one after another and not in the same super-dense time. So please clarify the meaning of "coinciding" somewhere.

**Comment by andreas-junghanns** [comment]
"Coinciding" means these clocks have the same activation time, e.g. meet every second activation time of one of the clocks because of the double-length interval of the other.
We should require them to be activated in the same super-dense time instant because we want a deterministic execution. If we allowed the importer to activate these clocks arbitrarily, then global variables which may be used by two model partitions could change differently depending on clock activation order.

**Comment by masoud-najafi** [comment]
Then we need absolutely define some key words such as "Synchronous", "simultaneous", "asynchronous"  (used in other synchronous languages such as Esterel or Signal) or "Coinciding" to avoid confusion.
Suppose that there are two clock sources, one periodic with period 1.0 and shift=0.0. So there are ticks at t=0.0,1.0,2.0, etc.
There is another "changing" interval clock and creates the same series of ticks at T=0.0,1.0,2.0,3.0,etc.

These two clocks are simultaneous (asynchronous), that means they do NOT NEED to be activated at the same super-dense time.
Do we agree on this?

**Comment by andreas-junghanns** [comment]
Web Design Meeting: We should relax the current text and remove the "coincide"-sentence, but warn that time-based clocks ticking at the same Event Mode do not necessarily tick at the same instant of super-dense time.
