### ISSUE TITLE
Resetting the clock by FMU

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1522]
Consider an FMU with an input countDown clock (clk_d) that delays another input clock tick clk_i. 
The qualifier of interval of a countDown clock which is retrieved in event-mode, is usually fmi3IntervalNotYetKnown. Only when clk_i ticks, the interval of clk_d can be retrieved with qualifier fmi3IntervalChanged.
Now the question is when getIntervalDecimal()  should be called, before or after fmi3UpdateDiscreteState().
If before, clk_i is still Active and getIntervalDecimal() can check the clk_i clock status and return the interval with qualifier=fmi3IntervalChanged.
But if called after fmi3UpdateDiscreteState(), clk_i is no longer active (reset by the FMU itself). Unless the FMU implements a buffer mechanism to ensure that clk_i has been ticked during current super-dense time, it is impossible to retrieve the correct interval.

In brief, forcing the FMU to reset the clock in fmi3UpdateDiscreteState()  adds the complexity to the FMU. 
The importer can very well reset the clocks that has set during the current super-dense time. 
I do not know why the importer should be forbidden from doing this "easy" clock reset with the price of adding the complexity to the FMU. If it is decided to keep the current restriction on resetting the click by the FMU, the FMU exporter should be warned about this (maybe at the implementation guide).

**Comment by andreas-junghanns** [comment]
Web Design Meeting:
 - With the current mechanism, importers can ignore triggered output clocks (except switching into Event Mode at the correct point in time). Otherwise it would have to actively deactivate the output clock after it was activated by the FMU.
 - During updateDiscreteStates() the clock state (as part of the discrete state) gets updated anyway.
 - Actively deactivating a clock resets the state of the corresponding model partition back to what it was before the activation. Auto-deactivation of still active clocks in updateDiscreteStates() allows us to have the clocks active when "updating the discrete states" of this clock (model partition).
 -  Was also needed for Rüdiger´s requirement for the computation of derivatives w.r.t. states.

Buffer issue: group agrees is needed as described by Masoud.
