### ISSUE TITLE
Handling the very first event in FMI3/CS

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1532]
Currently, in the section 4.2, we can read:

“Importers can directly switch a Co-Simulation FMU into Event Mode without calling fmi3DoStep to handle events immediately after initialization.”

What do you think about changing this to 

“If hasEventMode capability flag attribute is “true” and if the importer sets eventModeUsed to fmi3True, Importers must directly switch a Co-Simulation FMU into Event Mode without calling fmi3DoStep to handle events immediately after initialization."

This change is required. Consider, for example, an FMU (FMI-3.0/CS) that creates  a time event series [T1>0, T2, T3,….] by using nextEventTimeDefined and nextEventTime arguments of fmi3UpdateDiscreteStates.

This mechanism for creating event series works fine in FMI3/ME, because just after initialization FMU goes to the EventMode, but for CS it is does not. It is not possible to program the very first event in FMI/CS. The only possibility is to SYSTEMATICALLY push the FMU to EventMode right after initialization.

If we want to make this kind of FMU work identically in any importer we may need to do the above minor change in the specification to make sure that for an FMU with event  goes to the event Mode right after initialization.
CC: @t-sommer @KarlWernersson

**Comment by andreas-junghanns** [comment]
Let me try to rephrase what you want to add:
"If the FMU declares `hasEventMode == true` and the importer indicates `eventModeUsed == fmi3True`, then the first call to `fmi3EnterEventMode` must happen before the first call to `fmi3DoStep`."

This is a clarification we can add but that is different from allowing to call `fmi3EnterEventMode` directly from Initialization Mode.
Is my proposal above sufficient?

**Comment by masoud-najafi** [comment]
This is exactly what I mean. Thanks.

**Comment by andreas-junghanns** [comment]
FMI Design Meeting: Group agrees to have a direct transition from Initialization Mode to Event Mode IFF `eventModeUsed == fmi3True` (otherwise it goes to Step Mode).
Agree: all
Abstain: none
Against: none

Discussion on the name of the state transition. Two options: 1) land with fmi3ExitInitializationMode() in Event Mode or 2) use `fmi3EnterEventMode` to transition from Initialization Mode to Event Mode.
1) Pierre, TorstenB, Masoud, Matthias, Klaus, AndreasJ, Christian
2) none
3) no opinion: TorstenS, Timo
