### ISSUE TITLE
Clarification on providesDirectionalDerivatives/providesAdjointDerivatives in Scheduled Execution mode

### ISSUE THREAD

**Issue by dchne** [modelica/fmi-standard#1553]
In FMI 3.0 specification "2.3.4. Super State: Initialized", fmi3GetDirectionalDerivative and fmi3GetAdjointDerivative are mentioned as follows:

> Function fmi3GetDirectionalDerivative
> See fmi3GetDirectionalDerivative. This call is not allowed in Scheduled Execution.
> 
> Function fmi3GetAdjointDerivative
> See fmi3GetAdjointDerivative. This call is not allowed in Scheduled Execution.

It is confusing to reader whether the function call is not allowed within "Super State: Initialized", or in any states when simulation mode is Scheduled Execution. Other occurrences of these functions imply they can be called in Scheduled Execution mode. Clarification may be required.

**Comment by andreas-junghanns** [comment]
@MBlesken : I think @dchne has a point about clarity. Do you agree that in SE no derivatives can be computed at all?

**Comment by chrbertsch** [comment]
Webmeeting:
Klaus: If it is a continuous variable, why should partial derivatives not be allows.
If the FMUs cannot provide them, it can signal it via capability flags.
Patrick: in SE in model partitions we only have discrete variables
Klaus: we could have direct feedthrough. Discrete means only discrete in time. A simple example would be a gain function. A directional derivative w.r.t to the input would be possible as in model exchange.
Karl: I agree, but I question whether its useful.

**Comment by andreas-junghanns** [comment]
Is there consensus what to do here? Or even, if anything has to be done at all...?

**Comment by chrbertsch** [comment]
> Is there consensus what to do here? Or even, if anything has to be done at all...?

In 2.2.11 only ME and SE is explicitely mentioned for partial derivatives. We should clearly state if they are allowed in SE (if supported by the FMU) or not.

Currently calling of the `fmi3getDirectionalDerivatives `and `fmi3getAdjointDerivatives `is forbidden, because these calls are not listed in the allowed function calls of https://fmi-standard.org/docs/3.0-dev/#ClockActivationMode

So currently the corresponding flags providesDirectionalDerivatives/providesAdjointDerivatives do not make sense in SE.

In the use cases listed for partial derivatives in 2.2.11

> Partial derivatives can be used:
> 
>     in Newton algorithms to solve algebraic loops,
> 
>     in implicit integration algorithms in Model Exchange, and
> 
>     in iterative co-simulation algorithms.
> 

in my opinion do not fit to SE, as we have nothing iterative in SE.

(If we would allow partial derivatives in SE: it is not clear to me, if the knowns and unknows that we refer to in the definition of the partial derivatives would have to be belong to the same model partition.)

**Comment by andreas-junghanns** [comment]
Web Design Meeting: The FMU can signal if it can provide derivatives - no need to restrict usage because capability flags exist to signal availability.
