### ISSUE TITLE
Add info on "What is allowed"

### ISSUE THREAD

**Issue by MBlesken** [modelica/fmi-standard#1565]
Is FMI compatibility restricted to the calls that are defined in fmi3Functions.h? When is the FMU allowed to call other functions? Do we describe that as a RESTRICTION or an EXTENSION (i.e. a layered standard)?

Example:
* **Is the FMU that opens an Ethernet Port FMI conform?**
* **Is an FMU that opens threads for a certain OS FMI conform?**
* **Is an FMU opening a file in the working directory of a system FMI conform?**

**Comment by andreas-junghanns** [comment]
This issue was raised by in interesting discussion between @MBlesken and @andreas-junghanns:
"What calls is an FMU allowed to make?"
While @MBlesken has the strictest of interpretations stemming from the real-time platform world (essentially: what is not allowed is forbidden), I (@andreas-junghanns ) consider the opposite to be the base of the FMI standard:
"The FMI standard only describes the API exposed to the importer, but makes no restrictions towards the OS it is running on. The FMUs can use whatever system resources the system offers (files, network, memory, CPU/threads,...)."
This is how I see almost all existing FMUs to be implemented: malloc calls, network connections opened, temp files created, resources read...

The answer to this question above has a direct bearing on how we write Layered Standards. In my opinion, Layered Standards can only further constrain the behavior/packaging of the FMU (requiring more files to be present in /extra, restring variable names,. requiring certain clocks to be present,..). Matthias would like Layered Standards to add more freedoms to the FMU.

I think Matthias´ view would hurt the basic principle that an FMU of a Layered Standard must always conform to the base FMI standard.

Please weigh in on this issue!

**Comment by andreas-junghanns** [comment]
Note: We have to make this clear in "2.6. Versioning and Layered Standards" once we reach agreement here.

**Comment by chrbertsch** [comment]
While I agree with Andreas' point of view, we should make clear what has to be documented (in the documentation folder? or even in the xml?), so that users of FMI do not get "bad surprises" when they run an FMU.

**Comment by MBlesken** [comment]
Especially in [Chapter 1.3](https://fmi-standard.org/docs/3.0-dev/#_properties_and_guiding_ideas) the standard reinforces that the FMU code cannot make assumptions on the environment it is supposed to be run in:

> **Processor independence**
It is possible to distribute an FMU without knowing the target processor. This allows an FMU to run on a PC, a Hardware-in-the-Loop simulation platform or as part of the controller software of an ECU. Keeping the FMU independent of the target processor increases the usability of the FMU. To be processor independent, the FMU must include its C (or C++) sources.

On a HIL simulator as well as on an ECU it is in particular the OS that differs from a PC, not (just) the processor.

> **Simulator independence**
>
> It is possible to compile, link and distribute an FMU without knowing the environment in which the FMU will be loaded.
>
> Reason: The standard would be much less attractive otherwise, unnecessarily restricting the later use of an FMU at compile time and forcing users to maintain simulator specific variants of an FMU. To be simulator independent, the FMU must export its implementation in self-contained binary form. This requires that the target operating system and processor be known. Once exported with binaries, the FMU can be executed by any simulator running on the target platform (provided the necessary licenses are available, if required from the model or from the used runtime libraries).

Of course on a HIL simulator or an ECU there is no complete Windows or Linux distribution available. Thus there cannot be made any assumptions of availability of certain OS functionality (e.g. starting threads).

**-> The processor and  simulator independence we aim for is guaranteed only if the set of interface functions allowed to be called by the FMU code (compiled or not) is explicitly listed in the standard.**

**Comment by andreas-junghanns** [comment]
Why do we have binaries in directories with platform names? -> to indicate what platform the binary will run in. The platform is the OS+services compiled and linked for. I would call this "the contract down" from the point of view of the FMU.

The FMI functions are "the contract up" from the point of view of the FMU (see simulator independence).

Source code is somewhat more flexible because the "contract down" is still abstract until compiled/linked (see platform independence).

**Comment by MBlesken** [comment]
> So for me the most important point is that assumptions on ressources such as file systems, OS calls, etc. are well documented.

@chrbertsch To me it seems like that can be a solution. We should further discuss this.

> Why do we have binaries in directories with platform names? -> to indicate what platform the binary will run in.

@andreas-junghanns There are HIL simulators or even ECUs that provide Linux. Still it doesn't mean that these binaries can run on these platforms if they assume functionality of a full-blown desktop linux to be available.

**Comment by andreas-junghanns** [comment]
> @andreas-junghanns There are HIL simulators or even ECUs that provide Linux. Still it doesn't mean that these binaries can run on these platforms if they assume functionality of a full-blown desktop linux to be available.

The documentation can go a long way to tell the user what is needed to run an FMU.
However, if an FMU has a binary in a win32 folder, I take that as "I will run on a 32-bit standard windows".
For Linux, this is - unfortunately even for desktop versions - quite a bit more confusing, but I would assume basic services like files, memory and network to be available if the platform is called linux64.
If your platform is seriously restricted, then you need to check, if the actual needs of a linux64 FMU are meet by your system.
Currently, we do not ask the FMU to document its needs on the platform it runs on (files, memory, CPU usage, network...).
Maybe that is something we have to look into in future?

**Comment by MBlesken** [comment]
> If your platform is seriously restricted, then you need to check, if the actual needs of a linux64 FMU are meet by your system.

So far it is not stated in the standard what consumer and producer of an FMU can/should derive from the fact that a binary is located in a linux64 folder. I don't think that we want the existing of a non-empty linux64 folder in the binary directory to be the interface of an FMU to signal to the importer that the FMU assumes that it can call e.g. pthread_create.

... so we should talk about this concerning the FMI 3.0.

**Comment by pmai** [comment]
The x86_64-linux | linux64 identification refers to the operating system, not to the kernel. And while the definition of what is or is not part of the Linux OS might be fuzzy in the corners, at the very least POSIX or LSB compliance has to be assumed. So a platform that does not support e.g. pthread_* should in my not so humble opinion not advertise itself as x86_64-linux, but should use a more specific tuple. If it wants to, it can try to run x86_64-linux binaries, but if they break it is on their head...

And I see this as being equally true of FMI 2.0 and FMI 3.0, since it is actually impossible to create FMUs that only use the FMI API, since even the basic dynamic-linking startup code that is present in any binary FMU makes use of platform features, even before the generated code would get any chance of running.

And we already provide a list of stuff an FMU is explicitly forbidden from doing (like e.g. change current working directory, or changing of FPU flags without restoring them) in FMI 2.0, which would make no sense if the FMU were not allowed to call the platform ABI/API.

**Comment by sjoelund** [comment]
>  So a platform that does not support e.g. pthread_* should in my not so humble opinion not advertise itself as x86_64-linux, but should use a more specific tuple.

That's not really the problem. The problem would be what version of libc can you assume? If I link an FMU on Ubuntu 20.04, it will not work in Ubuntu 16.04 because its GNU C library is not recent enough. You cannot statically link libc/libm/etc easily on GNU/Linux.
Oh yeah, and you cannot assume it is even GNU libc that is being used. If the user runs Alpine Linux with musl libc it will not run your FMU https://www.alpinelinux.org/about/

**Comment by pmai** [comment]
> > So a platform that does not support e.g. pthread_* should in my not so humble opinion not advertise itself as x86_64-linux, but should use a more specific tuple.
> 
> That's not really the problem. The problem would be what version of libc can you assume? If I link an FMU on Ubuntu 20.04, it will not work in Ubuntu 16.04 because its GNU C library is not recent enough. You cannot statically link libc/libm/etc easily on GNU/Linux. Oh yeah, and you cannot assume it is even GNU libc that is being used. If the user runs Alpine Linux with musl libc it will not run your FMU https://www.alpinelinux.org/about/

Well, arguably Linux (the OS - not necessarily the kernel in this instance) is a really broken operating system in this respect (even more so than other broken OSes like Windows). This is however not an unknown problem, and in actual practice is "solved" by being conservative enough in the glibc you link against, and expecting newer/different OSes to provide enough compatibility for long enough for this to be practicable (see e.g. alpine gcompat). Speaking as a tool vendor who has to ship both tools and FMUs on Linux, this is definitely not nice, but certainly doable...

But that is now completely out of scope for FMI (we are not going to save the world against the world's wishes to suffer), and is also a separate issue of what OS/platform functionality FMUs are "allowed" to use.

**Comment by andreas-junghanns** [comment]
The discussion sounds like we have a choice. But I do not think so:
 - we did not restrict what OS services FMUs can use in 1.0 and 2.0 (nor in the current FMI 3.0 text)
 - we made a feeble attempt for memory usage and decided to drop it for good reasons
 - existing FMUs, and not just some, but I would wager most, make liberal use of OS services
 - we cannot start restricting OS usage now, when the general practise so far has been the opposite and is needed for most FMUs to work (how would you implement a tool coupling FMU without OS services?)

You can call the current state of the FMI standard on this issue as "undefined" and that is what it is:
 - if you use OS services in the FMU you generate, the FMU might or might not work
 - there are platforms out there that provide mostly stable OS services and API towards those and there the issue can be trivially ignored
 - users on platforms with "issues" are aware of these and are not surprised and know how to communicate their OS configurations
 - if you use a platform that is more restricted then the one you derive it from, you need to specify those restrictions and clearly communicate them to the FMU producers (and even for those generating C-code FMUs, because C-code may use malloc, fopen...)
 - maybe it is a good idea to define a new platform string for such platforms, e.g. x86_64-linux-minOS, and define it in a layered standard

**Comment by MBlesken** [comment]
It is important to vendors to signal that they share "common ground" with other vendors and are thus potentially compatible with each other. Therefore I would NOT support introducing a new platform string to address compatibility issues. I think we can agree that it is _risky_ to derive compatibility information from the string "x86_64-linux" and introducing new string won't solve that problem.

"If the FMU depends on external resources [e.g. shared libraries, files, or servers] to be loaded or simulated documentation/externalDependencies.{txt|html} must be present to document these dependencies and how to provide them." is already mentioned in the standard.

I hope we can agree to add _a hint_ in the standard that an FMU that is compiled or can be compiled with gcc and only depends on the GNU Libc is likely supported by most linux based FMU importers.

**Comment by TorstenBlochwitz** [comment]
Such a hint might be useful.

But more important (from my point of view) is a clear statement in "1.3. Properties and Guiding Ideas" that the FMI Specification does not restrict the usage of services provided by the operating system the FMU is compiled for. If an importer has restrictions (e.g. no file system available, or what not), this has to be communicated between the people who are involved during the process of model exchange.

**Comment by andreas-junghanns** [comment]
Web Design Meeting: we might want to add an architectural image with FMI at the top, the FMU and the OS/System at the bottom to show that the FMU does have interaction with OS services and that this is part of the FMU exporter to reduce these dependencies for maximum portability.

**Comment by andreas-junghanns** [comment]
When adding a few clarifying sentences, I found that we already state similar runtime.
Please check the changes proposed by the PR #1582 and see the previous versions of the texts I touched to make them more explicit.
