### ISSUE TITLE
Rename the folder "icons"

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-standard#1596]
Currently the folder where the terminalsAndIcons.xml file is to be stored within the FMU is called "icons". From my point of view, icons are much less important compared to terminals. For that reason I would propose to rename the folder to "appearance" or "displayInfo" or "terminalsAndIcons" or something similar.

**Comment by pmai** [comment]
I agree that icons is not a really good name; however appearance also seems a bit underselling, since terminals are about more than mere appearance; so if this is to be renamed I think we should go with something that is less concentrated on aesthetics... `terminalsAndIcons` is a bit ugly, but at least seems less problematic in this regards; maybe just `terminals` or `terminalInfo` is better?

**Comment by TorstenBlochwitz** [comment]
terminalInfo is not enough, since the folder contains data on the icon of the whole FMU too.

The terminal definition is from my point of view about appearance only, from FMU perspective, nothing changes if the information about terminals is utilized by the importer or not.

**Comment by pmai** [comment]
Given that the terminal kinds do prescribe certain semantics of the variables involved, I still think that subsuming this under appearance is a bit misleading.

**Comment by TorstenBlochwitz** [comment]
OK, then let us use terminalsAndIcons!
