### ISSUE TITLE
Sorting of variables in case of structured naming conventions

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-standard#1625]
In section 2.4.7.5.1. Variable Naming Conventions we still have the sentence "The tree of names is mapped to an ordered list of variable names in depth-first order."

It was removed from 2.0.1 which no longer enforces an FMU-exporter to sort the variables according to its names if the structured naming convention is used. The pros and cons were discussed in #413.

I propose not to repeat the discussion, but to remove this sentence from 3.0 too.

**Comment by andreas-junghanns** [comment]
What about flattened array variables (just below the text you mention)?

**Comment by TorstenBlochwitz** [comment]
This is OK from my point of view, but I do not have a strong opinion here.

One argument against the ordering from above was that a user might want to define a certain order of (for example) the parameters inside the FMU (which is often reproduced by importers), which might be overwritten by the sorting required to the structured naming convention. This argument does not hold for multidimensional variables. Here, the elements belong to each other.

**Comment by pmai** [comment]
There is no benefit to prescribing the order of variable entries in the standard: Most importers will do the only sane thing and sort/search the variables in whatever way they need for their algorithms to work, which is not much work and not algorithmically complex. Especially so, since we have enough historical experience in FMI 1.x/2.x that some exporters will break these kind of rules, and therefore relying on external sorting is going to be dangerous.

Less is more in these cases.
