### ISSUE TITLE
Clarify `nominal` default

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1666]
Text says default to be 1. We have no default defined in the xsd - why?

**Comment by andreas-junghanns** [comment]
Other defaults?

**Comment by KarlWernersson** [comment]
No default (or missing) equals 1.0

**Comment by andreas-junghanns** [comment]
> No default (or missing) equals 1.0

Let me try to be clear: if the default attribute is missing in the XSD, it means that the default defaults to 1.0? Not 0?
I did not find this, but I am not even sure how to search for the XSD default for a missing default...

**Comment by KarlWernersson** [comment]
OK could be good to have an xsd expert commenting as i might get something wrong but i will try.

We have quite a lot of optional attributes ie values that don't have a default value but are only relevant if defined e.g. previous, derivative. Others have default values like causality (local)
 Nominal falls a bit between as it only affects continuous time states. However any state that dont have a nominal value would have it implicitly defined to 1.0 
 
So we could change to have a default value of 1.0 but that would make nominal explicit for all float types for whom it normally don't make sense. So i think the current solution is better. But maybe this can be defined in some other fancy way to describe this in xsd that i don't know about

**Comment by pmai** [comment]
The text actually currently states:

> Nominal value of variable. If not defined and no other information about the nominal value is available, then nominal = 1 is assumed.

This is very different from saying that the nominal attribute defaults to 1.0: It indicates that importers have quite a bit of leeway to use other sources (e.g. prior runs, manual configuration, whatever) to derive a suitable nominal value if no value is specified. Only if they have no other source should they assume the value of 1.0.

In order for this to work, the attribute must not have a default value in the XSD, because this makes it hard for implementations to differentiate explicitly passed nominal=1 value, from a missing value, which allows the more open rules to kick in.

So I think the XSD rightly does not provide a default value for the attribute, and I also think that the current specification is the right approach: If no information is passed in the FMU model description, the importer can interpret this correctly as no information is available, and decide whether to default to 1.0 or not.

**Comment by andreas-junghanns** [comment]
All is well, if this is as intended - thanks for the explanation.
