### ISSUE TITLE
New simple type for complex nbs

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#168]
**Reported by jean-philippe&#x2e;tavella on 17 Dec 2013 14:23 UTC**
It should be appreciate by people from the electrical filed to introduce a new simple type for complex.
Do not forget too to add new primitives fmiGetComplex and fmiSetComplex.

----

Migrated-From: https://trac.fmi-standard.org/ticket/168

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 26 Mar 2014 17:19 UTC**
Replying to [ticket:168 jean-philippe.tavella@…]:
> It should be appreciate by people from the electrical filed to introduce a new simple type for complex.
> Do not forget too to add new primitives fmiGetComplex and fmiSetComplex.

This might be added in a future FMI version, but still requires some discussions (because there is no standard representation of Complex numbers in C; it is also still possible to simulate systems with complex numbers as inputs and/or outputs by just using 2 Reals for the real and the imaginary part). For FMI 2.0, this is definitely too late to perform changes here.

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 1 Jun 2018 12:49 UTC**

**Comment by chrbertsch** [comment]
This ticket is open for more than 6 years now and there does not really seem to be a demand for this feature. Otherwise please create an FCP.

With FMI 3.0 we decided to go away from "Real" variables to specifying concrete data types like "fmi3Float64".

This contradicts to my understanding the concept of a complex variable.

As FMI does speficiy only the intereface and not the internal behavior, one can define complex variables as  "x.Re" and "x.Im"  or as an 2-element array z.

Everything else to my understanding goes beyond the intention of FMI.

**Comment by andreas-junghanns** [comment]
Agreed.
