### ISSUE TITLE
FMI3 preemption callbacks - challenging to implement

### ISSUE THREAD

**Issue by lausdahl** [modelica/fmi-standard#1688]
Currently, the callbacks for logging and clock update contains a fmi3InstanceEnvironment pointer.
Among other uses, this pointer allows the receiver to determine the identity of the caller.
This makes it possible to provide a simple implementation of FMI bindings in other languages, such as [the one used in the into-cps association](https://github.com/INTO-CPS-Association/org.intocps.maestro.fmi) where a process `P` manages a map from real FMUs to corresponding Java FMUs.
When a callback is made from an FMU, `P` determines which Java FMU corresponds to it thanks to the `fmi3InstanceEnvironment` pointer of the callback.

Example good callback:
````
typedef void (*fmi3ClockUpdateCallback) (
    fmi3InstanceEnvironment  instanceEnvironment);
````

The new preemption callbacks of the Scheduled Execution interface do not contain this information:
````
typedef void (*fmi3LockPreemptionCallback)   ();
typedef void (*fmi3UnlockPreemptionCallback) ();
````

Unless there is a smart C or C++ trick that is implementable in standard C/C++ there doesn't seem to be any way to implement these functions in an elegant way. 

The only solution I see is to pre-implement X number of static callback functions and then pass a new function onto the each newly instantiated FMU.
An error is thrown when the more than X instantiations are made.
This is of course less than ideal...

Can we not make the callback functions of the Scheduled Execution interface consistent with all other callback functions?

I understand that the importer may not care about which FMU is locking or unlocking preemption, but it could just ignore that value...

The issue has initially been discussed with @clagms

**Comment by andreas-junghanns** [comment]
The reasoning for not having the instanceEnvironment pointer in the callback was that in SE the importer knows which of the model partitions currently runs and thus can determine which instanceEnvironment to use.
A second argument was the simpler implementation/forwarding of preemption control calls inside existing embedded code.

Lastly: we are quite late in the release process for such a change.

@MBlesken : Do you have other arguments?

**Comment by lausdahl** [comment]
Hi @andreas-junghanns I get your point but it seems odd that these two callbacks are so different from the others and I just dont see a way to implement a library that can proxy these calls. There is no way of knowing who the sender is unless you also intercept the logic controlling the FMUs (I assume that is what the SE importer does).

I could not find any standard C/C++ way to implement a dynamic bound function. Could someone at least describe how to implement this as I dont know on compile time how many FMUs or FMU instances will be created or which ones of the ones created will be simulated together.
We had no problems with the other type of callbacks with the environment as its simple and does not rely on additional semantic rules to determine the source of the callback.

**Comment by pmai** [comment]
The usefulness of proxying these calls without regard to the implemented scheduling strategy seems to me to be suspect:

Even assuming that one would want to run SE FMUs from Java (or some other higher-level language), the implementation strategy would be the same as one would employ in C/C++:

The callbacks are supposed to allow zones of exclusive access to be created; hence the implementation is intimately tied to the scheduling regime employed by the importer: If everything is run single-threadedly, they devolve into no-ops. If multi-threading is used, they are implemented using whatever exclusion mechanism one wants to employ. If anything is needed in terms of additional information (which usually isn't, except maybe for debugging purposes), one would use thread-local storage. In no conceivable circumstance does the implementation need to pass something into the FMU to get back to identify the relevant parts.

The other main reason these callbacks are different is that they are extremely performance sensitive: Ideally they should not have been callbacks at all, but rather inline code, but that is impossible to do portably for non-source FMUs. So even the call overhead is already a bit problematic. Adding additional arguments to the callback would make this worse, directly, and through the effort the FMU would need to go through to have the information handy at the critical sections.

For the other callbacks this is much less of a problem, since they are not intended to be used in performance critical situations. So while the environment argument is not strictly needed anymore, it is present to make live nice for implementations that want to use it.

**Comment by andreas-junghanns** [comment]
Closing after exchange of arguments. This is not likely to be changed now or in future for the reasons given above.

**Comment by MBlesken** [comment]
> @MBlesken : Do you have other arguments?

Much was said. I can add a remark: I wouldn't exclude that some importer might like to distinguish between several FMUs. But even then a workaround/ solution exists that seems acceptable to me: 
> ... pre-implement X number of static callback functions and then pass a new function onto the each newly instantiated FMU.

**Comment by clagms** [comment]
It's alright to close this. We won't support Scheduled Execution in our Java FMI bridge.
