### ISSUE TITLE
Should FMI3_FUNCTION_PREFIX be defined inside the FMU for Source code?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1703]
In the specification you read:

When compiling an FMU C-file the macro FMI3_FUNCTION_PREFIX must be defined before the #include <fmi3Functions.h>

If this prefix is defined inside the FMU, there is no way to compile the FMU for source code on the fly and generate DLLs without the prefix.  The only way is to load the DLL with static linking.

**Comment by andreas-junghanns** [comment]
The previous proposal does not allow overwriting the hard-coded prefix.
I suggest:
`#ifndef FMI3_FUNCTION_PREFIX`
`    #define FMI3_FUNCTION_PREFIX MyModel_`
`#endif`
This way,
 - previous examples work identically AND
 - you can make `FMI3_FUNCTION_PREFIX` go away by defining it empty `-DFMI3_FUNCTION_PREFIX=""` (but defining it!) or
 - you define it "your" way: `-DFMI3_FUNCTION_PREFIX=YourModel_`.

**Comment by Maplesoft-fmigroup** [comment]
That's also fine but then the specification has to be updated because currently it states that the prefix value must match the modelIdentifier as defined in the modelDescription.xml.

**Comment by klausschuch** [comment]
If the exporter defines the (default) prefix, we cannot drop the request that this prefix must match the modelIdentifier in the specification. How would the importer know the default prefix otherwise (without parsing the files)?
The importer would have to set the prefix to know which prefix is used.

Why should the exporter define a prefix at all? If the importer imports only one FMU statically and number of FMUs dynamically, the prefix is useless; and if the importer imports more than 1 FMU statically, the importer needs to ensure that the prefixes are different.

We should only request that the exported code must be prepared to use FMI3_FUNCTION_PREFIX if given.
