### ISSUE TITLE
Clarify if in which state discrete variables can be set in CS w/ event mode 

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1717]
Currently [the Spec reads](https://fmi-standard.org/docs/3.0-dev/#discrete):

> Co-Simulation: The value may change at communication points and in [Event Mode](https://fmi-standard.org/docs/3.0-dev/#EventMode), if supported.

So it's not clear whether discrete values can change at communication points if Event Mode is used.

On a similar note, does the importer have to enter Event Mode if a non-float value (e.g. a crank speed sensor providing its value as an `UInt64`) changes?

**Comment by KarlWernersson** [comment]
Since we now require CS FMU's to declare if they will use event mode. I don't see it as practical to no enforce event mode for changing discrete values of a CS FMU if it uses event mode, as they are forced to do it for other events.

Integers are discrete values and therefore a change requires event handling. as events are discrete changes.
So if the FMU uses event mode it has to enter event mode each time an integer changes its value.
