### ISSUE TITLE
Removal of event-related arguments to fmi3EnterEventMode()

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#1739]
(from an Email of Andreas Junghanns to fmi-design)
During the sessions of the just concluded FMI 3.0 PlugFest VII, the intention as been raised to remove event-related arguments from fmi3EnterEventMode().

**Reasons:**
These arguments can only be informative and FMUs would need to carry event detection mechanisms anyway if they want to be prepared for “lazy” importers.
The current text shows the difficulties on clearly defining the optionality of the information carried by the event “flags” and to make sure that this mechanism cannot be misunderstood as a way to control event handling from the importer.
If such control is required by the importer, Clocks must be used, as Clocks move control of when exactly a Clock is active to the importer.

**Process:**
You have until next Wednesday, April 13, 1pm CEST, to raise your concerns **against** removal of all event-related arguments to fmi3EnterEventMode().
The FMI Design Meeting will start one hour after this deadline at 2pm CEST (April 13) to take the final decision on whether to remove these arguments or not.

**Comment by chrbertsch** [comment]
(from an Email of @clagms ) 
I’d like to raise a concern: I recall relying on this mechanism in the synchronous clock example, to tell the FMU that it should activate the (event based) clock when entering event mode.
Without that, the FMU itself (which is a model exchange FMU) has to check the event indicators and see if the event corresponding to the clock is the cause of entering event mode.
This is a problem because the tolerance used by the FMU to check for event detection may be different than the tolerance used by the importer.

**Comment by otronarp** [comment]
Since we couldn't agree upon making them mandatory the last two times this was up for discussion (#1042, #589), they did end up being pretty useless. So unless it's possible to agree on making them mandatory I'm all for removing them.

**Comment by andreas-junghanns** [comment]
Please keep this issue here open and discuss the issue about the removal of the event flags and eventIndicatorDomainChanges[] array.

For those not part of the two days discussion, here what I think the issue is about:
If the importer needs exact control over when event handling must be executed, Clocks are the way to do it.
And every time an FMU is pushed into Event Mode, the importer can then call fmi3SetClock to tell the FMU that a specific clock is active NOW and needs handling NOW.

This is different to the other event types.
Unless we transfer similarly strict control over when a certain event type happens inside a specific Event Mode, the FMU must determine which events are currently to be handled.
 - state event: check FMU internal event indicators
 - input event: check if discrete variable was changed or continuous variable was change "too much" (violating continuity assumptions) when FMU receives fmi3SetXXX calls
 - step event: was raised by the FMU anyway using enterEventMode of fmi3CompletedIntegratorStep
 - time event: was raised by the FMU anyway using nextEventTime of fmi3UpdateDiscreteStates

The core of the issue is not when importer and FMU agree. The issue is that importer and FMU might disagree whether the event is currently reached for a specific event type or not. It was strongly argued that we cannot allow the importer to force or mask events using these flags ("force": the FMU must fire an event even if the FMU disagrees, "mask": tell the FMU to NOT fire an event even if the FMU would want to handle it).

Note again: For Clocks, this is different as the fmi3SetClock was designed to trigger the associated event.

Most understood the intend of the flags like that and the consequence was that the flags would only carry informative character and the FMU could still do what it thinks is right. Once almost the entire group reached that point in the discussion, the pain/gain question was raised: Why have such a complicated mechanism if it carries so little information and FMUs would have to prepare for lazy importers NOT providing this information anyway?

Unless strong reasons are brought forward HERE, we plan to remove these flags and simplify the fmi3EnterEventMode() function dramatically.

**Comment by TorstenBlochwitz** [comment]
> (from an Email of @clagms )
> I’d like to raise a concern: I recall relying on this mechanism in the synchronous clock example, to tell the FMU that it should activate the (event based) clock when entering event mode.
> Without that, the FMU itself (which is a model exchange FMU) has to check the event indicators and see if the event corresponding to the clock is the cause of entering event mode.
> This is a problem because the tolerance used by the FMU to check for event detection may be different than the tolerance used by the importer.

@clagms: We discussed that back and forth: At first we introduced some sentences which clarified that the rootsFound argument must be consistent with the switched signs of the event indicators returned by the FMU according the definition in section 3.1.1. Localization of State Events. This would rebut your point.

However, then some of us argued that an FMU is not able to neglect the information, which event type happens if the importer puts semantics in them (for example to let handle state events first and time events in a follow-up event mode at the same time, if both happen at the same time). For that reason we tried to formulate the description in a way that clarifies that these arguments are for efficiency reasons only and can safely be ignored by the importer. 

Then we realized, that this makes no sense at all and did a poll, which showed a majority for removing them, which I still support.

**Comment by clagms** [comment]
Thanks @TorstenBlochwitz  and @KarlWernersson  for the clarifications.

So the proposal in this issue is to remove the flags stepEvent, stateEvent, and timeEvent, right?
if that's the case, I have no other counter-arguments.

**Comment by andreas-junghanns** [comment]
> Thanks @TorstenBlochwitz and @KarlWernersson for the clarifications.
> 
> So the proposal in this issue is to remove the flags stepEvent, stateEvent, and timeEvent, right? if that's the case, I have no other counter-arguments.

The proposal includes also to drop `rootsFound` (current PR calls it `eventIndicatorDomainChanges`).

**Comment by KarlWernersson** [comment]
So this should not happen if master and FMU are correct.
Master has to make sure that the FMU has moved to a new domain, from negative to positive or positive to negative event indicator.
If this is done correctly the FMU should be able to detect this event in event mode. If the FMU don't detect the event even if the event indicator has had a sing change then there is likely an error with the FMU. 

An event could flip on and of during the same event iteration so it is possible that the end result is the same as before the event.

**Comment by clagms** [comment]
Thanks @KarlWernersson. Even if the importer is going back and forth on the event surface, it has to push the FMU into event mode on the new side of the surface.

**Comment by CSchulzeTLK** [comment]
I think the rootsFound/eventIndicatorDomainChanges is important for a robust ModelExchange implementation. Models which have a small non-deterministic contribution to the event indicators (e.g. by using an embedded nonlinear solver), are less efficient/robust using FMI 1 and 2.

**Only one of the two, FMU or the importer, has to decide if an event had happened or not, and inform the other.**  We should stick to "single source of truth".

If the FMU is free to recalculate the event indicators, it is very likely that some events disappear. The importer cannot know if the event has actually been handled. Therefore the event statistics of the importer is messed up, and the step size of BDF solvers is resetted several times when approaching an event.

**Comment by TorstenBlochwitz** [comment]
From my point of view the eventIndicators are the single source of truth! And both, the FMU and the importer have access to them. The Importer uses them for localization of the correct right point in time, when the event happens (a domain change happens). The FMU uses them to let the relations switch.

From my point of view, rootsFound is redundant information.

Discontinuity sticking is caused by numerical effects or bad models and will happen anyway.

**Comment by TorstenBlochwitz** [comment]
Discussion at FMI Design Meeting (2022/04/22):

Christian: Without rootsFound, the FMU might think, the event vanished. In certain cases (e.g. if eventIndicators depend on results of of non-linear systems of equations), an FMU might not be able to reproduce the the same values for eventIndicators in Event Mode in the same way as it did during event location before the Event Mode.

Hans: I don't think, rootsFound will solve the problem. I think, the problem must be solved by the FMU by for example introducing a proper hystereses.

Pierre, Torsten: We agree. 

Karl: Do we agree to remove the rootsFound argument?

Christian: It would be nice to have it, but if I am the only, then it is OK to remove.

Massoud: I would need this information for triggered clocks.

Torsten, Pierre, Karl: This is the same problem as for state events.

Christian: EventIndicators might be non-deterministic for several reasons.

Torsten, Pierre: Non-deterministic eventIndicators are not a good at all.

Torsten: Should we do a poll on removal of rootsFound?

Are you in favor to remove all event related arguments (including rootsFound) from fmi3EnterEventMode?

In favor: TorstenB, Allan, ChristianB, Erik, Hans, Karl, Kaska, Otto, Pierre, 
Abstain: ChristianS, Matthias, Patrick, TorstenS
Against: Masoud

Torsten: This is a clear picture, so lets remove the!

**TorstenS: I volunteer to make the pull request.**

Massoud: There should be a hint in the implementor's guide. 
Pierre, TorstenB: Please make a proposal in a ticket od pull request of the implemetor's guide.
Otto: It should clarify, that is the FMU which has to introduce the hysteresis, not the importer.
