### ISSUE TITLE
FMU announces what layered standard is supported and which version (and directory)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#1825]
In /extra, there shall be a file `layeredStandards.xml` announcing which version of which layered standard is supported:

Proposal for the structure of the XML:
```
<LayeredStandards>
    <LayeredStandard name="fmi-ls-xcp" version="1" directory="org.modelica.fmi-ls-xcp"\>
    <LayeredStandard name="fmi-ls-xcp" version="1.1" directory="org.modelica.fmi-ls-xcp"\>
    <LayeredStandard name="fmi-ls-xcp2" version="1" directory="org.modelica.fmi-ls-xcp2"\>
    <LayeredStandard name="fmi-ls-bus" version="2.0.1" directory="org.modelica.fmi-ls-bus"\>
    <LayeredStandard name="fmi-ls-struct" version="1.0" directory="org.modelica.fmi-ls-struct"\>
    <LayeredStandard name="ls-foobar"\>
</LayeredStandards>
```
Edit: This is specifically benefitial for humans to know which layered standard is supported by an FMU.

**Comment by andreas-junghanns** [comment]
Alternative:

Each Layered Standard defines its own file inside /extra, e.g. fmi-ls-xcp.manifest to at least define the version, maybe more as needed by the Layered Standard.
Downside: importers not knowing this layered standard do not know the internal structure of the file.

**Comment by pmai** [comment]
Having a central file is a bad idea (tm):

- Note that layered standards make use of the `extra` directory, and hence can be added/removed not only by the original exporter but by any processing implementation (see processing expectations of the `extra` directory). So requiring information on layered standards in one location means that multiple programs need to potentially read and rewrite that file, which has the obvious potential for breakage, especially for stuff that is optional by its very nature.

- The alluded to downside for the alternative (letting each LS handle this in its own way) is not really a downside: Why should any tool be aware of a layered standard and its version if it does not know the LS? There is nothing that implementation can do with the info, except potentially confuse the user.

- Different LS will have different (or no needs) for versioning, and might already try to use versioning mechanisms of another standard they are using. And some will just punt and use implicit versioning (keep stuff completely backward compatible and new features optional, until you need a breaking change, when you move to a new LS/different directory).

In any case it is too late to put a central file requirement into the core standard: It cannot be mandatory, since 3.0 does not talk about this, so if people want to have this, it could just again be a layered standard - though I highly advise against doing so, since it is going to be brittle in exactly the wrong ways.

BTW: Since we currently intend to publish the layered standards as non-MA standards, should they not rather use the `org.fmi-standard.*` prefix than `org.modelica`?

**Comment by andreas-junghanns** [comment]
I agree with your arguments, specifically for the importer mechanics.
Maybe we missed to explain this here better for the motivation: We wanted an easy way for humans to know what layered standards are supported -- would you follow that argument?

**Comment by andreas-junghanns** [comment]
> BTW: Since we currently intend to publish the layered standards as non-MA standards, should they not rather use the `org.fmi-standard.*` prefix than `org.modelica`?

See #1827

**Comment by chrbertsch** [comment]
I agree with your arguments, too, Pierre.

So we would follow the alternative with the  fmi-ls-xcp.manifest each /extra subfolder?  Would this be an xml-file? Then it should have the .xml file ending, perhaps `version.xml`? 
This cannot be mandatory in FMI 3.0, since this is already released, but could be  added in FMI 3.0.1 as a strong recommendation for every layered standard that wants to announce its version.

**Comment by chrbertsch** [comment]
Design Webmeeting: 

Pierre: why do we need a standardized way to announce the support a layered standard? Besides announcing it to the user?
Christian: What is to be done?
Pierre: For a standardized way, we would have to write something down. Personally, I think looking into the extra directory is sufficient.
Andreas: no strong opinion. One could have a manifest file in each extra directory subfolder.
Pierre: we could define a common file format for that. We need version information anyway.
Andreas: regaring a central file or not: decentral files are also good, is a little bit more work. We should specify encoding, linebreaking
Pierre: but this would avoid re-writing problems
Christian: would this be FMI specific? Or MA Layered standard general?
Pierre: could be general. An referenced by a maintenance release for FMI 3.
Andreas: let's define this in FMI, others can reference it.
Pierre: let's not put this into the FMI spec.
Christian: We could have it non-normative in 3.0.1 (perhaps linking to somewhere else)
Andreas: and "threaten" to make it mandatory in 3.1
Pierre: the layered standards still define how they do it exactly.
Pierre: do we want to have this in an xml file? Something else could be appropriate.
Andreas: I am pro-xml, as we use xml already. It is not complicated.

Pierre: I volunteer to create an xsd file

**Comment by chrbertsch** [comment]
Hi @pmai : could you please create a draft so that we can proceed with the FMI 3.0.1 release? Thanks!

**Comment by chrbertsch** [comment]
FMI Design Meeting: 

Pierre: It would be good that FMUs announce which FMU they support.  I opposed having a central file.
One should put certain attributes that one needs anyway. 
One would require an XML file with certain elements on the root level.
