### ISSUE TITLE
fmi3IntermediateUpdateCallback may call Get and Set functions, whose return value cannot be propagated to the FMU

### ISSUE THREAD

**Issue by arubisch** [modelica/fmi-standard#1833]
The FMI 3.0 specification specifies a `void` return value for `fmi3IntermediateUpdateCallback`. But this function is allowed to call `fmi3Get` and `fmi3Set` functions for the FMU, which return an `fmi3Status`. A failure of these functions goes unnoticed, as it cannot be passed back to the FMU after Intermediate Update. 
I feel that a return value of type `fmi3Status` would fit better.

**Comment by t-sommer** [comment]
> A failure of these functions goes unnoticed

The FMU itself is returning the status, so how is that a problem?

**Comment by chrbertsch** [comment]
Webmeeting: 

Torsten: This was discussed before.
Markus: What to do in the case of a problem?
Torsten: There is an output argument from the callback to return early
    fmi3Boolean* earlyReturnRequested,
    fmi3Float64* earlyReturnTime);
Markus: It would be clearer if there were a return value. Then the FMU would not have to remember 
Christian: this would change the signature of the callback, we cannot change this in FMI 3.x

@pmai  : could you please comment

**Comment by pmai** [comment]
I don't know why my opinion should matter here, but as far as I understand the issue, it seems to be a non-issue to me: If any FMU access during the callback causes an error, the FMU can keep track of this state if it needs to, so from the point of view of the FMU this seems very unproblematic (it already has to keep track of its error-state, if it wants to be robust against non-complying implementations, so this does nothing to change the situation).

From the point of view of the importer, we might have preferred a synchronous way of propagating the fault from the callback to the importer, but that would have required co-operation from the FMU. The importer can always keep track asynchronously, and since it has full knowledge of the required locking/synchronization mechanisms it can do so.

In any case as has been pointed out, any changes here would be 4.x material.

**Comment by chrbertsch** [comment]
Thanks Pierre for you comment; closing this issue
