### ISSUE TITLE
Default variability is missing for non-float non-clock non-clocked variables

### ISSUE THREAD

**Issue by antvl** [modelica/fmi-standard#1835]
The variability _attribute_ of the <fmi3Variable> elements is optional (see section 2.4.7.4).
When not present, table 17 specifies a default value for:
- variables of type `Float32` and `Float64`
- variables of type `Clock`
- clocked variables
In all other cases the default value is not defined.

**Comment by chrbertsch** [comment]
In FMI 2.0 the default for variability was continuous.  So this would be a natural choice.

(Or what would it mean if no default for variability gets defined for a variable? Then no parts of the FMI standard, where it is stated "if variabitly = XXX" could be applied for such a variable. Perhaps such variables would not make sense, but would they be problematic? But tables such as https://fmi-standard.org/docs/3.0/#table-allowed-variability-causality-combinations suggest, that variability is defined for each variable, otherwise one would have to add a row for "variabilty = <undefined>")

**Comment by pmai** [comment]
I think the intent in removing the overall default to `continuous` was to avoid a default that is invalid for all types except for Real/FloatXX. So I think what is missing is to state the default value for non-float types, the natural choice would be `discrete`.

The alternative would have been to make variability mandatory, which we didn't, hence this is moot, I think.
