### ISSUE TITLE
Return status when earlyReturn=fmi3True

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [modelica/fmi-standard#1844]
What status value should be returned by fmi3DoStep when earlyReturn=fmi3True, is fmi3OK still acceptable? What about when terminateSimulation is also set to fmi3True?

**Comment by andreas-junghanns** [comment]
> What status value should be returned by fmi3DoStep when earlyReturn=fmi3True, is fmi3OK still acceptable? What about when terminateSimulation is also set to fmi3True?

The way I read our definition of the return codes, fmi3OK must be returned in all cases, because any of these cases are normal use cases.
If this is not clear enough, we should find a place where to state this, please suggest where.

**Comment by andreas-junghanns** [comment]
> Perhaps I'm misunderstanding the use case for earlyReturn. Can we set earlyReturn/terminateSimulation=fmi3True if an issue occurred (ex. div. by zero) during integration prior to end of the step? Normally (without the earlyReturn mechanism) we'd return fmi3Error in this case.

The standard lists in "4.1.3. Early Return" the reasons for early return from doStep, errors are not mentioned, because the general idea of early return is that an additional communication step is introduced before the simulation continues.
For errors that cause the end of the simulation, the return code is the more general way to indicate to the importer the end of the simulation.

Again, if this is not clear enough: please propose where you would expect a sentence to clarify this issue.
