### ISSUE TITLE
Default value of variability attribute

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1846]
In the specification fmi-3.0, we read: "The default for variables of type <Float32> and <Float64> is continuous".
Wouldn't it better, if we clearly specify according to the table 18? In other works, we may say:
For variables with causality {Local, INPUT and OUTPUT}, if Type if FloatXX, the default variability is CONTINUOUS, otherwise it is DISCRETE.
If the causality is {structural Parameter, Parameter, or CalculatedParameter}, the default variability may be FIXED.

**Comment by chrbertsch** [comment]
@masoud-najafi : 

I do not understand your reference to table 1 https://fmi-standard.org/docs/main/#table-overview-features. Could you check again please?

If I understand right, you do not propose a change in the default value definitions, but want to write it down in  better way.  (what is unclear?) 
Currently, default value explanations are given after the the possible default values, e.g. `= discrete`.  So you propose to change the order of the definitions and group them based on the different causalities, right?

In order to decide on your proposal: Could you please suggest the concrete wording and place where you would put these sentences in a Pull Request?

**Comment by masoud-najafi** [comment]
Sorry, the table number is 18. The current default value for the variability is not clearly defined (or at least I cannot find for all causalities). I just propose to be more specific and define different default values, based on the data-type and the causality of a variable. For example, for parameters, the default value should clearly be "discrete". 
I'll look at the current spec and prepare a PR.

**Comment by chrbertsch** [comment]
@masoud-najafi : Could you please provide a PR, best until tomorrow's design meeting so that we could discuss your proposed changes? Thanks!

**Comment by masoud-najafi** [comment]
Hi Christian,
I noticed that the Spec3.0 has recently changed and now reflects exactly what I have asked in this ticket (https://fmi-standard.org/docs/main/#variability).  However,  the fmi-3.0 complete package zip-file is not up to date and needs to be updated.  So no PR is required.
Thanks!

**Comment by chrbertsch** [comment]
Hi Masoud, I think the change was introduced in https://github.com/modelica/fmi-standard/pull/1836; it will appear in the "complete package zip-file" one we have released FMI 3.0.1
