### ISSUE TITLE
Clarification of Argument "loggingOn" of fmiInstantiate needed

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#186]
**Reported by torstenblochwitz on 19 Mar 2014 15:38 UTC**
It is not clear for me, how argument "loggingOn" interacts with the fmiSetDebugLogging function and the fmiModelDescription.LogCategories of modelDescription.

----

Migrated-From: https://trac.fmi-standard.org/ticket/186

**Comment by modelica-trac-importer** [comment]
**Comment by torstenblochwitz on 27 Mar 2014 10:35 UTC**
Added non-normative text:
A FMU could set all logCategories according to this argument. Which logCategory the FMU sets is unspecified.]

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 6 Aug 2014 11:57 UTC**
We are experiencing problems with the logging behaviour of FMUs exported by different tools or by different versions of the same tool.

 - In one case the behavior changed with a new version of an exporting tool. An earlier version of the tool did only report warnings and errors with fmiInstantiate(..., loggingOn=true). A new version of the same tool reports all messages for the same fmiInstantiate call. The vast amount of Set/GetReal messages broke our importing application. Even if the logging function did do nothing, already the calls slowed down the whole application significantly.

 - In another case the behavior changes with a different tool: loggingOn=false means for this tool that no logs appear at all, not even in the case of critical errors.

The statement in section 2.1.5 "Which LogCategories the FMU sets is unspecified." is not satisfactory. Couldn't the standard define the expected behavior for loggingOn=fmi2True and loggingOn=fmi2False?

Alternatively, the function `fmi2SetDebugLogging` could be used. Its specification says:

"If loggingOn=fmi2True and nCategories > 0, then only debug messages according to
the categories argument shall be printed via the logger function."

This sounds good. But how to tell an FMU that it should do no logging at all?

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 6 Aug 2014 19:24 UTC**
Here is a solution proposal that clearly defines debug logging and that enables turning it off completely. The following paragraph in section 2.1.5:

_If loggingOn=fmi2True, debug logging is enabled. If loggingOn=fmi2False, debug logging is disabled. [The FMU enable/disables LogCategories which are useful for debugging according to this argument. Which LogCategories the FMU sets is unspecified.]_

is rephrased to:

_If loggingOn=fmi2False, then any logging is disabled and the logger function is not called by the FMU. If loggingOn=fmi2True, the FMU enables a vendor defined set of LogCategories. This set should typically contain categories for messages that explain execution errors, like fmi2Discard, fmi2Error and fmi2Fatal. The function fmi2SetDebugLogging gives more detailed control about required LogCategories (see below)._

Note: fmi2Discard belongs to the set of proposed default categories because this is stated in paragraph 2.1.3 of the specification.

**Comment by KarlWernersson** [comment]
Proposal, Accept and integrate the proposal from rfranke

**Comment by IZacharias** [comment]
We disagree to the proposal since it is more than a clarification. In the original specification, it is clearly stated that the “loggingOn” argument controls if *debug* logging is enabled or not. 

Changing the specification would break forward/backwards compatibility: Old 2.0 FMUs that call the logger function (e.g. to output error messages) although loggingOn is set to fmi2False would not be valid 2.0.1 FMUs.

**Comment by pmai** [comment]
I agree that this is not a clarification for 2.0.1; As it is the 2.0 standard only ever talks about debug logging, while implicitly leaving it unclear that there might or might not be other logging (i.e. the only function directly controlling logging is called fmi2SetDebugLogging, implying more or less that there is no other controllable logging, especially since logger shall only be called for categories given to fmi2SetDebugLogging).

So I think the only clarification we could maybe do is to state that if fmi2SetDebugLogging is called with loggingOn=fmi2False, the intention is for all logging to be disabled. Beyond that I think the situation is already to underdefined in FMI 2.0 to get to reasonably common behaviour.

This should be fixed in 3.0, by either clearly stating whether there is any logging besides debug logging, and if there is, how to enable normal vs. debug logging reliably and setting expectations on the amount and level of logging performed in either case.

**Comment by KarlWernersson** [comment]
You have convinced me, in addition if we can live without a recommendation addition on an issue, i think we should avoid it so we don't clutter the standard with those semi "fixes" if it is not really necessary. 
New proposal:
Wont fix, for 2.0.1
Reopen for 3.0

**Comment by KarlWernersson** [comment]
decision, move to 3.0

**Comment by chrbertsch** [comment]
fixed with #831
