### ISSUE TITLE
Inconsistent float type in XML vs API for IntervalDecimal & ShiftDecimal

### ISSUE THREAD

**Issue by PeterMeisrimelModelon** [modelica/fmi-standard#1896]
Hi, 

we have discovered an inconsistency of the float data-types for the ClockAttributes IntervalDecimal & ShiftDecimal:

As per XML schema and specification document, these are defined as float (=fmiFloat32).
However, the API functions

fmi3SetIntervalDecimalTYPE
fmi3GetIntervalDecimalTYPE
fmi3SetShiftDecimalTYPE
fmi3GetShiftDecimalTYPE

are defined for fmi3Float64 outputs.

Is this by design to keep the API uniform or is this an oversight?

**Comment by RThomas-29** [comment]
Hi,
I have similar questions regarding state variables and event indicators. 

* State variable:
In the XML schema (files fmi3AttributeGroups.xsd and fmi3Variable.xsd), attribute "fmi3RealVariableAttributes" is used in <xs:complexType name="fmi3Float32"> and <xs:complexType name="fmi3Float64">. Therefore, a Float32 can be a state variable or a derivative. 
However, the API functions:
  * fmi3SetContinuousStates, 
  * fmi3GetContinuousStates,
  * fmi3GetContinuousStateDerivatives, 
  * etc. 
have Float64 as arguments but not Float32. Is this by design to keep the API uniform or is this an oversight?

* Event indicators:
In "Table 23. ModelStructure elements" event indicators can be Float32 and Float64. However, there is no fmi3GetEventIndicators function with Float32. Is this by design to keep the API uniform or is this an oversight?

**Comment by pmai** [comment]
The Float32/Float64 discrepancies with regard to the getter/setter API is by design, as any Float32 can be represented exactly as a Float64 (and back-converted without any precision loss), so the API (and API specification) could be kept lean and clearer.

**Comment by RThomas-29** [comment]
Thank you for your reply,
It will be helpful to add this clarification in the standard.

**Comment by chrbertsch** [comment]
FMI Design Meeting: 
Klaus: For the clocks this is an inconstistency. Can we change this to Float64 in the schema? 
Klaus: For the states, this is fine.
Masoud: can we not say the same thing for the clocks?
Klaus: no. Currently one could not express in XML a value that cannot be expressed in 32bits.
Christian: Can we change the schema in a bugfix release?
Klaus: Yes, what does this mean for compatibility. Practically it is not a problem, because there are not so many implementation out.  Currently, the start value has be expressable as a float32. Practically there might be no problem at all.

**Comment by chrbertsch** [comment]
FMI-Design-Webmeeting: 

Klaus, Pierre: in the API we already use double, in the XML we use float
Pierre: is this really a problem?
Pierre: we can fix this in a way that does not break anything. The used numbers in the XML are not restricted to the numbers that can be represented. So we could change the schema without creating XML problems.

Poll: Should we fix this in FMI 3.0.2? (change the schema to double precision? We have to provide a clear info in the release notes)
Yes: Torsten S., Christian, Torsten B., Pierre, Daniel, Klaus, Otto, Timo, Daniel J, Patrick, Karl, Daeoh
No: - 
Abstain: Jan, Marcus, Kahramon.

Pierre: I will create a PR to change the XSD file. We might need also some non-normative text in the standard.
Klaus: I will create a text for the changelog
