### ISSUE TITLE
Clarify lifetime of argument functions in fmi2Instantiate()

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#1923]

**Comment by chrbertsch** [comment]
TorstenS: If you do not take a copy of the function pointers, you can run into trouble.
Andreas: I will check

**Comment by HansOlsson** [comment]
The current text makes little sense. 

C does not allow a _function_ to change - whereas function pointers are often changed, so a sensible interpretation is that when it says "It is not allowed to change these functions between fmi2Instantiate(..) and fmi2Terminate(..) calls." the intent was "It is not allowed to change these functions pointers between fmi2Instantiate(..) and fmi2Terminate(..) calls." which means that the pointed to struct cannot be changed by the caller - in that case it doesn't matter if the FMI makes a copy of the function pointers or not; as the values cannot change.

If we only wanted that the struct should be valid during the call we could have sent in a struct instead of a pointer to struct (the overhead of sending a struct by value during instantiation is minimal).

**Comment by chrbertsch** [comment]
Fixed with https://github.com/modelica/fmi-standard/pull/1931
