### ISSUE TITLE
Figure 10 need an update

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#318]
**Reported by anonymous on 2 Feb 2015 15:40 UTC**
Figure 10 is a bit outdated it contains variables, which are not used in the description( e.g. m).

----

Migrated-From: https://trac.fmi-standard.org/ticket/318

**Comment by chrbertsch** [comment]
URGENT (for 2.0.1 release) Please check if this picture is fine 
2.0.1:
![image](https://user-images.githubusercontent.com/16363372/65392963-4d5a7300-dd7b-11e9-90e0-1f22fa0b4636.png)

in comparison 2.0 was
![image](https://user-images.githubusercontent.com/16363372/65392812-05d2e780-dd79-11e9-8e7d-76b9d8252c4c.png)

Changes
* renamed **m** to *x_d**
* remand **x** to **x_c**
* Remove **z** event indicators  (not mentioned in text below, not important in FMI 2.0 CS); removed as text and at the error to the solver
* change order to be the same as in the table below
* Changed "solver" to "master algorithm"

Please comment if this is ok or something has to be changed. Thanks!

**Comment by masoud-najafi** [comment]
Just a short comment: May be I am missing the context or I have not get it correctly, in FMI for Cosimulation, the master algorithm does not intervene in the slave internal algorithm. Therefore, I would keep “Solver” or  just replace it by “slave algorithm”. Also, I would keep “z”, since it is interacting with the slave solver and it is not visible from outside.
Thanks
Masoud


De : Christian Bertsch <notifications@github.com>
Envoyé : dimanche 22 septembre 2019 20:56
À : modelica/fmi-standard <fmi-standard@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [modelica/fmi-standard] Figure 10 need an update (#318)


URGENT (for 2.0.1 release) Please check if this picture is fine
2.0.1:
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F16363372%2F65392963-4d5a7300-dd7b-11e9-90e0-1f22fa0b4636.png&data=02%7C01%7Cmasoud%40altair.com%7Ca1a8a21b0a77478dca8e08d73f8e7b37%7C2bae5b570eb848fbba47990259da89d2%7C0%7C1%7C637047753502035614&sdata=r73lhy%2BZFtx9qA%2FtzDVp%2BxjCfZ2THYSuiUI9kFzWf2Y%3D&reserved=0>

in comparison 2.0 was
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F16363372%2F65392812-05d2e780-dd79-11e9-8e7d-76b9d8252c4c.png&data=02%7C01%7Cmasoud%40altair.com%7Ca1a8a21b0a77478dca8e08d73f8e7b37%7C2bae5b570eb848fbba47990259da89d2%7C0%7C1%7C637047753502045607&sdata=B86793Ou6qzTiUDeTRUMtulfzcI7JmZ%2BKQVAhe%2FU9v4%3D&reserved=0>

Changes

  *   renamed m to x_d*
  *   remand x to x_c
  *   Remove z event indicators (not mentioned in text below, not important in FMI 2.0 CS); removed as text and at the error to the solver
  *   change order to be the same as in the table below
  *   Changed "solver" to "master algorithm"

Please comment if this is ok or something has to be changed. Thanks!

**Comment by chrbertsch** [comment]
@masoud-najafi  thanks for reviewing.
Ah, for sure it is the internal solver and not the master algorithm. 
What about naming z as "(internal) event indicators"?

What about this?
![image](https://user-images.githubusercontent.com/16363372/65393732-f063ba80-dd84-11e9-9cb2-c637a108c659.png)

**Comment by masoud-najafi** [comment]
Yes, I think Z is the slave internal event indicators. But since in FMI-for -Cosimulation, internal model and the internal slave solver is completely transparent to the master, I am not sure if it is a good thing to mention Xc, Xd, and Z.

De : Christian Bertsch <notifications@github.com>
Envoyé : dimanche 22 septembre 2019 22:05
À : modelica/fmi-standard <fmi-standard@noreply.github.com>
Cc : Masoud Najafi <masoud@altair.com>; Mention <mention@noreply.github.com>
Objet : Re: [modelica/fmi-standard] Figure 10 need an update (#318)


@masoud-najafi<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmasoud-najafi&data=02%7C01%7Cmasoud%40altair.com%7C621bf4f388fc45c8eeda08d73f9817c3%7C2bae5b570eb848fbba47990259da89d2%7C0%7C1%7C637047794780896526&sdata=IQwPfvaiY5YJA1LUoYvEWQqcmnul4dTZQmfiYBtIoko%3D&reserved=0> thanks for reviewing.
Ah, for sure it is the internal solver and not the master algorithm.
What about naming z as "(internal) event indicators"?

What about this?
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F16363372%2F65393732-f063ba80-dd84-11e9-9cb2-c637a108c659.png&data=02%7C01%7Cmasoud%40altair.com%7C621bf4f388fc45c8eeda08d73f9817c3%7C2bae5b570eb848fbba47990259da89d2%7C0%7C1%7C637047794780906533&sdata=I64Mb0LJ3PmuUDzeL6y48CbaCrQaPnsdO%2BaqtsP45IY%3D&reserved=0>

**Comment by chrbertsch** [comment]
@masoud-najafi 
> I am not sure if it is a good thing to mention Xc, Xd, and Z.

This was already there in FMI 2.0, but with wrong variable names according to this ticket.
I suggest not to change much for 2.0.1
