### ISSUE TITLE
How to interpret empty unit definitions?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#337]
**Reported by aviel on 22 May 2015 08:20 UTC**
Since an empty attribute seems to be valid XML, it is not clear in the 2.0 specification document how to deal with empty _unit_ attribute definitions. Different interpretations are possible:
1. a `unit=""` attribute in `<Real>` element of a `<SimpleType>` or a `<ScalarVariable>` is the same as having no _unit_ attribute declared at all?
2. a `unit=""` attribute in `<Real>` element of a `<SimpleType>` or a `<ScalarVariable>` means that there is exactly one `<Unit>` element in `<UnitDefinitions>` with an empty _name_ attribute?
Now in the case of a `unit=""` attribute in a <Real> element of a `<ScalarVariable>` element that also has a _declaredType_ attribute, does it means that it overwrites the unit of the _declaredType_, by either declaring no unit, or refering to a unit (with empty _name_ attribute) declared in exactly one `<Unit>` element in `<UnitDefinitions>`?

----

Migrated-From: https://trac.fmi-standard.org/ticket/337

**Comment by KarlWernersson** [comment]
I would say that option two is the only proper xml conclusion, but we don’t want that so I would recommend we forbid it,
if that is seen as to restrictive on forwards compatibility, explain why you should not have units as empty strings. Most likely such an FMU would not define it in unit definitions and would therefore bee illegal.

**Comment by pmai** [comment]
Yes, I think this is the only valid interpretation: Since the unit attribute has no default value in the XML schema, a missing unit attribute is different from a unit attribute that is present but has the empty string as its value; hence implementations must treat such a unit attribute the same as if any other value had been provided, i.e. by looking up a unit definition with name="". If such a unit is not present, the declaration is erroneous.

**Comment by KarlWernersson** [comment]
desicion
clarify, unit="" states that the variable has a unit with the name "" and it has to be defined in the unit definitions, the correct way is not declaring unit.
