### ISSUE TITLE
Setting input start values before fmi2EnterInitializationMode

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#369]
**Reported by karl&#x2e;wernersson on 16 Feb 2016 13:47 UTC**
Reference tickets:
https://trac.fmi-standard.org/ticket/258
https://trac.fmi-standard.org/ticket/271
Web meeting Minutes  2014-07-11

Hi
In ticket #271 input lost the initial attribute approx,
the reason for this was the ticket #258 and the fowling discussion about it during the web meeting 2014-07-11.

One effect of this change was that start values for input is no longer allowed to be changed from default value before call to fmi2EnterIntializtaionMode as of specification page 48

**fmi2SetXXX can be called on any variable with variability ≠ "constant" before initialization
(before calling fmi2EnterInitializationMode) if
• initial = "exact" or "approx" [in order to set the corresponding start value].**

This can also bee seen in the SEA and INI definition of ME and CS state charts

So before the removal of "approx" for input inputs could be set by the implicit definition stated above, but after the removal they are no longer allowed to be set.

By reading the tickets, the minutes and my memory I cant recall that this aspect was ever discussed and it is an unintentional restriction that should be corrected and clarified in 2.0.1

Up until a few days ago i have never encounter an FMU that had a problem with this so it seems that most vendors have overseen this restriction (or doesn't care about it).

The reason for supporting changing start values of input is to make it more user friendly and robustness.
if a user generates an FMU that has singularities, or other problems with certain values on inputs, and they have forgotten to set proper start values this can easily be corrected at import, instead of having to re generate the FMU.

Karl Wernersson

----

Migrated-From: https://trac.fmi-standard.org/ticket/369

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 15:28 UTC**
Since the current 2.0 specification is not ambiguous about that, this is more a requirement for a future version (for example 2.1) than a clarification needed for a maintenance release.

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 15 Jun 2017 11:55 UTC**
I understand your point but i see this as a bug/misprint in the standard rather then a new feature for 2.1

The fact that basically all different fmu's, including all with inputs uploaded at the cross check, I have encountered so far are implemented so that input can be set before call to fmi2EnterInitialization mode speaks towards that this is a bug/misprint that should be fixed for 2.0.1 rather than a new feature pushed for 2.1

Having start values for inputs that cannot be changes seems quite absurd to me.

**Comment by modelica-trac-importer** [comment]
**Modified by karl&#x2e;wernersson on 15 Jun 2017 11:56 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by najafi on 20 Jul 2017 14:22 UTC**
Just to say that we made many work arounds to avoid setting inputs before a call to fmi2EnterInitialization. Now we nolonger need this change in FMI-2.0. Changing calls in the state-machine for 2.0.1, although will simplify the import, but requires many changes at least for us.  I know that other vendors have had the same problem.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 14:06 UTC**
In 2.0.1 there can be only a clarification; in 3.0 it should be changed.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 18 Jun 2018 10:12 UTC**
Clarification in 2.0.1. is handled in #440.

**Comment by modelica-trac-importer** [comment]
**Modified by cbertsch on 18 Jun 2018 10:15 UTC**

**Comment by andreas-junghanns** [comment]
What about 3.0 - do we still need to clarify this? What about the new role of fmi3EnterInitializationMode with the new arguments (stepping in for the removed SetupExperiment)?

**Comment by chrbertsch** [comment]
@KarlWernersson , @antvl, @masoud-najafi : could you please check if this is still a valid issue?

**Comment by masoud-najafi** [comment]
Consider an SSP diagram where there are several interconnected FMUs. First, note that getting outputs of an  FMU is not allowed in the Instantiated mode.
 Even if we allow “getting outputs”, FMU outputs may depend on parameters that can change in the Instantiated mode (those variables with variability !=constant and 
initial = exact or approx).  Since, the outputs of FMUs are not present or not reliable, we may better keep it FMI-3.0 as it is in FMI-2.0, i.e., should not allow setting inputs in instantiated mode.
Thanks
Masoud

**Comment by andreas-junghanns** [comment]
@KarlWernersson : you raised this, please comment.

**Comment by KarlWernersson** [comment]
All input must have startvalues, start values are set before enterInitalizationMode if one want to change them from their predefined values in the xml. Pulling input values from other outputvalues is done during initialization mode, this is only to make it posible for users to change their start values of input. Before the call to enter initialization mode like all other startvalues. E.g. if the prededfined start value (nomally 0) causes problematic calculation. A most simple example y=1/u;

**Comment by andreas-junghanns** [comment]
Here my brief summary of Karl´s proposal: This requested change would allow setting the start values of inputs to replace the default as communicated in the modelDescription.

Masoud: Would you agree that changing start values of inputs is a useful functionality?

**Comment by ghorwin** [comment]
Sounds like a convenience feature to me. A decent Co-Simulation master implementation supports specifying input values for slaves, either as constants or linearly interpolated spline data. MasterSim, for example, allows specifying csv-data as input to tools. In case of constant data, such continuous states may be set only once by the master, which is usually done in the initialization mode (as Karl pointed out). So, getting alternative input values to a slave looks like a master-tool issue to me.

From FMU slave implementaters point of view, such a feature would mean potentially large changes in the initialization code. The fmi2EnterInitializationMode() call is frequently used to trigger the actual initialization of the FMU kernel, including initialization of the integrators memory structures. For quite a few tools, the memcpy-call inside fmi2SetContinuousStates() copies directly into integrator memory. If we were to allow fmi2SetContinuousStates-calls _before_ actual initialization, the slaves must implement an additional caching layer, which is IMHO a large price to pay for a convenience feature.

**Comment by masoud-najafi** [comment]
Andreas: I am not against this proposal, but maybe I am missing something. Since it is not allowed to do GetXXX before entering initialization, FMU does not do a computation and changing the default input value or parameters makes no difference.  Actually, changing the default input value can be done before or after entering initialization.
But the important point to consider is handling the 1/u issue pointed by Karl. We need to provide a way to "ignore" such errors raised in Initialization mode in FMU and "prevent" the FMU from entering permanently into error mode.

**Comment by andreas-junghanns** [comment]
First: The FMI Standard is not responsible for making it impossible to build broken FMUs. If you build a 1/u and give u a start value of 0, well, what should the standard do?

Second and more interestingly: As far as I understand, the input values (well, their start values) can be used for initialization. The proposal here is to define a way to change those from the defaults (represented in the modelDescription, but NOT changeable there).

@KarlWernersson should clarify this.

**Comment by KarlWernersson** [comment]
So

Before enterInitialziationMode, one can call Set<Type> on any variable with a start value (except constant and inputs)
**This includes states _if they have start value_**, but they have to be set with setFloat64 since some might be calucated and therefore SetContinousStates should not be used.

once you have enteredInitializationMode one can no longer set those variables with initial aprox, but only those with initial exact.

My understanding of this is that you set your general start values before EnterIntialization mode,
Once you are in initialization mode you solve whatever external initial constraints imposed on the fmu due to I/O connection or other reasons (e.g steady state initialization).
So in my view i would like to set most of my start values before i Enter initialization mode and then only worry about those that i need to involve to solve the initial equations imposed by my constraints.

I can agree that changing the start value of an input is a convenience, but still it is a nice convenience.
The start value of an Input is stated to be used if the fmu is unconnected. However there is no way of changing this as a start vale, only by setting it during initialization mode.
I would like to be able to treat it as all the other start values, **mainly for disabled inputs**.
It is of course fully possible to circumvent this by setting it at a later stage, but i cannot see why start values of inputs cannot be handled as a normal start value? 
Once you connect your input the start value will of course be irrelevant.

I cant see the problem however it is not super important to me and i can circumvent it. so if there is massive opposition to this I will back down

**Comment by andreas-junghanns** [comment]
So can we close this issue then? @KarlWernersson? @masoud-najafi?

**Comment by jph-tavella** [comment]
I would like to say that I support Karl's idea (being able to set input start values before fmi2EnterInitializationMode).
Indeed at EDF we are regularly confronted with the need to modify our models before FMU export, simply because of bad start value of some inputs, when the Master can do it easily.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : is this only about relaxing the constraints on which variables one can call fmi3Set{VariableType} on? Can you create a PR to show what needs to be changed?

@all: If we relax the currently present constraints to allow setting of inputs before fmi3EnterInitializationMode() do you see issues with that? (I don´t.)

**Comment by andreas-junghanns** [comment]
Design Meeting:
Karl: This is just making sure we can avoid one more iteration during initialization with the start value.
Klaus: This can also prevent bad start values causing issues during initialization (Div0 if start==0).
Pierre: In the best case, and only case, we reduce the number of iterations during the initializations.
Klaus: During 2.1 discussion we wanted this but did not allow because of backward compatibility reasons.
Pierre: Parts of the text already say that this is possible - let´s just cleanup!

All agree with Karl.

**Comment by clagms** [comment]
@KarlWernersson , when solving this, please the following text:
> Set variables latexmath:[\mathbf{v}_{\mathit{initial=exact}}] and latexmath:[\mathbf{v}_{\mathit{initial=approx}}]  that have a <<start>> value (<<initial>> = <<exact>> or <<approx>>)

**Comment by chrbertsch** [comment]
@KarlWernersson : Could you please  create a PR for this?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

TorstenB: We just allow setting inputs before fmi3EnterInitialization. No Problem with that.
Andreas: We need a PR.

@KarlWernersson : Could you please create a PR?

**Comment by KarlWernersson** [comment]
I will fix a PR next week

**Comment by jbernalr** [comment]
@KarlWernersson for your PR, I think one would need to consider and improve as well what is written in the definition of the atribute 'start'. As the here recommended SSP Standard is not really working in practice, I would tend to get more flexibility here. People are comming up with their own hacks on top of the master in order to re-parametrize FMUs which are unfeasible to re-export.

Currently the following is stated there: 

> Initial or guess value of variable. This value is also stored in the C functions. [Therefore, calling fmi3Set{VariableType} to set start values is only necessary, if a different value as stored in the XML file is desired. It is not allowed to change the start values in the modelDescription.xml file of an FMU, as this would break the consistency with the hard-coded start values in the C-Code. This could lead to unpredictable behavior of the FMU in different importing tools, as it is not mandatory to call fmi3Set{VariableType} to set start values during initialization. Instead it is recommended to use the SSP Standard (https://ssp-standard.org/) to handle modified parameters of FMUs or different parameter sets.]

**Comment by KarlWernersson** [comment]
#1223

**Comment by KarlWernersson** [comment]
@jbernalr , I dont exactly understand what it is that you want, to remove the reference to SSP? I don't see a problem with that.
To allow users to start changing xml? This is a very radical change as the xml no longer then represents the model. It would at minimum require that we remove the requirement that all start values are set by default.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 
Jorge: Users are changing the xml to set parameters. If you modify the allowed calls anyway, one could do larger change
Christian: This a different topic
Karl: And there is SSP to address this
Pierre: in the FMI standard we cannot do anything without modifying the FMU (XML)
Christian: off topic: one could put the Parameter file of SSP in the extra directory
Klaus, Karl: the importer should deal with this

@Karl: I will create a PR until next week

**Comment by andreas-junghanns** [comment]
@KarlWernersson : Can you please have a look and provide a PR now?
