### ISSUE TITLE
Mapping of the event indicators to the switching condition

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#382]
**Reported by christian&#46;schulze on 4 Jul 2016 10:09 UTC**
Currently FMI does not provide enough information to enable the mapping of the switching condition to the zero crossing functions. In some cases this information is required to provide useful error messages.

If the simulation of a ME FMU fails / is extremely slow because of chattering (e.g. flow reversal in fluid systems), then I can only narrow down the problem to a number of zero crossing function indices. E.g. an engineer is not able to map back, where the flow reversal actually happened.

Simply enhancing the logging features of the FMU is not enough. The importing tool has to handle the events and has to decide if the simulation should be stopped or if specific warning messages should be shown.
Another example are non-converging event loops (cross-FMU). An importing tool could provide information, which event indicator / switching condition caused the problem. 

I suggest providing a list of strings in the FMU XML which contains the switching conditions. The number of elements in the list should be equal to the number of event indicators. That information is optional and could contain concealed expressions.

----

Migrated-From: https://trac.fmi-standard.org/ticket/382

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#x2e;junghanns on 6 Feb 2017 10:58 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 17:29 UTC**
Changed the milestone to 2.1, since the proposal of adding new informations in the XML seems out of the scope of a maintenance release.

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 1 Jun 2018 15:07 UTC**
This needs more explanation and a concrete proposal.

**Comment by CSchulzeTLK** [comment]
If this example is exported as ModelExchange FMU, then importing tool cannot give a good explanation what the actual problem is.
```
model ExampleChattering
  Real x;
initial equation
  x=0;
equation
  if (x < 0.5) then
    der(x)= 1;
  else
    der(x)=-1;
  end if;
end ExampleChattering;
```

It would be nice to have an additional information about the switching condition. The importing tool should provide an logging/error message like "x < 0.5 became true/false", or "The switching condition 'x < 0.5' caused chattering".

To enable this the mapping of the switching condition to the event indicator index should be provided. Something like:

```
<fmiModelDescription> 
  ...
  <ModelStructure>
    <EventIndicators>
      <EventIndicator index="0" condition="#25# <= 0.5">
      <EventIndicator index="1" condition="#25# > 0.5">
    <EventIndicators>
  </ModelStructure>
</fmiModelDescription>
```

**Comment by CSchulzeTLK** [comment]
FMI-Design found a workaround:
- Detect consecutive events in the importing tool (e.g. 500 consecutive events in a very short time period)
- Activate logging messages for events
- Continue the event loop to get the informaton which event indicators are involved (handle the 501st event)

The proposal to change the XML scheme that was suggested in the comments above, would have to be merged with the array proposal. If arrays are present, the number of event indicators might change. Also dynamically changing meaning of the event indicators could be a problem. A C-API-function could be added, to dynamically provide the switching condition string to the importer (e.g. fmi3GetEventIndicatorDescription). However, since the workaround mentioned above is sufficient to provide the required information, this issue doesn't require a change of the existing standard.

**Comment by KarlWernersson** [comment]
Closing since good enough workaround exist
