### ISSUE TITLE
Inconsistency regarding fmi2GetEventIndicators and Initialization mode

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#395]
**Reported by aviel on 5 Dec 2016 17:33 UTC**
According to the table of page 85, section 3.2.3 of Model Exchange specification, the _fmi2GetEventIndicators_ function can be called during the Initialization Mode. However the state machine chart of page 83 contradicts this statement. This should be clarified, since it is not clear if state events are allowed to happen at t=t<sub>start</sub>

----

Migrated-From: https://trac.fmi-standard.org/ticket/395

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 5 Dec 2016 17:35 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 13 Feb 2017 15:54 UTC**
This issue is also discussed in #301 comment 4.

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:44 UTC**

**Comment by KarlWernersson** [comment]
Proposal:
update state diagram to allow fmi2GetEventIndicators durin initializationMode.

**Comment by KarlWernersson** [comment]
Poll
Allow EventIndicators at InitializatoinMode
Kaska, Karl, Pierre
Forbid EventIndicators at InitializationMode
Antoine, Masoud, Otto, Forbid, 

Abstain, Andreas, Irina, Christian (B & W), Markus, Thomas, Thorsten

**Comment by KarlWernersson** [comment]
Decision:
Follow table definition.
Write non normative text about that values might not be correct in initialization mode and the state chart was wrong in fmi 2.0 .

**Comment by chrbertsch** [comment]
Included in the merged PR #579

**Comment by chrbertsch** [comment]
(Urgent for release of FMI 2.0.1) As I have touched the state graph anyway for #301, I have updated also this the part of this issue  and the non-normative-text.

Is this fine?
![image](https://user-images.githubusercontent.com/16363372/65393414-92cd6f00-dd80-11e9-965d-2d1cc4e10d0c.png)

with the uptated non-normative text
_[Bugfixes in FMI 2.0.1: Note that there was an inconsistency in FMI 2.0 in the state graph and the table regarding if fmi2GetEventIndicators is allowed to be called in initializationMode. The table (see further down) is correct and fmi2GetEventIndicators can be called in initializationMode.
Additionally the state grapyh has been updated so that now fmi2GetDerivatives may by called in initializationMode.]._


Please comment, if ok, or if something has to be changed. Thanks!
