### ISSUE TITLE
Clarify the definition of the number of continuous-time state variables

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#396]
**Reported by aviel on 21 Dec 2016 13:57 UTC**
In the Model Exchange specification, the number of continuous-time state variables is an argument of the _fmi2GetContinuousStates_, _fmi2SetContinuousStates_, _fmi2GetDerivatives_, and _fmi2GetNominalsOfContinuousStates_ functions. Some FMUs define real scalar variables that refer to the same real continuous variable through their _derivative_ attribute, for example if they are alias. It is not clear in the specification if the number of continuous-time state variables is always taken as the number of state derivatives, or if it takes into account the case of the multiple references, thus decreasing the actual number accordingly. This number is defined nowhere in the specification document.

----

Migrated-From: https://trac.fmi-standard.org/ticket/396

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:45 UTC**

**Comment by KarlWernersson** [comment]
If I understand you correctly, there are FMU’s with ndx nbr of derivatives specified in the modelStructure/derivatives, however some of those referes to the same state so that you nx  nbr of states and ndx != nx.
For me this is such an obvious error that I don’t even think that its necessary to write anything about it in the standard, it’s like defining 1+1 =2
Or have I misunderstood you?

**Comment by antvl** [comment]
Yes, but this number is defined nowhere in the specification document. So, we have to add a statement that refers to the number of Unknown elements in the Derivatives section of ModelStructure.

**Comment by KarlWernersson** [comment]
I still think its superfluous, but how would you want it?
_The number of continuous time states must be the same as the number of continuous time state derivatives_

I did some digging in the document and this is what is currently stated

P.30

ModelStructure Defines the structure of the model. Especially, the ordered lists of
outputs, continuous-time states and initial unknowns (the unknowns
during Initialization Mode) are defined here. Furthermore, the
dependency of the unkowns from the knowns can be optionally
defined. [This information can be, for example used to compute
efficiently a sparse Jacobian for simulation or to utilize the
input/output dependency in order to detect that in some cases there
are actually no algebraic loops when connecting FMUs together].

p. 54
Derivative If present, this variable is the derivative of variable with ScalarVariable index
"derivative". [For example, if there are 10 ScalarVariables and derivative = 3 for
ScalarVariable 8, then ScalarVariable 8 is the derivative of ScalarVariable 3 with
respect to the independent variable (usually time). This information might be
especially used if an input or an output is the derivative of another input or output,
or to define the states.]
The state derivatives of an FMU are listed under element
<ModelStructure><Derivatives>. All ScalarVariables listed in this element
must have attribute derivative (in order that the continuous-time states are
uniquely defined).

P 55
FMU must expose all derivatives of its continuous-time states in element <Derivatives>. A Co-
Simulation FMU need not to expose these state derivatives. [If a Co-Simulation FMU exposes its state
derivatives, they are usually not utilized for the co-simulation, but, e.g., to linearize the FMU at a
communication point.]

p 58
The corresponding continuous-time states
are defined by attribute derivative of the corresponding ScalarVariable state
derivative element. [Note, higher order derivatives must be mapped to first order
derivatives but the mapping definition can be preserved due to attribute
derivative. Example: 𝑑𝑠
𝑑𝑡 = 𝑣, 𝑑𝑣
𝑑𝑡 = 𝑓(. . ), then 􁉄𝑣, 𝑑𝑣
𝑑𝑡􁉅is the vector of state
derivatives and attribute derivative of 𝑣 references 𝑠, and attribute
derivative of 𝑑𝑣
𝑑𝑡 references 𝑣.]

P 60
(3) all continuous-time states and all state derivatives (defined with element
<Derivatives> from <ModelStructure>)

p82

The ordering of the elements of the derivatives vector is identical to the ordering of the state vector

**Comment by antvl** [comment]
On p. 58,  I would propose something like:

> The number of Unknown elements in the Derivatives element uniquely define the number of continuous time state  variables, as required by the corresponding Model Exchange functions (integer argument "nx" of fmi2GetContinuousStates, fmi2SetcontinuousStates, fmi2GetDerivatives,  fmi2GetNominalsOfContinuousStates see hereafter) that require it.

**Comment by KarlWernersson** [comment]
decision, accept proposal from Antoine

**Comment by chrbertsch** [comment]
Included in the merged PR #579
