### ISSUE TITLE
Non-determinism regarding the pure discrete-time FMU variant

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#409]
**Reported by aviel on 1 Feb 2017 09:45 UTC**
The model exchange 2.0 specification defines a variant called _pure discrete-time FMU_, when an FMU does not exhibit continuous-time variables. It is defined in the Mathematical Description (section 3.1), remarks 2 (p.76) and 4 (p. 78), table 1 (p.75, _Set independent variable time ... if no continuous-time equations_), and it is consistent with the State Machine of Calling Sequence (section 3.2.3, p.83) that describes a transition triggered by a call to the `fmi2SetTime` function (labeled _discrete FMU_).

However, the model exchange specification does not clearly states if it is mandatory for an importing environment to follow the above mathematical semantics if such a pure discrete-time FMU is encountered. Some pure discrete-time FMUs expect from the environment that the above semantics (corresponding to the function call sequence `fmi2EnterEventMode` -> `fmi2NewDiscreteStates` -> `fmi2SetTime` -> `fmi2EnterEventMode` -> ...) is applied, whereas some other FMUs rely on the full continous-time semantics (corresponding to `fmi2EnterEventMode` -> `fmi2NewDiscreteStates` -> `fmi2EnterContinuousTimeMode` -> `fmi2SetTime` -> ...) to be executed and to provide the expected results.

This yields non-deterministic behaviors: is is not possible for an importing environment to know in advance which semantics the FMU complies to.
The specification must clearly get rid of this non-determinism, either by defining a normative semantics, or by introducing new informations in the XML model description to identify which semantics a pure discrete-time FMU adheres to.

----

Migrated-From: https://trac.fmi-standard.org/ticket/409

**Comment by modelica-trac-importer** [comment]
**Comment by najafi on 1 Feb 2017 11:25 UTC**
This may be irrelevent, but what a "pure discrete-time" FMU really means? I could not find a clear defintion in the specfication to avoid the non-determinism explained in this ticket. Can an FMU with these characteristics
-- no continuous-time state
-- no zero-crossing
-- completedIntegratorStepNotNeeded is TRUE
be considered as a "pure discrete-time" FMU?

**Comment by modelica-trac-importer** [comment]
**Comment by aviel on 1 Feb 2017 12:55 UTC**
I think you are right, this is what can be deduced from the specification, mostly from the mathematical description. Regarding the zero crossings, there is another ticket #405 that tries to clarify this. Regarding the _completedIntegratorStepNotNeeded_ flag, it is not clear, since there are in the cross check repository some FMUs that do not have continuous-time variables but have this flag left to _"false"_ (the default value). Perhaps this deserves another ticket?

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 17:44 UTC**

**Comment by KarlWernersson** [comment]
I agree that pure Time discrete stat is a bit fuzzy
However the 2.0.1 standard should avoid any radical changes and to relay clear this up i think we should push for 3.0 (either remove or properly define)

My proposal to solve this issue is an amendment to Remark 4
original in _italic_ addition in **bold**

_Remark 4 – Pure Discrete-Time FMUs:
If an FMU has only discrete-time equations (and no variables with variability = “continuous”), then the
environment need not to call fmi2EnterContinuousTimeMode but can directly call fmi2SetTime to set
the value of the next event instant, before fmi2EnterEventMode is called._
**This is an optional optimization for the master, the FMU must support all functions that are required for a continuous FMU and should run in a master that treats it as such**

This also goes well with
https://github.com/modelica/fmi-standard/issues/411

**Comment by chrbertsch** [comment]
Included in the merged PR #579
