### ISSUE TITLE
Are all of the API functions mandatory?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#411]
**Reported by aviel on 15 Feb 2017 08:27 UTC**
The model description for Model Exchange and Co-simulation defines three flags _canGetAndSetFMUstate_, _canSerializeFMUstate_ and _providesDirectionalDerivative_. According to sections 2.1.8 (p. 25) and 2.1.9 (p. 26), it is stated that the functions:
* `fmi2GetFMUstate`
* `fmi2SetFMUstate`
* `fmi2FreeFMUstate`
* `fmi2SerializedFMUstateSize`
* `fmi2SerializeFMUstate`
* `fmi2DeSerializeFMUstate`
* `fmi2GetDirectionalDerivative`
are only supported by the FMU, if the (above) optional capability flags (...) are explicitly set to _true_.
Does it mean that these functions may not or shall not exist in the binary part of the FMU if these flags are set to _false_?
Are these functions mandatory, and always present in the FMU? Indeed, if the flags are set to _false_, these functions could return _fmi2Error_ if incorrectly called.
It is not clear in the specification, and at this time some FMU from the Cross Check Repository provide some or all of the above functions when the flags are false, whereas some other FMU do not define the functions.

----

Migrated-From: https://trac.fmi-standard.org/ticket/411

**Comment by modelica-trac-importer** [comment]
**Comment by ottot on 10 Oct 2017 14:47 UTC**
If we want to support use cases where an FMU is linked directly to a simulator (in contrast to loading it at runtime) it makes a lot of sense to require them to always be present. Otherwise we enforce that these kind of simulators has to be generated (unless you want to supply a static one for every combination of available optional features).

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 10 Oct 2017 15:22 UTC**
As a 2.0 FMU shall be a valid 2.1 FMU due to our requriments on backwards compatiblity, will we not have the case that some functions will not be defined in such an FMU w.r.t to the 2.1 Standard anyway(due to new optional features that a 2.0 FMU has no chance to know)?

**Comment by modelica-trac-importer** [comment]
**Modified by aviel on 27 Nov 2017 16:45 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 26 Apr 2018 14:07 UTC**
Hi

Section 2.3 page 65 states

_The
implementation must either implement all the functions of FMI for Model Exchange or all the functions of
FMI for Co-Simulation or both._

I would say its quite clear

**Comment by hyumo** [comment]
Comments from an import tool developer:

FMU capabilities should be enforced, and forbid “optional” clauses in the standard. This is currently the largest hurdle I am encountering as an fmu import tool developer.

FMI 2.0 adds a lot of great features like directional derivatives, get/set fmu state and fmu state serialization, however, they are all optional. Not only most export/authoring tool vendors are reluctant to implement those features (because they are optional). As an import tool developer, it is almost impossible for us to support 1) FMUs by all tool vendors 2) utilize those advanced features in our algorithms at the same time. We always have to may a trade off and either sacrifice feature or FMU generality from different tools. 

For example, master algorithms utilizing rollback. We have to tell our users that “Unless you export the FMU from Dymola, or your FMU won’t work in this algorithm”. Knowing this, our users get quite frustrated because they were **advertised** (from presentations/papers/talks) that that they could avoid vendor lock-in with FMU, but it is actually not the case. 

Our management team always want to make the safest decision, which is not to implement the algorithm that utilize those features at all. This is a huge impact to a good usage of FMI standard, and it forms a very negative loop “Authoring tools are not exporting FMUs with advanced capabilities -> Import tools cannot design algorithms around those capabilities->Authoring tools are reluctant to add/develop those capabilities because no import tool can support this”. 

It would be great if capabilities are enforced and explicit in the standard. Or it would be extremely hard to push reliable and new algorithms to users.

**Comment by pmai** [comment]
@hyumo I think your comment goes beyond the current issue, which is whether functions in the C-API must be present regardless of the capability being supported or not, not whether capability flags (i.e. optional features) are a good idea or not. I think if this discussion is to be had (which would only apply to FMI 3.0++ in any case), it should be moved to a new issue.

As an aside: I highly doubt that any changes in the standard will have an impact on FMUs suddenly appearing with "advanced" features, since this is a market economic problem, not something that can be forced by the standard, especially not now that 2.0 is out: Making all kinds of optional features mandatory in 3.0 will only lead to most exporters not supporting 3.0 full stop, since for many things the advanced features either cannot be supported - consider directional derivatives for embedded controller code, or get/set fmu state for an FMU that is an interface to real hardware - or do not make economic sense for the use cases in question. Making stuff mandatory that cannot reasonably be supported in those situations is only likely to lead to the standard being ignored one way or another.

**Comment by hyumo** [comment]
Thanks @pmai , I totally agree that this is more of an economic issue rather than a technical one, to make those features optional favors/pleases export tools, but gives import tools a bit of hard time, which directly affects *user* experience. I think it is probably a much longer discussion than a github issue.

I also agree that, for different use cases, some of those features are not realistic or necessary, and this will cause a complete stop on exporting 3.0 FMUs if those features are enforced. However, if we think the other way around, if we assume new 3.0 FMU features are all optional, why would an import tool supports 3.0 if nothing new is added, or how do we encourage our users to upgrade to 3.0?

I think this will be an endless debate, but I hope there will be solutions to target those issues, here are my 2 cents:
- Make an advanced version FMI standard which requires everything? Just like like ModelExchange and CoSimulation, maybe we could have CoSimulation-Strict/Experiental/3.0++?
- Make APIs self implementable, like calculating directional derivative, get/set FMU states and serialization are currently impossible.

**Comment by pmai** [comment]
To the core issue I think we could have a clarifying point in the 2.0.1 release that takes the paragraph Karl quoted above and expands it like this:

> The implementation must either implement all the functions of FMI for Model Exchange or all the functions of FMI for Co-Simulation or both. Specifically it is required that all functions specified for Model Exchange and/or Co-Simulation are present, even if they are only needed for capabilities that the FMU does not support. The behavior of those functions are unspecified, so while calling environments can rely on the functions being present, they cannot rely on any particular behaviour for functions only needed for capabilities the FMU does not support. 

And I think that sentence should really be moved from section 2.3 (which deals with packaging into a ZIP archive) to section 2.1 (which introduces the common C-API).

**Comment by pmai** [comment]
@hyumo These are some of the considerations that are already being taken into account when designing new features for FMI 3.0 (especially in order to allow FMUs that support more advanced features to allow transparent fallback when used in importers that do not support those features, which is IMHO a much bigger impediment to new version adoption than the other way around). There's also the idea of having use case specific profiles that require certain features for certain use cases (something which can be done independently from MA, BTW). However I think this discussions should move to a seperate issue (and also onto fmi-design, etc.).
