### ISSUE TITLE
Shall we use a three-digit version string

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#433]
**Reported by cbertsch on 31 May 2018 18:23 UTC**
For FMI 1.0 and FMI 2.0 we use a two-digit version string.
For FMI 3.0 it would be possible to use three-digit version string "FMI 3.0.0" and require, that an FMI 3.0.x importing compliant importing tool must be able to import all 3.0.y versions.

----

Migrated-From: https://trac.fmi-standard.org/ticket/433

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#x2e;junghanns on 31 May 2018 18:32 UTC**
I would call it FMI 3.0 compliant, not FMI 3.0.y compliant (see your compatibility explanation). The version string in the FMU should likely be FMI 3.0.0 or later FMI 3.0.x but importers would largely ignore the bug-fix digit, except to be more strict in "later" versions because additional clarifications leave less room for interpretation and potential trial and error when running an FMU from earlier (more ambiguous) versions.
Right?

**Comment by modelica-trac-importer** [comment]
**Modified by andreas&#46;junghanns on 31 May 2018 18:32 UTC**

**Comment by chrbertsch** [comment]
FMI Design in Regensburg: 

Discussion: 
If we have "3.0.3", one knows that the exporter has implemented clarifications for ambiguities. An importer could then rely on the fix.
But: One cannot make changes in bugfix releases anyway.
The "semantic versioning" definition is about implementation and not about standardization.

Poll: 
Pro 3 digit: 8
Contra: 2
Abstain: 2

We should give a rationale in the specification.

Task: Check XSD,  specification text

**Comment by chrbertsch** [comment]
Shall we still go on with the three digit version string? We had a poll for it, see above (https://github.com/modelica/fmi-standard/issues/433#issuecomment-470575473) ...

In order to discuss this, I created a draft PR#961

The main risk that I see with this, is that importers supporting FMI 3.0.0 will not be able to support FMUs created after the release of future bugfix versions of FMI. We could overcome this by creating a dummy reference FMU with a  version string "3.0.17" that every FMI 3.0.0 importing tool should be able to load and simulate. 

Please comment!

**Comment by chrbertsch** [comment]
(Andreas, Christian)
closed in favour of #983
