### ISSUE TITLE
Clarification of stepSize for CoSim FMUs

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#434]
**Reported by maplesoft on 1 Jun 2018 17:21 UTC**
The meaning of stepSize, if provided in the DefaultExperiment field, needs to be clarified.
On pg. 43 of the spec it says:
"for CoSimulation the _stepSize_ defines the **preferred** communicationStepSize"
but on pg. 96 it says:
"the **smallest** sample period as accessible by the outside of the FMU is defined by attribute _stepSize_ in element DefaultExperiment"

So should the importing tool interpret it as a minimum or just a preferred step size?  This is important especially when canHandleVariableCommunicationStepSize = false.

----

Migrated-From: https://trac.fmi-standard.org/ticket/434

**Comment by modelica-trac-importer** [comment]
**Comment by karl&#x2e;wernersson on 26 Jun 2018 15:05 UTC**
Remove in 3.0 , use clock if you want to define step size.

**Comment by ghorwin** [comment]
IMHO stepSize can be interpreted as follows:

- fixed step size FMUs and master algorithms: -> use stepSize as communication interval
- variably step size FMUs and master algorithms: -> stepSize use as *initial* **and** *maximum* allowed interval when *initially configuring the master algorithm*. Any decent master tool will allow the user to adjust these settings, so *stepSize* really only affects initialization of master-specific algorithm parameters. Also, in context of fmi-cross-checking, it allows consistent setting of these master parameters, thus (potentially) reducing differences between results.

## Rationale for using stepSize as "maximum" communication step

Some FMUs hold internal resources such as time-series data to be linearly interpolated. When the communication time step exceeds the sampling time of such time series, there is the risk of skipping (important) values.

But, as mentioned above, master algorithm parameters can normally be adjusted by the user in the simulation tool, so that usually just a warning shall be issued when stepSize of any used FMU is set to a lower value than the maximum step size.

I would reject the term of "preferred" step size, since this is ambiguous at best. When error control demands smaller communcation steps, they must be reduced below this "preferred" step. If steps are increased again and are clipped/limited to the "preferred" step size, the meaning coincides with "maximum time step" limit.

**Comment by chrbertsch** [comment]
> but on pg. 96 it says:
> "the **smallest** sample period as accessible by the outside of the FMU is defined by attribute _stepSize_ in element DefaultExperiment"

I propose to remove this sentence for FMI 3.0 as it contradicts

> On pg. 43 of the spec it says:
> "for CoSimulation the stepSize defines the preferred communicationStepSize"

Any objections?

Anyway, the full sentence reads

> A real sampled-data system (so a sampled discrete controller; the inputs and outputs can be of type Real, Integer, Boolean, String, or enumeration. Variables of this type are defined with variability = discrete; the smallest sample period as accessible by the outside of the FMU is defined by attribute stepSize in element DefaultExperiment).

and in FMI 3.0 one should use Clocks or SES for "sampled discrete controller"

**Comment by andreas-junghanns** [comment]
Agree to both suggestions.

**Comment by ghorwin** [comment]
Still, the ambiguous term "preferred" is still in the standard text, which I object to. What do we do about this?
