### ISSUE TITLE
Setting input start values before fmi2EnterInitializationMode (clarification in 2.0.1)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#440]
**Reported by cbertsch on 18 Jun 2018 10:10 UTC**
(FCP alignment Meeting:) 
Corresponding to #369 (contains changes for FMI 3.0)

Clarify in 2.0.1 that setting of input start values before fmi2EnterInitializationMode is not allowed. 

(the specific problem seem in practice to occur only if the the exported FMUs contain bad start values and can be solved in the exported FMUs)

See also #349 for the scope of maintenance/bugfix releases

----

Migrated-From: https://trac.fmi-standard.org/ticket/440

**Comment by chrbertsch** [comment]
Closing as included in merged PR #579

**Comment by CThuleHansen** [comment]
@chrbertsch I am going over this issue in 2.0.1 RC 3 due to a discussion in the FMI design meeting.
 
It has been fixed two places in the standard
p.86 `this does not include inputs`
p. 107 `this does not include inputs...`

But the old wording - which is **not** incorrect, just less explicit - is still present in:
p. 77 `Table 1: Mathematical description of an FMU for Model Exchange.`
p. 86 `Figure 6: Calling sequence of Model Exchange C functions in form of an UML 2.0 state machine.`
p. 88: `table description of 1`
p. 103: `Table 2: Mathematical description of an FMU for Co-Simulation.`
p. 107: `Figure 11: Calling sequence of Co-Simulation C functions in form of an UML 2.0 state machine.`
9. p. 109: `table description of 1`

I am unsure whether these should be updated or not. In principle, it is just duplication of the same text in a lot of places.

**Comment by chrbertsch** [comment]
> But the old wording - which is **not** incorrect, just less explicit - is still present in:
...
> I am unsure whether these should be updated or not. In principle, it is just duplication of the same text in a lot of places.
@CThuleHansen : As you state it is not incorrect, this late in the release of FMI 2.0.1 I would not change it.
