### ISSUE TITLE
FMU co-simulation run time error

### ISSUE THREAD

**Issue by siddharthaDevineni** [modelica/fmi-standard#502]
Hello,
After importing a FMU and when I tried to run the simulation the following error shows up, could anyone please help me out with this?

Log from FMU: [category:logStatusError, status:fmi2Error] Simulation terminated due to error(s) at start time.
Log from FMU: [category:logStatusError, status:fmi2Error] fmi2ExitInitializationMode: FMU encountered runtime error during simulation.

I would be very glad if you could answer ASAP.
Thank you so much.

**Comment by pmai** [comment]
This repository deals with the FMI standard document itself, not with individual implementations (i.e. individual FMUs or individual simulators importing FMUs). You will have to address your questions to either the author (and authoring tool) of the FMU you are trying to import, and/or to the importing tool (i.e. the simulation tool) that you are using to run the FMU.

As an aside, potentially increasing the log level of the simulator might trigger the FMU to provide more information about why it cannot exit initialization mode (which might be caused by inconsistent start values, or something else entirely).

**Comment by chrbertsch** [comment]
This is an issue tracking for the developmentment of the FMI Standard, not for FMI user support.
I recommend to use StackOverflow (tagged "FMI")  instead; please provide there also more information:  form which tool was the FMU exported, which was the importing tool; best would be to provide also the FMU there.

**Comment by siddharthaDevineni** [comment]
Thank you very much for the suggestions
