### ISSUE TITLE
Generate PDF from AsciiDoc sources

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#504]

**Comment by chrbertsch** [comment]
Even though PDF generation with the asciidoc-docker image works in principle, @t-sommer  and I consider it significant effort to generate a nicely formatted PDF (e.g., formatting the pictures, pagebreaks etc.)

As we are considering the html version our main release medium of the FMI 3.0 standard, as an alternative I suggest to consider if it is not sufficient just to provide a pdf version generated from the html.

I tried to print from Firefox on a Windows machine, gut got printing errors (because of the file size? I tried two printer targets: Adobe PDF and Microsoft PDF printer).
I tried the same on an Ubuntu Linux machine, and succeded, but the hyperlinks were all gone.

Then I tried to print from Chrome on a Windows machine, and the results looks sufficient for "Just having a printed version", also preserving the hyperinks.

[FMI3dev_chrome.pdf](https://github.com/modelica/fmi-standard/files/4238151/FMI3dev_chrome.pdf)

I consider this sufficient and would not spend more effort in this topic and close this ticket as Wontfix, at least for the moment. Anyone objecting and/or volunteering to do the asciidoc-pdf-generation?
