### ISSUE TITLE
Include descriptions from schema files

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#537]
AsciiDoc allows the inclusion of sections of XML using [tags](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-lines-tags.adoc).

It would make sense to synchronize the description in the XSD schema files with the current documentation and include the text into the documentation so we have a "single source of truth" (see also #464).

Example: add a tag to the schema file... 

```
<xs:element name="Binary">
  <xs:attribute name="maxSize" type="xs:nonNegativeInteger" use="optional">
    <xs:annotation>
      <xs:documentation><!-- tag::BinaryMaxSize[] -->If present, limits the maximum size of the binary to the indicated value. All variable accesses, both getting and setting of values must guarantee that the returned size of the binary is strictly equal or less than this maximum size.<!-- end::BinaryMaxSize[] --></xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:element>
```

... and include it in the documentation

```
== Element <Binary>

=== Attribute maxSize

include::fmi3Variable.xsd[tag=BinaryMaxSize]
```

**Comment by chrbertsch** [comment]
FMI regular design meeting: 
this concept is already used  for c-code, extending it to xsd.
Single source is always good.
General agreement
Torsten: one has to make sure, that one uses special formatting so that it displayed nice.
Comments in the XSD: not always reliable for the html. One solution would be to remove the comments in the XSD. (in 2.0 they do not always have the same meaning as the spec). 
Or we can say, that all the comments in the xsd are non-normative. 
otherwise we have to synchronize and check.
(in FMI 2.0 there were screenshots with comments, that were not always consisten)
It is hard to synchronize.
Currently the commments are out sync

Proposal: remove comments (documentation tag) from xsd-files.
Poll: 
In favour: Torsten, Klaus, Masoud, Jean-Philppe, Kaske., Christian
Against: 
Abstain

**Comment by t-sommer** [comment]
The documentation has been removed from the XSDs which makes this issue obsolete.
