### ISSUE TITLE
Return value for illegal function calls

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#574]
It is usually not well defined what an FMU should return one of its function is called with an illegal argument. With illegal argument i include things like

- invalid valueReference
- invalid state call.e.g  newDiscreteStates in continoustime mode, setting a fixed parameter after initialization
- providing a  nullState for setFMUstate
- etc.

Currently an FMU exporter has to either return a warning or an error.
a waring has the risk of getting ignored while an error forces the master to terminate even though it might be able to recover. 
I would argue that what behavior you want is more on the master side than on the exported FMU side.

if a master is non interactive during simulation, you would probably want to terminate since you have either programed your master wrong or the exported FMU is wrong and there is little you can do now to fix it.
However if the master is interactive, then a user using it could try do allot of dumb things and it would be sad to force termination instead of giving a proper message, e.g. "illegal call, please do something else"

We could call it
fmi3Illegal

**Comment by chrbertsch** [comment]
Regular Design meeting: 
Masoud: we need something like this during initialization (e.g. like. This input would lead to a dvision by zero)
Karl: in this specific case, one could use discard. One  could use discard for setReal
Klaus: agree. Perhaps we should not mix these two issues: numerical reasons, not allowed function called.
Klaus: Strongly reminds me of DCP discussions ... distinguish between several log / error messages: what can the master expect that the slaves checkes. The master can e.g. know if the call of setting a value went wrong.
Kaska: We need a clear specification how a function call reacts to an error.
Klaus: Look at DCP specfication 3.4.7 , what happens for PDUs (these are essentially function calls)
Kaska: one should get the same error codes for different FMUs in the same error case
Karl: My proposal was more lightweight. Error code are good, but would need a lot of work.
Klaus: in DCP, the focus was on realtime systems. With error codes, more automatization is possible.


Poll (multiple options possible): 
* do nothing (keep it as in FMI 2.0, one could use error or discard)
** Antoine, Andreas, Masoud, Kaska
*define "fmiIllegal" + non standardized human-readable message (could be extended later with error codes)
** Karl, Christian B., Masoud, Klaus, Thorsten G. 
* define detailed Error codes for specific cases that we can imagine.
** (no one)

Karl will prepare to proposal for the Design meeting.

**Comment by pmai** [comment]
Sorry could again not attend today’s meeting, but might I suggest that instead of adding a new fmi3Illegal or whatever we might want to have fmi3Error be that code, since that is what reasonable people expect an error to be: Something that didn’t work, but nothing gets corrupted or destroyed. If we want to keep the fine-grained distinction between “I’m kaputt” and “everything is beyond repair” (fmi3Error vs fmi3Fatal as defined now), I’d propose something like fmi3Critical or fmi3Serious as the name for what is now fmi3Error.

**Comment by chrbertsch** [comment]
Regular design webmeeting: 
Pierre: We should have something that indicates an illegal call. The is only a small destincion between error and fatal. (in an error one still could continue)
Kaska: what about fmi3warning?
Karl: people do not read errors.
Pierre: Anyway it is just naming ...
Karl: Changing the definition or error between versions is pronblematic

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Torsten S: New Proposal: Use warning.

Andreas P: Should we allow continuing in case of a wrong argument?

Torsten B: The master could repeat the call with a correct VR for example.

Torsten S: We should give better advice about warnings, errors.

Torsten B: In cases of a wrong calling sequence, it should be an error. But we have not defined what to do in case of errors.

Torsten S: Illegal VRs should always crate an error

Torsten B: Illegal calling sequence should be an error. (But perhaps the FMU is so simple it does not care)

Suggestion: 
* Clarify use cases of fmi3warning.  Add to document: in case when the one can safely continue simulation, give a warning, in other cases give an error.
* Reformulate that a logger function MUST be called before warning is returned. 
* Use errors/warnings to inform the user. E.g. use error in case of wrong calling sequence, use warning in other cases.
* Difference between Warning and Discard: Discard can be used for several functions to inform the master that a problem occured, that can be solved e.g. by using a different timestep. For Discard the Solver can solve the problem automatically. For warning: inform the user with a message, he has to decide what to do.

Torsten S.: We could include this also as a recommendation to FMI 2.0.1

Torsten B: Example for a warning: A tool cannot handle toleranceDefined=true of fmi2SetupExperiment. Shall only the logger be called? Or also fmi2warninng?

Pierre: I do not expect masters to do intelligent stuff if we do not have encoded  error codes.

Torsten B: in case of a message the user must decide.

Pierre: the user would have to change parameters ... open an menue to select correct VR. It would be better to throw an error. 

Pierrre: Do we want mandatory error checking? (E.g. for wrong VRs, wrong calling sequence)

Torsten S: Add it as a recommendation, not mandatory.

Pierre: it is not time critical --> We could discuss this e.g. in December

@KarlWernersson: Could you look into this?

**Comment by clagms** [comment]
Maybe a reference FMU that contains all possible checks on the behavior of the environment could be the reference one wants, instead of trying to write this by hand in the standard.
Maybe @nickbattle 's work could be used for this.

**Comment by nickbattle** [comment]
@clagms is referring to the formal model of the dynamic semantics that I am working on. This has to define the error behaviour on each API as well as the correct behaviour of that API in terms of an abstract representation of the state.

So for example, fmi2SetReal performs the following argument checks:
- Does the length of the value reference array match nvr?
- Does the length of the new values array match the length of the value reference array?
- Are the "general SetXXX preconditions" met (from the state machine, depending on state - SEA IN INI etc.)?
- Are all the VRs referring to Real variables?
- Are all of the new values within the calculated (eg. inherited by definedType and considering alias sets) min/max for the variables?
- Do any variables have causality "independent"?

There is also an implicit dependency on the correct static semantics of the configuration - ie. the behaviour of the API is only defined for modelDescriptions that are correct.

If these tests pass, they become preconditions on the "core" definition of the API that defines how the abstract state is updated. If any argument checks fail, then "fmi2Error" is returned and the state of the system is completely unchanged (ie. it doesn't process the VR's left to right until one fails. This isn't defined by the standard, but I have to make a choice and this is the cleanest behaviour).

There is an implicit ordering of the checks at the moment. That is, the checks are performed in an arbitrary order and the first to fail is logged; it might be better if all failed error checks were logged.

An implementation would be free to return fmi2Error for other cases, perhaps out of memory or some other internal issue. But we are trying to (formally) define the minimal set of checks that each API ought to perform, that are then sufficient to specify the normal successful behaviour.

The formal model is a work in progress. We know that the core definition of an API's behaviour can require yet more preconditions that turn into extra checks (these are required to satisfy "proof obligations"). For example, in the case of fmi2SetXXX, we have to define what happens if the value reference array contains duplicate entries. Either we insist that the corresponding update values are the same or we make this another error case.

The formalisation of FMI3 is somewhat behind FMI2 currently, but progressing :-)

**Comment by pmai** [comment]
Just to be sure that there is no mis-understanding on my part: The formalisation you are working on provides for checks that one would place against an importing tool, to ensure that it does not call the API in illegal ways (and vice-versa for calls/return values that come from the FMU).

The standard currently does not pose any requirements on error checking, either for actual FMUs nor for importers.

**Comment by nickbattle** [comment]
@pmai Yes, the argument checks are an attempt to define what constitutes a legal call, given the current state of the system. The modelling of an abstract state (derived from the modelDescription) then backs that up with minimally correct behaviour, so some API calls "change things". But the underlying purpose of the FMU (eg. to simulate a bouncing ball) is not defined; this is delegated to external computation functions, which can be provided for testing but which aren't part of the specification - other than by being invoked at specified places to update the FMU state.

**Comment by clagms** [comment]
2020-04-30-Regular-FMI-Design-Meeting

CB: KW, can you look at this please?

Conclusion: let's close this and label it as "wont-fix".

**Comment by KarlWernersson** [comment]
OK Closing

**Comment by chrbertsch** [comment]
The use of discard for illegal function calls is described also here: https://github.com/modelica/fmi-standard/pull/986
