### ISSUE TITLE
Clarify whether 'unit' attribute in Real TypeDefinitions is mandatory or not

### ISSUE THREAD

**Issue by ghorwin** [modelica/fmi-standard#578]
The FMI specs (version 2.0) do not state whether a TypeDefinition of type real must include a unit attribute or not.

Some of the Dymola-FMUs in the cross-check repo have Real type definitions without _unit_ attributes. Since they ought to pass the compliance checker, I assume that missing the _unit_ is allowed.

Questions: What unit shall be selected when the unit attribute is missing or when an empty string is passed as unit (i.e. in unit compatibility tests in FMI Masters)? 

IMHO having real type definitions without unit doesn't really make sense and I would favor  making this a mandatory attribute (even if the exporting tool would specify an empty string or something like - or --- as unit).

**Comment by KarlWernersson** [comment]
Hi It is clear, since unit is an optional attribute for real **is not mandatory.**
#337 deals with empty unit string. It is not recommended but possible, but if a variable has an empty string as a unit it has to have it defined in types definition with the name "". 
The correct way of not having a unit is to not include the attribute at all in the xml.

It is up to the importing tool how to deal with units or to care at all, FMI just give the tool the option to do so. In Dymola we check units, but unities variables can be connected to a variable with any (or none) unit, but other tools might have another way of doing this.
