### ISSUE TITLE
Handling triggered clocks (triggered time-events)

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#589]
Triggered clocks tick due to state, step, and time events.  
In order to handle a triggered clock ticking due to a time-event in the FMU, the simulator retrieves the event-times by calling GetInterval() for a particular clock.
Then the simulator schedules the simulation and once the event time instant is reached, pushes the FMU into the event-mode.
In the event-mode, the FMU should distinguish the reason for which it is in the event-mode, which may be a step-event, a state-event, a discrete time event or a triggered clock.
In the current specification, the FMU needs to compare its internal clock times with the current simulation time. If they are identical the FMU returns the activated clocks via GetClock().  
In order to avoid problem in the time comparison, very often an error tolerances is used by the FMU to check whether a time event has happened.

Note that, unlike inferred clocks where the simulator is allowed to perform a SetClock() to indicate to the FMU that an inferred clock has ticked, for triggered clocks, this is not possible.
The simulator is only allowed to invoke GetClock() to retrieve the ticked triggered clocks.

In order to avoid such numerical errors or using error tolerances in time event comparison,  the simulator should be allowed to do SetClock() on triggered clocks too.
Since the simulator has the clock reference and the time of triggered clocks, it looks more natural that the simulator performs  Setclock() for the triggered clock to inform the FMU about triggering of that clock.

Am I missing something? In any case, we would need a solution to get rid of time-event comparison inside the FMU to detect and tick a triggered clock.

**Comment by chrbertsch** [comment]
Regular design meeting: 
Andreas P.: Is this an issue for the Hybrid Cosimulation group? 
Masoud: This is already a problem for FMI 2.
Andreas P: Currently, the FMU ticks and not the master. 
Pierre: How would the master know, that a clock has ticked?
Torsten S.: Is this not related to #588?
Masoud: who is responsible for a time event? --> the master
Torsten S: we could pass this information to the FMU. This is about model exchange (hybrid co-simulation shall be treated separately). You should tell the FMU, the reason why you call event update. Could be a time event or a detected state event (#588).
Torsten S: @masoud-najafi : could you please provide more motivation?
Masoud: In our implementation, we use always an epsilon to detect time-triggered events.
Pierre: in ME, there is no internal time.
Masoud: in ME, the next event time is calculated by the FMU
Torsten: We should rename the name of the ticket and give an example. @masoud-najafi : could you do this? Something like "pass reason for event update to FMU"
Pierre: clocks would need a separate  discussion, should be excluded here.
Masoud: time events in FMI 2.0 will have the same problem as clocks in FMI 3.0
Torsten: But the solution could be carried overe
Pierre: I would expect the model not be there for Clocks.
Pierre: We perhaps should split the ticket.
Massoud: I encourage everyone to comment this issue. (@KarlWernersson  :-) )

**Comment by t-sommer** [comment]
@masoud-najafi, is the function below what you want to do for the Model Exchange case (i.e. pass the "reason" for the event update to the FMU)?

```c
fmi3Status fmi3EnterEventMode(
  fmi3Component c,
  fmi3Boolean stepEvent,
  fmi3Boolean stateEvent,
  fmi3Boolean timeEvent,
  fmi3Float64 eventTime
);
```

**Comment by masoud-najafi** [comment]
There are four kind of discrete events, i.e., StateEvent, StepEvent, TimeEvent, or InputEvent.
 In FMI-2.0, if one or several discrete events happen, the simulator pushes the FMU into the event mode to get the event handled.
 The FMU can also be pushed into the event mode, without any discrete event.
 The problem is that the FMU has no indication about the reason for which it has been pushed into the event mode.
 In the event mode, the FMU should find itself the origin(s) of the event to handle events correctly.
 
 In FMI-2.0, the proposal of Torsten (https://github.com/modelica/fmi-standard/issues/589#issuecomment-513443721)  and  the proposal #588 (https://github.com/modelica/fmi-standard/issues/588)  allow passing the event origin and avoid extra work and uncertainty in the FMU.
 
 In FMI-3.0, the inferred and triggered clocks have been introduced for FMI for ModelExchange as well as for FMI for CoSimulation. This issue will be present especially for Triggered clocks.

**Comment by HansOlsson** [comment]
> In FMI-3.0, the inferred and triggered clocks have been introduced for FMI for ModelExchange as well as for FMI for CoSimulation. This issue will be present especially for Triggered clocks.

I'm a bit confused here and couldn't find this in the current dev-version.

In the synchronous part of Modelica there are "triggered clocks" (a.k.a. Clocks with Boolean condition), and additionally the normal event handling is also described as triggered by something.
I believe we need to separate those.

I agree that we need to know when a "triggered clock" is triggered, but I don't see how a step event could trigger such a clock, or similarly how an input event directly could trigger it.

Regarding the idea of having different flags for differnt kinds of events: in general that is a good idea - however, a in practive it is often easy to miss one of the combinations (e.g., step event with time event and no state event) - so we might consider how to design the API to avoid that.

**Comment by t-sommer** [comment]
> I'm a bit confused here and couldn't find this in the current dev-version.

The Hybrid Co-Simulation feature is still a work in progress that has not been merged (see https://github.com/APillekeit/fmi-standard for the latest version).

**Comment by chrbertsch** [comment]
Regular Design meeting: 
Andreas P.: Massoud, could you explain the need? We have triggered clocks and inferred clocks. 
Massoud: Who detects ticking the triggered clocks? Can they be time triggered?
Andreas: ....
Massoud: Master controls the clock time, and should inform the FMU. 
Andreas: this is then an inferred clock. For a periodic clock, the FMU can transport the periodicity information to the master via the XML
Massoud: It is similar to the time event in FMI 2.0, right? Is the feature still there?
Andreas P.: if the FMI is able to detect a time event, it can do so, otherwise it should define an inferred clock
Massoud: We do not allow to set ... for triggerd clocks?
Andreas P.: Yes
Massoud: How does an FMU at event time, which clock should tick? If there are multiple ticks at one time
Andreas: P. : The FMU has the time information of the starting time and end time in CS
Massoud: I talk about ME.
Torsten B.:  Do we talk about the proposal of Torsten S. or ....?
Massoud: The extension of Torsten S. is very good, but not sufficient
Torsten B.: I agree for the extension, but would not allow for setClock for triggered clocks. It is up to the modeller to design the clocks accordingling
Massoud: We need some clarification.
Andreas P: What would be the clarification?
Massoud: We should forbid time triggered clocks into the FMU
Torsten B.: it is up to the FMU. Then it is responsible to trigger it.
Massoud: Another question: can we have two time triggered clocks at the same time?
Torsten B.: it is up to the FMU
Massoud: this is an uncertainty
Torsten B: this is not uncertainty, this is up to design 
Andreas P:  ....
Torsten B: This can happen, but is deterministic. When it comes to implementation I would not know what to do when the master uses setClock on a triggered clock
Masoud: The Master should do this
Torsten B: For this we have inferred clocks
Christian B.: Massoud, could you come up with a clarification?

Masoud: The problem  is stated in the ticket. Let's incorporate Torsten's proposal. I will try to find an example to show the problem, at Lund meeting.

Torsten B.: I propose to extend Torsten's proposal to support tools which are not able to communicate the reason of an FMI3EnterEventMode call to an FMU.

Torsten S: Could we keep them all optional?

Torsten B: We have to specify to allow to set everything to false or true?

Masoud: What should the FMU then do when all Booleans are false?

Andreas: P.: It is unclear. 

Masoud: Currently it is allowed to push the FMU in event mode without any reason. Perhaps the solver does not know why inputs change discontinuously

Torsten B.: Perhaps the master cannot transport the information  to the FMU

Masoud: We could also have an additional boolean

Torsten S: I prefer to have all booleans false if we do not know.

Torsten S: We need a pull request for this

Torsten B: We need the same information for newDiscreteState.

Andreas: We use the same newDiscreteState for Hybrid Cosimulation. We should use it in the same way as in ME.

Masoud: When timeEvent boolean is true, it means either one of triggeredClock inferedClock, time event has happened?

Torsten B: not a triggerd clock. The FMU decides if a triggered clock ticks.

Torsten B: This would also be possible

Torsten S: I will prepare the API part; Torsten B.: can you help me in the description

**Comment by otronarp** [comment]
I realise that I'm late at the game, but what's the reason for the weak formulation? As I read it I, as an FMU, cannot rely on the timeEvent flag to be set if the environment pushes me to event mode due to a time event in myself. If cannot rely on it, what's the point of the API?

**Comment by t-sommer** [comment]
> I, as an FMU, cannot rely on the timeEvent flag to be set if the environment pushes me to event mode due to a time event in myself. If cannot rely on it, what's the point of the API?

If you get this information (`timeEvent == fmi3True`) you can use it to perform your update more efficiently especially for time events where the master might not hit the event time exactly e.g. if it's  using a fixed step method.
