### ISSUE TITLE
Variable attributes "min", "max" and "nominal" should be lists

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#590]
... like for attribute "start", so a value can be supplied for each index.

**Comment by otronarp** [comment]
My take on this is that min/max/nominal (as well as all the unit/quantity related attributes) are part of the "type" and I really would like us to restrict arrays to contain one single type.

**Comment by KarlWernersson** [comment]
I agree, use scalar if you want to scalarise you array, one of the main things that makes it harder to import "arrays" deduced from structural naming, in FMI 1.0 and 2.0 is that there is no requirement that the types are consistent. This was discussed quite thoroughly during early design of the array proposal and it was decided to restrict types because of this.Another problen lies withdynamic sized arrays, for start values we have explicitly stated that they become invalid  if you deviate from the default size. (if I remeber corectly).However min/max are more fundamental model properties and you would need some getMin/max functions for each vector . (we do already have getNominalsOfContinousStates but that is in conjunction with using get/setContinuousStates)

**Comment by t-sommer** [comment]
It's fine for me to keep these attributes as scalars. I suggest we add a sentence to the spec that this is intended.

**Comment by chrbertsch** [comment]
Regular FMI Design meeting: 
Klaus: I agree with Otto and Karl.
Andreas: Me too. Fits to "traditional" computer science (different to Modelica :-)  )
Klaus: I do not know of we need an additional sentence. For "start"  there is a shortcut defined. There one could add a clarification for min/max

**Comment by t-sommer** [comment]
Let's keep it as it is for now.
