### ISSUE TITLE
Boundaries of simulation intervals in the co-simulation specification

### ISSUE THREAD

**Issue by sglumac** [modelica/fmi-standard#613]
In the section describing the basics of the mathematical model for co-simulation (4.1.1. Basics) there is a bullet list starting with the sentence: "FMI for Co-Simulation is restricted to slaves with the following properties". The 6th bullet in this list says that "Whenever the simulation in a slave is interrupted, a new time value <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_{i%2B1}, tc_i <= tc_{i%2B1} <= t_{stop}"/>, can be given to simulate the time subinterval <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i < t <= tc_{i%2B1}"/>".

This statement may be contradictory a new time can be set as <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_{i%2B1} = tc_i"/> and latter says that the simulation interval ends with <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_{i%2B1} > tc_i"/>. If the former said "a new time value <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i < t <= tc_{i%2B1}"/>" I think it would be ok.

Furthermore, in section 4.1.2 Mathematical Model under the equation (4.1) there is a statement "<img src="http://chart.apis.google.com/chart?cht=tx&chl=\mathbf{\Phi}_i"/> and <img src="http://chart.apis.google.com/chart?cht=tx&chl=\mathbf{\Gamma}_i"/> define the system behavior for the time interval <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i <= t < tc_{i%2B1}"/> with <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i = tc_0 %2B \sum_{k=0}^{i-1}hc_k"/>". I would interpret this that an FMU simulates the time subinterval <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i <= t < tc_{i%2B1}"/> and not <img src="http://chart.apis.google.com/chart?cht=tx&chl=tc_i < t <= tc_{i%2B1}"/>.

I am interpreting this as an inconsistency in the boundary definition of the simulation subinterval. I apologize if this interpretation is due to my misunderstanding of the topic.

**Comment by chrbertsch** [comment]
As no one commented on this, remove milestone 2.0.1. 
@antvl : could you please look into this and comment?

**Comment by sglumac** [comment]
I would like to add an example that shows an inconsistency.

Suppose a slave solves the initial value problem with the initial value
x(tc_0) = x0
 Since Phi_0 defines the system behaviour on the interval tc_0 <= t < tc_1 then
x_1 = Phi_1(x_0, ...)
defines the behaviour of the state signal on the same interval. To the best of my understanding the standard states that you define an initial value by
x(tc_0) = extrapolation(x_1, tc_0)
and this value may be different than the initial value specified by the slave.

I had a discussion with @klausschuch and I hope I explained my problem with a little bit more detail in this discussion.

**Comment by klausschuch** [comment]
I agree to the first part, the sentence should be changed to:
Whenever the simulation in a slave is interrupted at time latexmath:[$t_{c_i}], a new time value latexmath:[tc_{i+1}, tc_i < tc_{i+1} \leq t_{stop}] can be given to simulate the time subinterval latexmath:[tc_i < t \leq tc_{i+1}]

This change basically highlights that no do-step with a communication step-size = 0 is possible.



I am not sure about the second part.
I guess the current version of the text is written based on when inputs [u_i] are set:
At time [t_{c_i}], the system gets inputs [u_i] for exactly this time and these inputs are valid until the next communication step [t_{c_{i+1}}] is reached.

However, I think it should be change to latexmath:[tc_i < t \leq tc_{i+1}] too.
My main argument is (again) that the FMI standard requests that communication step-sizes are greater than 0.

**Comment by sglumac** [comment]
> As no one commented on this, remove milestone 2.0.1.
> @antvl : could you please look into this and comment?

Is there a pogress on this topic? BTW, for me this topic is closely related to https://github.com/modelica/fmi-standard/issues/622. I think the integration intervals should be aligned with the definition of the signals exchanged between co-simulation slaves.

**Comment by andreas-junghanns** [comment]
@clagms : Have we worked on this part already? Can we close this?

**Comment by sglumac** [comment]
If you worked on the issue, can you, please, comment on the outcome?

**Comment by clagms** [comment]
Thank you for following up on this @sglumac !
This is on my todo list, but haven't come around yet to work on it. We will probably cover this when we update the mathematical description of BCS...
I hope this is not getting you stuck on your work, right?

**Comment by sglumac** [comment]
Hi @clagms ,

I am working on the error control algorithm, which is based on the reconstruction of signals in the continuous domain. I'm not sure how to apply the algorithm to FMUs because I'm not sure how to interpret the standard.

I'm not blocked in my work, I can always add the assumptions that are required for my algorithm to work. However, it would add value if I could say that I am 100% sure that it can be applied to FMUs.

If you think it would help to talk, I am available.

br,
Slaven

**Comment by clagms** [comment]
I've started working to fix this in https://github.com/modelica/fmi-standard/pull/1075

Thank you @sglumac and @klausschuch  for spotting this and for the input!

I think I fixed the inconsistencies pointed out. 
However, do note that, in the following:
![image](https://user-images.githubusercontent.com/871103/85253596-d6175400-b45e-11ea-822c-c9648b386b1d.png)
the document defines the [flow](https://en.wikipedia.org/wiki/Flow_(mathematics)#Autonomous_systems_of_ordinary_differential_equations) function $\Phi_i$ of the initial value problem defined by the inputs and state set at time $tc_i$ (and prior inputs as well).
This flow function is defined in the closed interval $[tc_i, tc_{i+1}]$.
That does not mean that the FMI allows zero communication step size. The FMI standardizes how the flow equation may be used, but not how it is defined. 
The restriction of the communication step size being greater than zero is due to other practical issues such as defining what happens to the other features of the FMU when a zero step size is provided (do we compute the outputs from the inputs? When do we consider the input step size to be zero? etc..)

Let me know if you disagree with this :)

I corrected the earlier points, as they are clearly related to the standard, and not so much to the mathematical definition.

Regarding the following,
>Suppose a slave solves the initial value problem with the initial value
x(tc_0) = x0
Since Phi_0 defines the system behaviour on the interval tc_0 <= t < tc_1 then
x_1 = Phi_1(x_0, ...)
defines the behaviour of the state signal on the same interval. To the best of my understanding the standard states that you define an initial value by
x(tc_0) = extrapolation(x_1, tc_0)
and this value may be different than the initial value specified by the slave.

I don't quite understand what you mean here. @sglumac . Could you point me to where this is said in the standard? I don't remember reading anything about extrapolating the state of the FMU 😮 

Please scrutinize the changes made in https://github.com/modelica/fmi-standard/pull/1075

**Comment by sglumac** [comment]
> > Suppose a slave solves the initial value problem with the initial value
> > x(tc_0) = x0
> > Since Phi_0 defines the system behaviour on the interval tc_0 <= t < tc_1 then
> > x_1 = Phi_1(x_0, ...)
> > defines the behaviour of the state signal on the same interval. To the best of my understanding the standard states that you define an initial value by
> > x(tc_0) = extrapolation(x_1, tc_0)
> > and this value may be different than the initial value specified by the slave.
> 
> I don't quite understand what you mean here. @sglumac . Could you point me to where this is said in the standard? I don't remember reading anything about extrapolating the state of the FMU 😮

The standard states "where \(\mathbf{\Phi}_i\) and \(\mathbf{\Gamma}_i\) define the system behavior for the time interval \(tc_i \leq t < tc_{i+1}\), with \(tc_i = tc_0 + \sum_{k=0}^{i-1}hc_k\)." The behavior is not specified for the closed interval.

If I reread the example, it seems to be misleading. I apologize, I should have written about Gamma_i rather than Phi_i. I will try to add an example to ease the discussion. Suppose you have a system that updates the state according to
dx/dt(t) = u(t)
and the output according to
y(t) = x(t)
Suppose you use Forward Euler to solve the above system in the FMU
x_i+1 = Phi_i(x_i, u_i, hc_i) = x_i + u_i hc_i
and the output signal is extrapolated with constant extrapolation
y_i+1 = y(t) = Gamma_i(x_i, u_i, hc_i) = x_i + u_i hc_i, t in interval I = [tc_i, tc_i + 1)

According to this definition
y(tc_i+1) = y_i+2 = Gamma_i+1(x_i+1, u_i+1, hc_i+1) = x_i+1 + hc_i+1 u_i+1 = x_i + u_i hc_i + hc_i+1 u_i+1

However, according to #1075 
```
fmi2DoStep(component, tc_i, hc_i)
y = fmi2GetReal(component, yvr) // this is a loose interpretation of C

```
I am expecting that
y(tc_i+1) = y_i+1 = x_i + u_i hc_i

> Please scrutinize the changes made in #1075

It looks good for me. I think the mathematical description should be updated accordingly. Of course I accept that you may not share my opinion :)

Thank you for addressing the issue.

**Comment by andreas-junghanns** [comment]
@clagms : Can you create a PR that fixes the remaining issues raised here? Or can we close?

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

Andreas: we decided this in one of the design meeting. The importer must not set a communication interval of zero, but the FMU may immediately return with an early return

@clagms : I will create a PR
