### ISSUE TITLE
Clean up semantics of input and output derivatives (especially in context of IVA)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#622]
see discussion in #603 

* Clarify description of input/output derivatives in FMI
* Describe exact interplay between input/output derivatives and IVA

**Comment by CSchulzeTLK** [comment]
Proposal at design meeting:
We allow to use setInputDerivatives and getOutputDerivatives functions in Intermediate Output Values / IVA. We forbid to use getDirectionalDerivatives for the sake of simplicitly.

Current proposal to clarify setting values and extrapolation of inputs (incomplete yet):
"If a value is set with a setter function, then this value stays until the next call to the setter function for the same value reference. This also applies to the function setRealInputDerivatives."

**Comment by andreas-junghanns** [comment]
Further clarification is required for default values of derivatives to be 0, even if not specified.

**Comment by hv3ds** [comment]
This is one reason I started to ask about C++ at the Lund meeting. We'd define something like

class FunctionInterface
{
  virtual ~FunctionInterface() {}
  virtual double computeValue(double time) const=0;
  // some handy queries … what else?
  virtual bool isLinear() const;
};

We'd define lifetime management, applicability period.

Can we perhaps make something similar in "C"?

**Comment by chrbertsch** [comment]
Regular design webmeeting

Andreas P.: Currently initial values for input derivatives: undefined in FMI 2.0. 
What was the conclusion of the discussion?

@andreas-junghanns : is this your proposal for a a solution?
> Further clarification is required for default values of derivatives to be 0, even if not specified.

Could other experts on input derivatives, co-simulation and IOV please comment propose a solution
@klausschuch , @TorstenBlochwitz , Martin Benedikt, @robbr48, @jph-tavella, ...
Please also comment #603

**Comment by andreas-junghanns** [comment]
Yes, I think all agreed that we should assume 0 for default.

**Comment by jph-tavella** [comment]
Agreed for me to assume 0 for default value.

**Comment by robbr48** [comment]
I also agree that we can assume 0 as default value.

I suggest to either remove the input derivatives feature, or to prohibit it from being used in combination with IVA. All the other options above causes ambiguities or unwanted limitations. It is fine to support different interpolation techniques, but not to use them simultaneously.

**Comment by jph-tavella** [comment]
Removing the input derivatives feature is not a good idea (regression from FMI 2.0).
Prohibiting it from being used in combination with IVA could be a wise decision.

**Comment by nickbattle** [comment]
> Yes, I think all agreed that we should assume 0 for default.

Slightly off topic, but if we assume 0 by default, if the variable also has min/max values that don't span zero, would that be an error?

**Comment by nickbattle** [comment]
> Current flag MaxOutputDerivativeOrder is defined as an unsigned integer. Should be the same for the new proposed flag MaxInputDerivativeOrder. So the variable as zero as min value… and span 0.

OK, I think I understand. So an explicit min attribute on the variable that is not zero would be an error - ie. you can't define non-zero minima for derivatives?

**Comment by jph-tavella** [comment]
According to me yes, the min value for an unsigned integer being zero, this value should be the min for the variable MaxInputDerivativeOrder.

**Comment by jph-tavella** [comment]
@nickbattle Assuming X is an input, and der(X) has a min/max that doesn't span zero, the FMU should not expose a MaxInputDerivativeOrder flag set to zero but at least one.
But after that, if the master don't define a value for the input derivative, yes we have a problem because default 0 is not possible.

**Comment by pmai** [comment]
Hmmm, I'm getting more confused by the minute... What do the valid values for the MaxInputDerivativeOrder flag have to do with der(X) and especially the valid ranges thereof?

It seems to be true to me that:

- For variables for example that are strictly monotonically growing, of course the relevant der(X) variable can have a range that excludes 0. The same for all higher orders of derivatives. Again regardless of any MaxInputDerivativeOrder.

- A MaxInputDerivativeOrder == 0 just means that no derivatives are requested, it does not mean that the derivatives are 0 or not e.g. available through some other means.

- If you specify maxinputderivativeorder > 0 for a variable where one or more of its derivatives are exposed as input variables themselves, the master probably needs to be very careful in what values it is providing so as not to contradict itself. That said I don't think this depends on any valid ranges for those inputs, except of course that those must be adhered to.

But maybe I'm missing something here. Can anyone clarify what the issue is?

**Comment by HansOlsson** [comment]
I don't see that that access to intermediate values and input derivatives directly interact - at least not in normal cases.

The goal for the co-simulation is that it computes states and output knowing the inputs, which are given as a Taylor-series at the starting point (i.e. value, derivative, etc), and then simulates a step forward by using that - possibly internally triggering events during that interval; and also allowing access to these intermediate points.

If we know that the input have "discontinuities" in that interval we have to use a Taylor-series that approximates that, or split the interval into parts.

If we want to directly allow providing input signals with "discontinuities" it becomes messy and we need a more advanced interface - likely using some form of splines for the inputs. In combination with hybrid co-simulation an additional issue is that the input "discontinuities" will likely trigger events for the outputs, and if done incorrectly this will lead to a cascade of events; so it must be implemented and described with care.

And the case with der(x) not having 0 in min/max-range seems a bit esoteric, but as @pmai I don't see a problem of allowing MaxInputDerivativeOrder=0 for them; as both of them are defined by the same FMU.

**Comment by nickbattle** [comment]
Again, apologies if I'm causing confusion as my point is only indirectly related to the issue here. The suggestion was made that derivatives should have zero default values. I am trying to define all of the constraints on (any) variables' values, and I think one such constraint is that numeric variables that default to zero (ie. no "start" value) must also have min/max ranges that span zero - though note that the default min/max will do so.

This isn't a new issue that is caused in any way by the discussion here. It's just a clarification that arose because zero-defaulting was raised.

**Comment by jph-tavella** [comment]
I agree with @HansOlsson to say that access to intermediate values and input derivatives don't directly interact.
For me the flag MaxInputDerivativeOrder is defined by the FMU and used by the Master if desired (but not necessarily).
The meaning of this flag is clear: if the FMU says its flag MaxInputDerivativeOrder is n, it simply means that the Master can set inputs and the n first derivatives of inputs before each doStep(). But the Master can give less derivatives or even no derivatives at all, the stepping should be still possible at the FMU side, simply with less accuracy on internal calculations. Is not it?

**Comment by chrbertsch** [comment]
Superseded by #921
