### ISSUE TITLE
Clarify fmi2SetDebugLogging API

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#628]
On p21 [of the 2.0.1 draft], the fmi2SetDebugLogging function indicates what happens for nCategories > 0, but not when it equals zero. The fmusdk has interpreted this to mean enable or disable all categories. Can that be clarified?

Also, it is not clear whether this is intended to allow toggling of categories (multiple calls to enable/disable category sets) or whether it is a one-shot call. The fmusdk interprets it as one shot, resetting all categories before setting those passed.

**Comment by andreas-junghanns** [comment]
I agree we should improve the wording. But: so late in the process? We need a really good proposal that many would agree improves the description. Can you suggest?

**Comment by nickbattle** [comment]
Agree it's probably too late for 2.0.1. From the look of the API, and the presence of the loggingOn flag, it appears to be a "toggling" function. So I would say something like:

"Enables or disables debug logging for sets of logging categories. If `nCategories` is 0, then the change applies to all categories defined in the LogCategories section of the fmiModelDescription, otherwise only those categories listed in `categories` are changed. If the `loggingOn` argument is true the categories are enabled, else disabled. The function only has effect if the `loggingOn` argument of the `fmi2Instantiate` function was true, which initially enables all LogCategories."

That's my guess of the intended semantics. Other guesses are possible :-)

**Comment by pmai** [comment]
I think the wording is fairly clear already that loggingOn is used to toggle overall logging on or off, independent of the categories being provided (i.e. if you provide loggingOn=false, no logging will occur, regardless of what you provide in terms of categories):

> If loggingOn=fmi2True, debug logging is enabled, otherwise it is switched off.
If loggingOn=fmi2True and nCategories > 0, then only debug messages according to
the categories argument shall be printed via the logger function. Vector categories has
nCategories elements. The allowed values of categories are defined by the modeling
environment that generated the FMU. Depending on the generating modeling environment,
none, some or all allowed values for categories for this FMU are defined in the
modelDescription.xml file via element “fmiModelDescription.LogCategories”, see
section 0.

I think the only thing that should be made cleares is what happens if loggingOn=fmi2True and nCategories = 0, which I think was intended to mean enable logging for all categories that the FMU understands (which might or might not be all included in the LogCategories of the model description, as the text already clarifies).

So I'd propose the following minimal sentence addition as the second sentence in the paragraph:

> If loggingOn=fmi2True and nCategories = 0, then all debug messages shall be output.

In order to make this whole paragraph slightly cleaner from a language perspective, I would make the whole paragraph look like this:

> The function controls debug logging that is output via the logger function callback.
> If loggingOn=fmi2True, debug logging is enabled, otherwise it is switched off. 
If loggingOn=fmi2True and nCategories = 0, then all debug messages shall be output. If loggingOn=fmi2True and nCategories > 0, then only debug messages according to
the categories argument shall be output. Vector categories has
nCategories elements. The allowed values of categories are defined by the modeling
environment that generated the FMU. Depending on the generating modeling environment,
none, some or all allowed values for categories for this FMU are defined in the
modelDescription.xml file via element “fmiModelDescription.LogCategories”, see
section 0.

**Comment by nickbattle** [comment]
@pmai Your interpretation is consistent with the implementation in the fmusdk.

My concern with this is that it is slightly awkward to disable just one category. I think that you would have to disable everything, and then re-enable the categories that were previously enabled (which you have to know somehow), less the one you want disabled.

But it's hardly critical. If there are other implementations like fmusdk, I agree your re-wording clarifies their behaviour.

**Comment by pmai** [comment]
@nickbattle You just have to enable logging again with the new set of categories you want, no need to disable it beforehand. The whole point of the interface is to leave the burden of maintaining delta-state on the caller, not the FMU (that only needs to keep the set state, not do delta updates).

I can imagine nicer interfaces, but for 2.0.1 we can only clarify, not change the semantics...

**Comment by chrbertsch** [comment]
I will include @pmai 's proposal (agreed by @andreas-junghanns  by  👍 in RC3

> The function controls debug logging that is output via the logger function callback.
> If loggingOn=fmi2True, debug logging is enabled, otherwise it is switched off.
> If loggingOn=fmi2True and nCategories = 0, then all debug messages shall be output. If loggingOn=fmi2True and nCategories > 0, then only debug messages according to
> the categories argument shall be output. Vector categories has
> nCategories elements. The allowed values of categories are defined by the modeling
> environment that generated the FMU. Depending on the generating modeling environment,
> none, some or all allowed values for categories for this FMU are defined in the
> modelDescription.xml file via element “fmiModelDescription.LogCategories”, see
> section 0.

#623 to mention it there

@nickbattle : if you have a better proposal for FMI 3.0 please open an new ticket.
