### ISSUE TITLE
Unnecessary restriction related to fmi2Discard

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#630]
_Originally posted by @CThuleHansen in https://github.com/modelica/fmi-standard/issues/623#issuecomment-534261589_

**PLEASE comment on this - this is very late for inclusion in FMI 2.0.1**

Unnecessary restriction related to `fmi2Discard`: Figure 12 on p. 107 shows that `fmi2Discard` leads to `stepFailed`. In order to continue simulation from this point, it is necessary to `fmi2reset` of `fmi2SetFMUState` according to table on p. 109. However, it is stated on p. 105: `fmi2Discard – if the slave computed successfully only a subinterval of the communication`

Why is the computed subinterval not valid - in other words, why does it require a reset or setstate in order to continue? Perhaps the restriction can be lifted and the computed subinterval made valid?

**Comment by chrbertsch** [comment]
@pmai : Could you please comment? Thanks.

**Comment by pmai** [comment]
I'm probably the wrong person to comment on the original intent; however the API is designed to allow an FMU to try to integrate in multiple steps to the next communication point and when it fails to proceed to return as is, without first having to roll back to the original state (which would mean saving it in the first place). Since the co-simulation API in 2.0 does not provide for a way to return "early" in a defined way (i.e. returning the current time to which it integrated), this is the only plausible course of action.

I think the use of the word "successfully" is very slightly misleading in this context, 'cause while it's true, the whole operation was not successful.

**Comment by CThuleHansen** [comment]
@pmai I might misunderstood your comment, but an FMU 2.0 does provide a way to return how much of the step it progressed - fmi2LastSuccessfulTime (related to your comment on returning the current time to which it integrated). 

A scenario came to mind that might serve as a use case for lifting the restriction. A scenario consisting of a DE fmu and a CT fmu. The DE fmu is stepped first, as its step sizes varies based on events. The CT fmu probably just have a maximum step size, and can perform any steps smaller than that. 

Furthermore, I have come across DE FMUs that are difficult to roll-back due to scheduling of threads and similar.

**Comment by chrbertsch** [comment]
discussed with @pmai and @TorstenBlochwitz won't fix for 2.0.1: cannot change in a compatible way with 2.0.1
Check for 3.0

**Comment by chrbertsch** [comment]
Regular FMI Design Webmeeting: 

Pierre: is this issue still there in 3.0 with the early return?

**Comment by chrbertsch** [comment]
@CThuleHansen: is your concern still valid with the current state of the FMI 3.0 draft?
Could you then please provide a concrete proposal?

**Comment by CThuleHansen** [comment]
I will check it after the restructuring.

**Comment by CThuleHansen** [comment]
Actually, FMI 3 lifts the restriction. It is no longer required to perform a rollback. 
However, the description is phrased in different ways in different places. I will create a pull-request after the restructuring that phrases it in a similar fashion.

**Comment by andreas-junghanns** [comment]
In #972 we redefined fmi3Discard. All descriptions are now in one place.
If you find another issue, please reopen this issue here.
