### ISSUE TITLE
NAN, +INF, -INF, MaxDouble, MinDouble, MaxInteger, MinInteger, etc

### ISSUE THREAD

**Issue by jph-tavella** [modelica/fmi-standard#644]
In FMI 2.0, it is stated the following sentence in page 29:
 "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files."
But there is no more mention about the use of these special values in the API that is generated in the FMU. These special values are in different libraries depending on different systems and from different languages (C++, Java, Python, ...) and the terminology of these symbols is not unified. For instance, NaN symbol is textually expressed in Java as NaN and in C++ as nan. Generally speaking, NaN can be textually expressed in different manners and differently codified between languages too.

So there should be a higher specification in this sense. Here are some questions that we thing should be answered:
1.	Are these special values to be used in the API?
2.	If so, what would be the convention? What is the convention in text? What is the convention in codification?
3.	If so, what happens with other special values like MaxDouble, MinDouble, MaxInteger, MinInteger?
4.	If so, why is not it possible to use them in XML? We think it should be possible to use them also in the XML IN CASE it is to be used in the API.
Our understanding according to the sentence in page 29 of the previous FMI 2.0 specification is that the spirit of the standard is to avoid the use of the special values. We are on the same line and we think that it should be also mentioned that these symbols should not be used in the API.

**Comment by chrbertsch** [comment]
Regular Design Meeting: 

Can someone explain where the restriction in FMI 2.0 came from?
> "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files."

**Comment by andreas-junghanns** [comment]
> 
> 
> Regular Design Meeting:
> 
> Can someone explain where the restriction in FMI 2.0 came from?
> 
> > "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files."

If I remember correctly: Parsing these back into floating point number formats is not standardized. So we cannot assume that a scanf-like parser knows how to translate this into the proper double representation, for instance.

**Comment by t-sommer** [comment]
> Parsing these back into floating point number formats is not standardized.

The bit-representation is well defined by [IEEE 745](https://en.wikipedia.org/wiki/IEEE_754). You could e.g. add an if-clause for these 3 special values.

**Comment by jph-tavella** [comment]
To answer Christian, the restriction comes from a comment done on Feb 17th 2013 as a final answer to the issue #115 titled "Clarification of xs:double special values".
This issue is closed and was reported by Andreas Nicolai on Dec 2012.
For me this clarification is helpful but not suffisant.

**Comment by andreas-junghanns** [comment]
Even the old ticket/discussion did not report the point of the discussion that decided the issue then:
The textual representations of NAN and +-inf is as varied as C standard libs and other languages. We would have to define exactly which NAN we mean with NAN (IEEE 745 has several NANs and if you really want to represent them all to get the exact same bit representation back we would have to solve quite a hard problem; similar, albeit not as complicated: +-INF. 
Second part of the discussion was, that infinity is useless for float computation anyway, MAXDOUBLE and MAXFLOAT in numeric representation is just as good and this we decided not to bother with special non-numeric representations.

**Comment by jph-tavella** [comment]
I agree, the representations of NAN and +-INF are as varied as C standard libs and other languages. 
For this reason my proposal is very simple:
- keep the sentence: "The special values NAN, +INF, -INF for variables values are not allowed in the FMI XML files."
- add a complementary sentence: "The special values NAN, +INF, -INF for variables values are not allowed in the APIs of FMUs."
This proposal is simple and in conformance with the spirit of the standard that is to avoid the use of these special values.

**Comment by pmai** [comment]
While there are some pragmatic reasons for not allowing the special values in the XML representation (where they'd only be used as initial default values or values of constants, so that the restriction is not of much relevance), I see no proper reasons for disallowing them in the C API, where they'd (for all practical purposes) be specified very clearly in IEEE754. Should we disallow denormals at the API level as well? Specify our own floating point arithmetic, to supplant IEEE754?

What are we guarding against here? If code dealing with IEEE754 floating point code is written without proper handling of all of IEEE754, then just disallowing special values is not going to make it any better, just differently wrong.

Unless someone can point to specific problems that this would help solve, I do not see the need to change anything here.

PS: I'd strongly urge any implementations to never rely on C stdlib functionality for reading/writing FP numbers, since many of those are completely broken in the IEEE754 sense, and there are completely correct, efficient and user-friendly alternatives around...

**Comment by jph-tavella** [comment]
Following the origin of my thread I think we should go through the idea of:
1) Either allowing these symbols both in XML and API
2) Or disallowing these symbols both in XML and API

It does not make any sense to allow in one place and not in another. For that we can use the standard but in any case, the specification should indicate which are the symbols allowed in the XML files. In case we allow these values, other special values should be regulated: if they are valid for API they should be also expressed in the XML.

**Comment by andreas-junghanns** [comment]
The difference between C-API and XML is, that in the C-API IEEE 754 gives us a proper representation and all (reasonable) tools agree.
For XML, this is NOT the case and would require effort. And for what: What value would you set in the XML to +-INF or NAN?

**Comment by pmai** [comment]
Just so that we are clear: There are no symbols in the API. There are only "numbers" representable as fmi3Real32/64, which for most platforms will mean IEEE754 (for some of the eFMI stuff it will mean subtly broken variants of IEEE754 that tumble out of the design departments of embedded FPU artists, where getting the wrong value for a bit of gain in transistor counts is still de-rigeur, though hard to actually make a case for nowadays, and those cores will die out any time soon).

The representable "numbers" under IEEE754 do include +/-0, +/-inf, many signalling and non-signalling NaNs, denormals and the normals.

For XML there is the lexical representation of xs:double / xs:float, which does include precisely specified representations "INF", "-INF" and "NaN", as well as allowing "-0" and obvious representations for normals and denormals.  Note that this does not allow the distinction between signalling vs. non-signalling NaN, nor does it allow the many distinct NaNs to be represented. For negative 0 this can be represented in the lexcial representation, however the remaining wording of the standard makes clear that for XML schema internal purposes there is only one 0.

So in case one wanted to change the status quo, I definitely think that removing the restriction in the XML side is the way to go, because the XML specification itself is quite precise, it's just that if you use unsuitable tools (like scanf/printf) to do XML float parsing/printing (or any float parsing/printing at all ;), you can run into trouble.

I personally do not see a pressing need to change the status quo. What I do see is a pressing need not to restrict proper IEEE754 usage in numeric code.

**Comment by jph-tavella** [comment]
I agree with Pierre: we can remove the restriction in the XML side, if the XML specification itself is enough precise.
If not, we can (small effort) explicitly define the string "NaN" which should be interpreted as NaN in the programming language. The same for +INF and -INF.

**Comment by beutlich** [comment]
Cross-reference to Modelica language: https://github.com/modelica/ModelicaSpecification/issues/2048

**Comment by jph-tavella** [comment]
My reason is Simply consistency. It is not consistent to be able to set a value (e.g. NaN) for a real via API that cannot be set via XML. My proposal is not arguing that we need these values, it is arguing that API and XML should be consistent (either if you allow or not allow these values). I'm just pointing out this weakness of the standard.
One option or the other is satisfying for me.

**Comment by chrbertsch** [comment]
Regular FMI Design Webmeeting: 

Pierre:
- either do nothing at all (we cannot prohibit them in the C-API)
- allow NaN etc. in the XML (previously the reasoning to forbid them was that there are different representations; but the XML schema speficies them)

Masoud: would we allow inf in the parameters?
Pierre: for persistency sake yes.
Pierre: But there does not seem a practical need for this feature
Masoud: not all compilers support.
Pierre: But IEEE demands it, other chips are dying out.
Christian: Perhaps some tools cannot take care of e.g. inf values, e.g. for masks

--> Discuss at next F2F meeting

**Comment by chrbertsch** [comment]
FMI Design Meeting: 

Torsten S: One could use Inf for End time
Klaus:  Could we list the use cases for these numbers?
- undefined end time
Andreas J: For +/- Inf it is easy. NaN is the problem
Masoud one could have start value of a variable of Inf.
Klaus: In Simulink you can have Inf as a value for end times
Andreas J: When you print a number, they get formatted differently.
Andreas J: Is Inf defined in XML?
Torsten, Markus: Yes
Andreas J: is the standard C scanf able to read this?
Torsten S: One should use a suitable  XML parser
Andreas J: We should allow everything
Klaus: We are a standardization committee. We can make reasonable restricitions. otherwise the problems will come on our table
Leo: The ticket was about the inconsistency between XML and C-API
Masoud: I am asking for support of Inf.
Masoud: We could use NaN for undefined values
Torsten S: We could allow everything that is allowed in C
Torsten B: In modelica/ModelicaSpecification#2048  one proposes to use NaN as "not assign"
Markus: In IEEE NaN means "a value that does not exist" e.g. 1/0
Torsten B: The semantics could be defined the FMU, not in the standard
Klaus: What would the compliance checker would have to do with this?
Andreas J: Perhaps this should fail.
Klaus: My expectation would that we have to define what behaviour is to be expected. NaN is something else than "undefined".
Torsten B., Andreas J, : Does not have to be defined.
Andreas J: From an integration tool  point of view: E.g. having a start value of an input "NaN".
Klaus: this is the same as making the start value optional
Andreas: We should not care. C and XML are standardizing this.
Klaus: At least we have to define the meaning at some places. E.g. NaN for end time
Torsten S: Comparisons with NaN  is always False
Torsten B: For issues that we now in advance we can define the behaviour.
Klaus: What do we have if we have NaN for a state variable


Poll: Shall we allow NaN, +INF, -INF in the modeldescription.xml?
Yes:4
No:1
Abstain: 5

We shall go through the text and see if we have to modify the text (or include warnings.)
- startTime, StopTime, Tolerance, StepSize, Nominal, Min, Max, this 
- start value: is up to the FMU

@t-sommer : I will create a PR

**Comment by andreas-junghanns** [comment]
@t-sommer : Can you create a PR for this, please?

**Comment by masoud-najafi** [comment]
"The special values NaN, +INF, -INF for variables values are not allowed in the FMI XML files."
is still present in the standard. A PR may be needed.

**Comment by andreas-junghanns** [comment]
@t-sommer : you are on vacation, bored, lots of time... for a PR?

**Comment by masoud-najafi** [comment]
I just checked the text, these values have been mentioned only once. I can do the PR, if you would like.

**Comment by andreas-junghanns** [comment]
> 
> 
> I just checked the text, these values have been mentioned only once. I can do the PR, if you would like.

Yes, please!
