### ISSUE TITLE
Update type names in documentation, schema and examples

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#669]
The old FMI 2.0 type names (e.g. "Real" and "Integer") still appear in the documentation, XSDs and code examples. They should be update to match the new definitions in `fmi3PlatformTypes.h`.

I suggest to use `fmi3Float*` and `fmi3Int*` instead of `fmi3Real` and `fmi3Integer` to reflect the added 32-bit and signed / unsigned integer types.

**Comment by chrbertsch** [comment]
We shall not close this ticket when merging PR 799 as there are still open points, e.g.
-    table entries: there is a lot more that needs fixing in the tables and it is not enough to set {VariableType} here as entries are different for floating point and integer types 

![grafik](https://user-images.githubusercontent.com/16363372/75172698-f3951500-572d-11ea-8d86-664b2bf0177c.png)

-  pseudo code in SES: This is for AndreasP to fix and should not go into this PR

**Comment by andreas-junghanns** [comment]
These are different issues with a different focus, I think.
The tables need a general makeover.
The pseudo-code needs more than a quick fix and other issues need to be fixed there too.
Therefore: In the general text, all is done.
Any other issue goes to other tickets, if not already open (table fixes should already be listed).
Therefore, I strongly suggest to close this so that we do not get lost in endless ticket descriptions (rather open a new ticket with a reference to here but a full description of the remaining issues there)

**Comment by chrbertsch** [comment]
Closing as #799 was merged
