### ISSUE TITLE
Modeldescription - main source of truth?

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#678]
Hi,

What should be considered the “most truthful” definition of the structure of the model description for fmi 3 at this point - The test fmus, the actual written standard or the xsd schemas? Or is it both xsd and written part (such that these should be in sync) or some other combination?

Cheers

**Comment by nickbattle** [comment]
I agree this is important to clarify. Currently there are differences between the different sources. For example, comparing the CATIA test FMUs, HTML, docs/examples and XSDs:

The Test FMUs have SourceFile within ModelExchange/CoSimulation; the HTML and XSD describes SourceFileSets within BuildConfiguration.

The Test FMUs have ModelVariables with element names like "Int16"; the HTML agrees, but the XSD seems to define "fmi3Int16" etc, though the TypeDefinitions in the XSD are called "Int16" etc.

One example in the HTML has ModelStructure entries that have "Output" as an element name, the other has "Outputs" and "Unknown" subentries, like 2.0. The XSD has "Output"; the Test FMUs have the 2.0 style.

Many of the XMLSpy diagrams in the HMTL have yet to be changed, so for example the ModelVariables diagram still shows ScalarVariable elements, even though the XSDs are updated.

One of the example files (co_simulation_early_return.xml, under docs/examples) has "Variable" tags for ModelVariables with "Int16" subelements.

All very confusing!

**Comment by pmai** [comment]
FWIW my 2cents on this: The Test FMUs will never be normative, they are going to be examples, and will be fixed if they disagree with the normative reference. In the end I would expect that either only the specification is considered normative, or a combination of spec and schema.

For now I would consider the schema as the master of all truth, given that this evolves quickly, whereas spec and examples are likely to lag, due to the effort to maintain them.

One side-note: I do not see that the schema has a discrepancy in the element names for variable types: Only the internal complexTypes are called fmi3Int16, etc., the XML element names are Int16, matching the TestFMUs.

BTW: PRs for updating the test FMUs and/or spec to match the schema are likely welcome... ;).

**Comment by chrbertsch** [comment]
Currently you look at an unreleased alpha status of FMI 3.0

The Test FMUs are by no means normative.  It is great that Dassault Systems started this effort for prototyping FMI 3.0 and providing them to the community, but they might  have to be updated. 
In a future version of the Test FMUs it is planned to modify and review them to be "reference FMUs" fully compliant with the coming FMI 3.0 standard in order to test importing tools.
In order to (legally) simplify Pull Requests to the Test FMUs, there is already a (private) fork of them on https://github.com/modelica/Test-FMUs.

IMHO the XSD files (but not comments included there) and the standard text will be normative in the coming released version for FMI 3.0. We have to clearly write this down within the specification.

As Pierre pointed out, the XSDs are in the current alpha-phase more up-to-date and should be trusted more than the specification in case of inconsistencies ... please open issues and/or PRs in this case.

**Comment by nickbattle** [comment]
> One side-note: I do not see that the schema has a discrepancy in the element names for variable types: Only the internal complexTypes are called fmi3Int16, etc., the XML element names are Int16, matching the TestFMUs.

Ah yes! My mistake. Thanks for that.

**Comment by t-sommer** [comment]
> The Test FMUs have SourceFile within ModelExchange/CoSimulation; the HTML and XSD describes SourceFileSets within BuildConfiguration.

In the last FMI Steering Committee Meeting we decided to tag every release (from now on) whenever the API or schema changes. Prototypes can then indicate compliance with the corresponding `fmiVersion` attribute:

```xml
<fmiModelDescription fmiVersion="3.0-alpha.2" modelName="BouncingBall" ...>
```

**Comment by CThuleHansen** [comment]
Thank you very much for the fast response!

**Comment by t-sommer** [comment]
@CThuleHansen, since you brought this up, can you make a PR?

**Comment by CThuleHansen** [comment]
@t-sommer a PR for what part? The issues that we uncover related to standard and schema?

**Comment by chrbertsch** [comment]
Regular design meeting
