### ISSUE TITLE
StopTime in fmi3SetupExperiment

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#680]
The signature of fmi3SetupExperiment in FMI-2.0 and FMI-3.0 is :

fmi3Status fmi3SetupExperiment(fmi3Instance instance, fmi3Boolean toleranceDefined, fmi3Float64 tolerance, fmi3Float64 startTime, fmi3Boolean stopTimeDefined, fmi3Float64 stopTime);

StopTime and stopTimeDefined may be provided by the environment. If stopTimeDefined=TRUE, stopTime indicates the time beyond which the environment should (will) not call the FMU. According to the spec, if the environment tries to call the FMU beyond stopTime, the FMU raises an error.

I do not know if this definition is really useful or not. Because, first: the FMU cannot rely on the presence of stopTime to use it or not. One importer may provide stopTime and another environment may not provide it. All the FMU can do with current stopTime and stopTimeDefined is just a check to raise the above error.
Second: If there is a real limitation over the simulation time INSIDE the FMU, the FMU has no way to inform the environment over the internal limitation. All the FMU can do is just raise a Discard or an Error when the requested time by the environment is beyond its internal limit. 

What I propose is to change the signature of fmi3SetupExperiment to allow the FMU inform the environment if there is limit over the independent variable (time). This allows the importer adjust the simulation time to avoid possible errors. Here is new signature:

fmi3Status fmi3SetupExperiment(fmi3Instance instance, fmi3Boolean toleranceDefined, fmi3Float64 tolerance, fmi3Float64 startTime, fmi3Boolean *stopTimeDefined, fmi3Float64 *stopTime);

Thanks
Masoud

**Comment by chrbertsch** [comment]
Design Webmeeting: 

Klaus: there are different usages currently. In the past we struggled with such FMUs.
Torsten: It can make sense, e.g. to reserve memory.
Masoud: there is currently no way for an FMU to inform the master that it needs a stop-time.
Torsten:  Why is fmi3Boolean *stopTimeDefined a pointer? Why can it not be in the XML?
Masoud: It might depend on parameters
Torsten: is this not too complicated?
Klaus: We have to distinguish different cases:
- Master must be able to tell the FMU that it cannot provide a stop time
- FMU must be able to express that it needs stop time (in the XML or by raising an error?
- Stop time in defaultExperiment: what does it mean? There have come several questions by customers  (perhaps needs clarification)

Otto: We can already define a stop-time if we know it.
Torsten: this is the expected stop time. e.g. in case of error, it could stop earlier.
Masoud: the FMU might be defined for a specific time span.
Klaus: The FMU could return an error, or send the terminate state.
Christian: Currently one cannot set a hard stop time
Torsten: One can send an error if the time goes beyond. Or put it into the XML
Klaus: but it could depend on parameters

Klaus: there is fmi2discard
Masoud: but not in ME, only in CS
Klaus: that is an argument that something needs tobe changed to terminate in a good way.

Otto: If we need this, do we not have to add a new API function instead of calling the functions 2 times?
Mousoud: one does not have to call it twice
Klaus: It might be the case to call it twice, e.g. if you have two FMUs with different end times.

Torsten: I do currently not yet see the need for this change. The FMU can just return an error.
Please come up with a use case that shows that we need this really.

**Comment by chrbertsch** [comment]
Regular design meeting: 

Andreas P: Why do we need a stop time in the XML?
Torsten S: Imagine you get an FMU without other information. Having a default  is very helpful.

Andreas: we have to distinguish between a default stop time and the end of validity:

Torsten: We have to distinguish between 3 issues as listed above

Solution for 1.: StoptimeDefined = false (is this solved already? Andreas P.: was fixed in FMI 2.0.1 --> spend a sentence what it means)                
Solution for 2:  Raise an error. 
allow inf in the XML,  and return an error if the environment wants to simulate beyond 

...

Proposal: in the XML to provide an optional  maximal stop time to the XML (no dynamical stop time)
In the case of dynamical changing end times, one can raise an error.
Alternative: rely on error codes  at SetUpExperiment

Andreas: we must explain this carefully, explain the relation to the stop time in the default experiment.

If the FMU needs a stopTime, it can raise an error if it does not get one.

Klaus: We do not have "endTimeReached" in ME w/o an error.

Torsten S: one could use Discard in SetTime. We could unify these functions. @t-sommer : will create a new ticket for this

Conclusion:  Close this ticket, rely on error messages. If someone needs clarification, open a PR.

**Comment by chrbertsch** [comment]
Regular design meeting: 

Andreas P: Why do we need a stop time in the XML?
Torsten S: Imagine you get an FMU without other information. Having a default  is very helpful.

Andreas: we have to distinguish between a default stop time and the end of validity:

Torsten: We have to distinguish between 3 issues as listed above

Solution for 1.: StoptimeDefined = false (is this solved already? Andreas P.: was fixed in FMI 2.0.1 --> spend a sentence what it means)                
Solution for 2:  Raise an error. 
allow inf in the XML,  and return an error if the environment wants to simulate beyond 

...

Proposal: in the XML to provide an optional  maximal stop time to the XML (no dynamical stop time)
In the case of dynamical changing end times, one can raise an error.
Alternative: rely on error codes  at SetUpExperiment

Andreas: we must explain this carefully, explain the relation to the stop time in the default experiment.

If the FMU needs a stopTime, it can raise an error if it does not get one.

Klaus: We do not have "endTimeReached" in ME w/o an error.

Torsten S: one could use Discard in SetTime. We could unify these functions. @t-sommer : will create a new ticket for this

Conclusion:  Close this ticket, rely on error messages. If someone needs clarification, open a PR.
