### ISSUE TITLE
Harmonize state machines

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#683]
Currently we have five state machines that describe the allowed states and transitions for the different interface types:

- Model Exchange
- Co-Simulation
- Hybrid Co-Simulation
- Hybird Co-Simulation with Clocks
- Scheduled Execution Simulation

However the only difference between them is the way the time is advanced

- `fmi3SetTime` for ModelExchange
- `fmi3DoStep` for Co-Simulation, Hybrid Co-Simulation and Hybird Co-Simulation with Clocks
- `fmi3ActivateModelPartition` for Scheduled Execution Simulation

and which states can be entered / which functions may be called. The state diagram below is a first attempt to harmonize the state machines. It summarizes the discussions at the FMI Regular Design Meetings on [2019-11-08](https://github.com/modelica/fmi-design/tree/master/Meetings/2019-11-08-Regular-FMI-Design%20Webmeeting) and [2019-11-29](https://github.com/modelica/fmi-design/tree/master/Meetings/2019-11-29-Regular-FMI-Design-Webmeeting).

The goal is to improve the readability of the specification and simplify the implementation of FMUs and simulation masters that support more than one interface type.

![calling-sequence-unified-co-simulation (2)-Page-1](https://user-images.githubusercontent.com/2453858/70151081-60f35580-16ab-11ea-8ef6-da4e96f671fe.png)

**Comment by chrbertsch** [comment]
Regular Design Webmeeting: 

Question: Is there anything that can be done in ScheduledExecutionMode that cannot be done in HybridCoSimulation

Andreas P: Cannot say exactly. Perhaps the random activation at any point of time. I have to check this further.

Torsten: I found nothing,   but perhaps I ovrelooked something

Andreas P.: One has to check the scheduling

Torsten: All the infrastructure is already there in hybrid CS. Do we need a special mode?

Andreas  P: the master shall schedule the different partitions. This is not possible in Hybrid CS. One will run in problems, see my slides from 1-2 years a ago on a design meeting. In scheduled execution you can directly trigger tasks in the FMU.     

Torsten S: Could the scheduled execution be integrated in the unified state machine?

Andreas P.: I personally think yes, but the differences have to be documented.

Torsten S: is there anything that prevents us from using the same diagram for ME and CS? It looks almost the same. E.g. intermediate update mode just is not possible in ME.
The unification would be very helpful for implementers , especially if they support various kinds

Torsten S: Torsten B's main concern was not to loose time. But I think also with the different diagrams we will spend a lot of time anyway. In FMI 3, we bring features from ME to CS anyway.

Andreas J: How many states are affected for individual descriptions of the different states?

Andreas P., KLaus S: Step mode and possibly Step discaded are affected.

Andreas J: Would be very cool.

Torsten S: Different DLLs for different kinds could go away.

Andreas J: Let's just propose the changes, so that the changes become apparent.

Torsten S: It would be important to collect also criticism towards this issue. We could have a short write-fest. 

Andreas J: I am willing to contribute.

Andreas P.: When you make a propsal, I will include the scheduled execution.

Torsten S: For every FMU modes, we could have a "zoomed-in-" version of the diagram with also the self-transitions.

**Comment by chrbertsch** [comment]
FMI Regular Design WebMeeting:  closing in favor of #725 

@t-sommer : I will incorporate improvements form the statemachin above in the other statemachines
