### ISSUE TITLE
"Apostrophe" instead of "Right Single Quotation Mark" in EBNF

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#692]
According to the EBNF for variable names `Q-name` is surrounded by "Right Single Quotation Mark" (U+2019) but shouldn't this be an "Apostrophe" (U+0027) as in the example?

```
Q-name          = "’" ( Q-char | escape ) { Q-char | escape } "’"
```

Example (`docs/2_2_common_schema.adoc`):

```
robot.axis.'motor #234'
```

**Comment by nickbattle** [comment]
VDMCheck has interpreted the grammar as using an apostrophe here, as well as within the "escape" group (since you must be able to quote the apostrophe within the name).

The standard refers to the Modelica naming convention via ref [9] (though the link is broken?) - "This definition is identical to the syntax of an identifier in Modelica version 3.2." This should clarify the matter?

Also see https://github.com/modelica/fmi-standard/issues/612.

And the definition, "name = Unicode-char { Unicode-char } // identical to xs:normalizedString" isn't quite true, as I believe xs:normalizedStrings can be empty.

**Comment by t-sommer** [comment]
> This should clarify the matter?

In the [Modelica Specification](https://www.modelica.org/documents/ModelicaSpec33Revision1.pdf) (p. 255) it's clearly a "Right Single Quotation Mark", but I think it should be an "Apostrophe".

**Comment by nickbattle** [comment]
Ugh... well, I'd question whether it is "clearly" anything, but yes I agree it probably intended to indicate an apostrophe, otherwise the closing quote would probably be a Left Single Quotation Mark (and yet it's the same). Similarly the double-quote character `"\""` will be the simple ASCII character rather than the left or right versions.

**Comment by nickbattle** [comment]
Section 2.3.1 of the Modelica Specification does explicitly say that identifiers use a single quote. It then refers to Appendix B, which is not as explicit.

"The second form (Q-IDENT) starts with a single quote, followed by a sequence of any printable ASCII character, where single-quote must be preceded by backslash, and terminated by a single quote".

**Comment by t-sommer** [comment]
@nickbattle, can you approve #693, so we can resolve this?

**Comment by nickbattle** [comment]
@t-sommer, I'm not sure how I'd do that? Though informally, I agree that the changes look correct.

**Comment by t-sommer** [comment]
This is also relevant for `v2.0.2`

**Comment by chrbertsch** [comment]
@HansOlsson : could you please fix this in the Modelica Specfication? Thanks!

**Comment by HansOlsson** [comment]
> @HansOlsson : could you please fix this in the Modelica Specfication? Thanks!

As far as I can see that was due to Word-rendering of quotes and should already be corrected in 
https://specification.modelica.org/master/MLS.pdf https://specification.modelica.org/master/A2.html#lexical-conventions

**Comment by chrbertsch** [comment]
fixing in 2.0.2 word document with https://github.com/modelica/fmi-design/commit/cf591b2c2e17b7006190102d15ca053c8576c4b2
