### ISSUE TITLE
Revisit section on source code distrubution

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#699]
Is this still true/required with the new `BuildConfiguration` element?

> If default options of the compiler are sufficient, it might then be possible to automatically process such source code FMUs.
> An exporting tool should give documentation on how to build an executable, either via a documentation file and/or via a template makefile for a particular platform, from which a user can construct the makefile for his/her target platform.

**Comment by andreas-junghanns** [comment]
The idea of source code FMUs is to be as platform independent as possible.
We realise this is not entireley possible, but shipping platform dependent makefiles is as good as shipping platform binaries - what would be the point?
We want to ship code so that we can reach unknown platforms using unknown compilers, ideally.
Therefore, we should try to build as much flexibility into the standard as possible to define as much as needed, but not to require more.
Since the compile/link stuff is differently tricky on different platforms, this would benefit from a discussion in a group.

Note also: The long-term archival people are also tending towards source code FMUs. Their requirements make it even more obvious that we cannot know target platforms/compilers/linkers.
