### ISSUE TITLE
matchingRule of terminals

### ISSUE THREAD

**Issue by friedrichatgc** [modelica/fmi-standard#771]
The matchingRule of terminals defines the rules how the member variables inside of a terminal are matched. The according table in the document gives precise information about these rules.
However, later on the document states

> Tools which apply sequence based matching should also provide unique member names, so that all importing tools which use name based matching use the same member names.

What is the matchingRule: a definition how the matching must be done or is it just a recommendation and everyone is free do do something else (which may not be the intend of the exporter who defined the matchingRule)

**Comment by CSchulzeTLK** [comment]
There is the mentioned table with basic matchingRules. Others might be added by other standards. They are described in normative text.

This sentence you're citing was added to avoid that sequence based tools export FMUs without member name (so we finally made this attribute mandatory), and that these tools provide the same member name for several variables (so we made the member name unique). Both has been described in other places. So this is merely an information for the sequence based tool FMU exporters, that tools use these names for member variable matching. Maybe we can adapt the formulation to make this clear. Maybe remove.

**Comment by antvl** [comment]
I agree with Christian's remark.
The document distinguishes between normative text and non-normative text (written in italic between brackets).

The normative text states that:

> The member name has to be unique in a terminal.

And then there is the non-normative text that gives precisions about this statement:

> Tools which apply sequence based matching should also provide unique member names, so that all importing tools which use name based matching use the same member names.

This requirement about the uniquess of the member name does not change the matching rule any way.
If the sequence matching rule is required, it must be applied regardless of the member name, if the importing tool is able to do it.

As explained in the non-normative text, this is intended for importing tools that cannot perform sequence-based matching.

For me this is clear enough, I do not see the need to remove the paragraph.

**Comment by pmai** [comment]
I am not fully aware of the underlying issues, but just from a standard-writing standpoint:

The non-normative text cannot state that 

> tools ... _should_ also provide unique names

when the normative text already makes that a requirement.  At a minimum that text needs to be adapted to state that they _must_ do this, and state reasons for why that is a good idea (the rationale part).

But going further, it seems to me that this whole approach seems awfully dangerous: If the matchingRule states that sequence-based matching is to be performed, just requiring that the names are also unique does not lead name-based matching to yield the same results, unless I'm missing something. So suggesting that tools that do not support sequence-based matching should use the names for some form of name-based matching seems ill-advised. So at a minimum I'd say in case a matchingRule is not supported, it should not do _any_ matching, leaving it to the user to solve the problem in a same way.

I also don't see why this should even be allowed: If a tool puports to support this part of the standard, then it should be required to support the core set of matching rules.

Am I missing something here?

**Comment by antvl** [comment]
Pierre, you are right I would prefer a strict interpretation of the matching rules. However, there are always trade-off. The current situation about unique member names for tools that do not support sequence-based matching is the result of some trade-offs at the Renningen Design Meeting of June 2019 ... I do not recall who really needed these ajustments?

**Comment by andreas-junghanns** [comment]
If I remember correctly, we added name-based matching to support buses where here and there some elements might be missing. Since the vECU world needs bus support in FMI, name-based matching was added (at least this is what I remember because that is the only part I watched out for).

**Comment by CSchulzeTLK** [comment]
The word "should" dates back to a time where it was not required. We have to change that wording. I would also prefer to keep the paragraph.

Sequence based matching has been removed and re-added several times. Most recently we re-added it, because most participants were not aware that relevant tool (amesim) actually applies this method.

The variable member name attribute has been made mandatory (again) because we identified the problem that we need to identify min/max/nominal values of a specific alias - this section has to be adapted since we changed the alias information.

The member name has to be unique, because:
- It is not a big issue for the exporting sequence based tool to provide unique names (e.g. in the worst case out1/out2/out3...)
- Most of the involved FMI tools support name based member matching (yes, this is a reason)
- Sequence based matching always requires that you know the connected model. You don't expect reasonable results if you connect to an unkown model from an unkown tool which has a sequence based terminal - without further information (see next bullet point)
- Other standards can specify domain specific terminalKinds which define member names and their order. So only if this additional information is known, it is possible to know the "meaning" of the members, and apply a proper mapping.
- The requirement for busses in eFMUs Andreas mentioned


Actually we examined the 4 different use cases
1. Sequence based tool A exports -> sequence based tool B imports
2. Sequence based tool A exports -> name based tool C imports
3. Name based tool C exports -> sequence based tool A imports
4. Name based tool C exports -> name based tool D imports

The option to make the member names unique and mandatory was the "best". The main issue was, that sequence based tools have to generate arbitrary names. But as mentioned above in any case there has to be a more detailled information about the terminal with sequence based matching to enable an inter-tool exchange.
So one big advantage was, that the mandatory and unique member name at least solves the issues for the name based tools, and provides an optionally nice representation in those tools. Only the FMU exporting tool will be able to define a reasonable representation of the terminal in a name based tool. And if this is not defined, the FMI standard has to define how the sequence representation has to be mapped into name based tools to enable interchange between the name based tool C and D.

**Comment by pmai** [comment]
I don't want to relitigate whether to have different matchingRules, or what each should mean. I take those as decided.

My point is that if an FMU specifies a matchingRule in a Terminal, then that should be the rule that needs to be used to match stuff. If it says sequence based, then I expect the importing tool to use that, and not something else. If it cannot support a matchingRule, it should defer to the user of what to do more or less manually, not magically apply a different matching rule in the hopes that that somehow happens to work...

Nothing in the specification would ensure that applying name-based matching to a terminal with sequence-based matchingRule would somehow work. Name uniqueness is besides the point here: It would have to be ensured that two FMUs will always generate the same order of identical names. This cannot work.

So if I import an FMU with sequence-based matchingRule on a terminal, then I fully expect an FMU importing tool that claims to support the terminals and icons standard to do sequence-based matching. Otherwise I would not consider such a tool a conformant implementation of terminals and icons (the same for name-based matching rules, i.e. plug and bus, BTW). It would just be a partial implementation (the same as certain tools do not support string inputs and outputs on import: that's not a proper implementation of FMI).

**Comment by CSchulzeTLK** [comment]
Working Group Meeting on 03.04.2020 (@antvl , @friedrichatgc , @CSchulzeTLK ):

1. replace "should" with "must"
2. add non-normative-text:
An importing tool might fall back from sequence based matching to name based matching. This is possible because member name must be present. 
Sequence based tools could rely on the terminalKind, vendor annotations, and number of member variables, and ignore the member variable names. So the defined member variable names are merely a decription how to import the terminal in a name based tool.

**Comment by chrbertsch** [comment]
Regular design meeting

Pierre: I do not understand this

Christian: The sequence based tools additionally relies on the sequence ...

Pierre: Sequence based means as they appear in the connector. If I create a sequence based FMU, the names are not intended for name-based matching.

Christian S: the Sequence-based matching will always rely on additional information , e.g. a vendor annotation.  The addition is, that we define how a name-based tool can import it.

Pierre: I do not see this in the standard. There are no vendor annotations etc. mentioned. 

Antoine: ... this is not stated ....

Pierre: Should we than not prevent the importing tool from doing .....
In non-normative-text we tell something that might not work ....

Andreas: What does sequence-based matching mean? Taking only the order in the xml?

Christian S: When a name-based tool imports  ....

Pierre: We should not talk about "name-based tools" and "sequence-based tools". We should talk about supporting the FMI standard. The importing tool should do what the FMU expects.

Christian: this is an additional information. you check the terminal kind and this helps to connect it.

Andreas: perhaps this is a misunderstanding. What you call "sequence based matching" ....

....

Markus: we should remove the sentence that a sequence based must define names

Christian S:  then AMESim would not support it

...

Andreas: How can we support the connection of a sequence-based and a name-based matching

Christian S: you need additional information, given by TerminalKind

Markus: If .e.g, AMEsim exports Sequence based matching + defines the names by the TerminalKind, then this could work.

Andreas J: How could this work? What happens if these definition contradict? Wouldn't we get different results depending on the importing tools?

Christian S: these are domain-based definitions that  are defined in some other standard

Pierre: We should remove the matching rules and do everything in a layered standard

Christian S: We wanted to solve 90% of the cases with a matching rule

Pierre: ....

Christian S: The idea was to have a "compatibility mode"

Pierre: The importing tool should treat a sequence based  Terminal ... in a  sequence-based way.

Christian: the exporting tools should export names

Pierre: the names are not specified ....

Christian: ... this was the intention of the sentence we are discussing

Pierre: then it must be normative. But why do we have the matching rules then?

Andreas J: Trying to understand the intention of sequence based: Is this a simplification for tools that know a certain TerminalKind ...

Antoine: For sequence based matching: names do not have a meaning ...

Andreas J: Then you cannot fallback to name-based matching?

Chrstian S: You could define the terminal completely. We just define that the names are unique.

Christian B: We need an example

Antoine: E.g. a two-dimension mechanical port ... using an AMEsim convention

Christian S.: this will only work with a separate definition

Antoine: this is the same issue with the names.

Christian S: We want to have a layered standard defining certain  Terminals

Andreas J: could you please define 1-2 examples how this could work?

Markus: Could we skip one of the definitions "sequence based-matching" or "order-based matching"?

Christian S: You could put an additional constraint on the sequence in a layered standard.

Pierre: why not then moving everything in a layered standard?

Christian S: Because we want to have a minimal common ground.

Pierre: ... if we have rules in the layered standard ... a tool cannot do anything without looking into other standard 

Christian S: We could still have name-based matching and remove sequence-based matching.

Christian B: so we will have only name-based matching. And only with a vendor annotation or a layerd standard something like name-based matching can be used.

Christian: basically yes.

**Andreas: Please supply us with two example how the fallback mechanism could work. (Do not make it trivial)** 

Pierre: What is preventing for the name based-tools to implement sequence based tools and vice versa?

Christian: Could be a problematic for Modelica tools.

Antoine: We have a prototype with Modelon where they kept the order of the connectors

Pierre: please also show where the problem lies, e.g. in Modelica

Christian: We wanted to shift the burden to the exporting tool ....

Pierre: this is currently not the case.

Christian S: I will provide examples ...

**Comment by CSchulzeTLK** [comment]
I prepared a document to compare the different cases of FMU exchange between tools with different matching rules.

Basically only the exchange between name based tools works without an additional specification (which was considered as the most relevant use case). Export to sequence based tools with matching rule "plug" doesn't work. Everything else works, but with flaws in compatibility.

https://github.com/modelica/fmi-design/blob/master/WorkingGroups/01_Port_Icons/Meetings/2020-04-09-FMI_Web_Meeting/discussion.md

**Comment by andreas-junghanns** [comment]
@CSchulzeTLK or @antvl : Can you document the result of the working group meeting of April 2020 Design Meeting?

**Comment by chrbertsch** [comment]
Adding link to minutes of yesterdays working group meeting during Online Design meeting: 
https://github.com/modelica/fmi-design/blob/master/Meetings/2020-04-21-22-Online-FMI-Design-Meeting/minutesPortsAndIcons.adoc

**Comment by andreas-junghanns** [comment]
merged #919
