### ISSUE TITLE
Clarification of Early Return from Current Communication Step

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#797]
After a first read of section 4.1.2 Early Return from Current Communication Step, I think that the feature is useful! 
But there are a few issues with the way it is explained that prevents me from understanding it clearly.

Please define "multi-FMU architectures" or point to the corresponding definition.

Could you please add a legend to the figure, explaining that, 
- dashed green is the next planned communication time,
- black is the internal solution of the fmu,
- solid green is ? (at first I thought it meant the current internal solution of the FMU, but then FMU4 is not consistent with this.

Could you define what partial rollback means? The master will still have to restore the state. How is this different than the complete rollback from an operational point of view? I understand that the master did not have to way for the computation to end, but the rollback operation is still the same as the rollback of FMU2, that is, it's not cheaper. if I'm right, then please avoid the term "partial rollback" and just use "rollback".

The case for FMU4, while possible, seems to be improbable in practice. Therefore, I would guess that a sensible master will always rollback any FMU that has gone past the point of the event.

Does Fig 12 represent all possibilities?
I think there's a case missing, which is when there is an FMU that is even slower than FMU1, and the master needs to tell that FMU that he no longer needs to step until t_{i+1} but should instead step until t'_{i+1}. Correct?

**Comment by andreas-junghanns** [comment]
Similar comment to before: Do we want Early Return capabilities in Basic Co-Simulation?

**Comment by chrbertsch** [comment]
> Similar comment to before (in #820): Do we want Early Return capabilities in Basic Co-Simulation?

I moved this discussion regarding IVA and Early return (from #797, #820, #821) to #846.

**Comment by APillekeit** [comment]
@jph-tavella: could you please have a look?

**Comment by jph-tavella** [comment]
@clagms:
"multi-FMU architectures" means that several FMUs are executed in parallel on a multi-core or multi-machine environment. So they are all driven by the Master to integrate a step from ti to ti+1.
You can change the wording if you prefer something different for the same idea.

In my view the figure 12 is complete. Refering to the left part of the figure:
- dashed green is the next planned communication time ti+1 (the Master asks all FMUs to integrate from ti to ti+1).
- dashed red is the logical time t'i+1 <ti+1 of the first FMU event, assuming in the example this event time is detected by FMU1.
- solid green is the logical time where an FMU is aware of the first FMU event time (given by the Master).

I give you more explanations to understand my thoughts.

At first, there is no relationship between the computing time T and the different logical times ti, ti+1, t'i+1.
It is assumed in this example that the first event is detected during FMU1 integration, at computing time T.
So due to 'early return' FMU1 stops at its logical time t'i+1 <ti+1.
Then we have different cases for the other FMUs that are integrated in a parallel way during the same computing time T.
First possibility: an FMU reached its logical time ti+1 consuming a computing time less than T.
FMU2 is in this case. So to resynchronize FMU2 to its logical time t'i+1 <ti+1, the Master requires a rollback from ti to t'i+1.
I call this rollback a complete rollback (a usual rollback, a normal rollback).
Second possibility: during the computing time T, an FMU integrated to a logical time t with t<ti+1 and t>t'i+1.
FMU3 is in this case. The Master can stop immediately the FMU not waiting the end of the normal step integration but FMU3 is still to be resynchronized and the Master requires a rollback from ti to t'i+1.
I call this rollback a partial rollback. Probably this wording is clumsy as it is also a normal rollback for the FMU. But simply the rollback is anticipated by the Master (for global efficiency).
Last possibility: during the computing time T, an FMU integrated till a logical time t with t<t'i+1.
FMU4 is in this case. The Master can ask the FMU to go on its integration but with another time target which is t'i+1. No rollback will then be necessary. 

The right part of fig.12 is the result where all  FMUs have integrated to the same logical time t'i+1.

**Comment by APillekeit** [comment]
WG Meeting: comments have clarified the issue, solving and improving the issue should be done with issue #836.
