### ISSUE TITLE
Inconsistency in fmuResourceLocation and resources folder?

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#814]
The argument fmuResourceLocation in fmi3Instantiate is an URI, so it cannot be optional and the importer should provide a valid URI to the location of the resources directory of the unzipped FMU.
But, the "resources" directory is optional. So to what the URI should point to if the "resources" directory does not exist? Pointing to a non-existing folder may be dangerous.

**Comment by chrbertsch** [comment]
I propose to make the resource folder mandatory.

**Comment by chrbertsch** [comment]
I propose to make the resource folder mandatory.

**Comment by andreas-junghanns** [comment]
PR #833 merged.

**Comment by chrbertsch** [comment]
So there seems to be broad support to revert #833  and
- make the resource folder optional
- clearly describe to return a  NULL pointer, if the environment cannot provide the resource location 
-- either because there is no resource folder in the FMU
-- or because due to other reasons it cannot provide an URI to that location (e.g., because there is no filesystem)

(The importer can check in advance, if there is a resource location and provide a feedback to the user if it cannot handle it, and the FMU can raise an error if it gets returned a NULL but depends on information in the resources folder)

Any objections to following this path and creating a PR?

**Comment by andreas-junghanns** [comment]
No objections - will you create the PR?

**Comment by andreas-junghanns** [comment]
Should we continue the discussion in the open ticket #1020?
