### ISSUE TITLE
co-simulation, basic co-simulation, hybrid co-simulation, scheduled co-simulation

### ISSUE THREAD

**Issue by CThuleHansen** [modelica/fmi-standard#818]
There are 3 interfaces, but  4 different names. The names are
1. co-simulation
2. basic co-simulation
3. hybrid co-simulation
4. scheduled co-simulation.

For example, `canNotUseBasicCoSimulation` refer to a defined set of features and certain interface functions. In essence, Basic Co-Simulation has been in a fluctuating state between FMI for Co-Simulation, Co-Simulation and Basic Co-Simulation. 

From the restructuring we have the following:
1. co-simulation is the CONCEPT.
2. Basic co-simulation is related to the the same thing as the modeldescription `canNotUseBasicCoSimulation`, i.e. the functionality and interface similar to FMI2.
3. Hybrid Co-Simulation is related to HYBRID Co-SIMULATION
4. Scheduled Co-Simulation is related to Scheduled co-simulation

This ticket is created to ensure that a check will be made to ensure consistency.

**Comment by andreas-junghanns** [comment]
I started with a first pass to see what we need to use. Here is a suggestion slightly different to the first:

1. co-simulation: as the general concept
2. Co-Simulation (xCS): meaning all three Co-Simulation interfaces (that follow below)
3. Basic Co-Simulation (BCS)
4. Hybrid Co-Simulation (HCS)
5. Scheduled Co-Simulation (SCS)

We need 2. to have a good way to name all three FMI CS interface types - in many situations the text refers to all of them. I will create a PR with a first set of change proposal. Please check. Many places are still in need of fixing as descriptions for many things are still open.

I started this because we need to define a consistent way of using these terms.

**Comment by t-sommer** [comment]
`canNotUseBasicCoSimulation` is obsolete and has been removed from the schema.
