### ISSUE TITLE
Improve the integration of the early-return ("break step") feature in Basic Co-Simulation section 4

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard#820]
There are subsections separatly describing the early return feature in section 4 but the information should be either included in other subsections or the subsections should be moved to different places to match the overall structure.

**Comment by andreas-junghanns** [comment]
I seem to remember that we rejected making Basic Co-Simulation more complex because Hybrid Co-Simulation is the interface type to go to, if you need a more sophisticated co-simulation, the second is your choice.

The document structure should reflect this and describe common concepts only when they are used in multiple interface types.

So, do we allow advanced features like early return in Basic Co-Simulation?

**Comment by chrbertsch** [comment]
> So, do we allow advanced features like early return in Basic Co-Simulation?


I moved this discussion regarding IVA and Early return (from #797, #820, #821) to #836.

**Comment by APillekeit** [comment]
> So, do we allow advanced features like early return in Basic Co-Simulation?

The state of the discussion up to now was: Intermediate Variable Access is available for all Co-Simulation modes since it is a realtivly orthogonal to the simulation interface types. It can be turned on and off in each co-simulation interface type and the fundamental way of simulating the FMU would not change, only additional information can be transported.

**Comment by andreas-junghanns** [comment]
This was addressed in #972.
