### ISSUE TITLE
Description of the mechanics of start values for arrays is missing

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-standard#843]
As noted in the discussion of #838, as well as in interaction with outsiders, the documentation of start values currently does not explain how they are to be treated for arrays:

- Values are in row-major order
- What to do if the number of values does not match the initial size of the array

The specific case that start values are specified as elements rather than an attribute for string variables should also be mentioned.

**Comment by klausschuch** [comment]
The serialization of array values in the start attribute is currently mentioned in section "2.1.7 Getting and Setting Variable Values".

> Variables can be scalar or array variables. When getting or setting the values of array variables, the serialization of array variable values used in C-API function calls, as well as in the XML start attributes is defined as row major - i.e. dimension order from left to right for the C-API (e.g. array[dim1][dim2]…​[dimN]), and document order in the XML attributes. For this serialization of array variables the sparsity pattern of the array is not taken into account. All elements of the array, including structural zeros, are serialized.

This does not mention (and must be extended):
# special handling string array variables
# error handling or mismatching

I suggest to just reference this section in the description of the start attribute in "2.2.10 Definition of Model Variables (ModelVariables)"

Additionally, we specified in the array FCP that a short notation should be possible.
If only a scalar value is given, the all entries of the array have this value.
This is not mentioned in the specification at all yet.

**Comment by andreas-junghanns** [comment]
@klausschuch : you seem to have a plan: please prepare a PR

**Comment by clagms** [comment]
2020-04-30-Regular-FMI-Design-Meeting

AJ: No need for any further discussion here.

KS: do I need to write what happens when parameters are invalid.

AJ: Please check the fmi3error again. Is it enough to describe what happens when the arguments are invalid.

Conclusion: KS will prepare a PR that leaves error handling out. He will check whether fmi3error and other error codes description are clear.

**Comment by chrbertsch** [comment]
FMI Design meeting: @klausschuch I will create a PR today.

**Comment by chrbertsch** [comment]
@klausschuch :  Could you please provide a PR?

**Comment by klausschuch** [comment]
This issue was partly fixed with #1247. 
The representation of string start values in the modelDescription.xml are not described yet because the xsd was not clear yet.
The pull-request #1241 to fix the xsd for array start values got merged meanwhile.
Hence, a pull request for the description of this mechanism can be created.

**Comment by andreas-junghanns** [comment]
> Hence, a pull request for the description of this mechanism can be created...
... by you?

**Comment by andreas-junghanns** [comment]
@klausschuch : Ping.
