### ISSUE TITLE
Create release for v3.0-alpha.3

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#860]
@pmai, can you please look into this?

**Comment by andreas-junghanns** [comment]
Pierre: Any news here?

**Comment by chrbertsch** [comment]
Regular Design meeting: 
@pmai I will create a draft for the release notes
@ everyone : please add comments to this issue what shall be mentioned in the release notes.

**Comment by chrbertsch** [comment]
alpha.3 was tagged on March 22nd. 
Afterwards many changes came in (e.g. during the online design meeting, e.g. splitting the xml).
Shall we describe the changes for March 22nd? 
Or the changes to the current state? (Shall then the tag be changed (??) or a new tag alpha.4 be created?

**Comment by chrbertsch** [comment]
_@t-sommer  created a draft at https://github.com/modelica/fmi-standard/releases  I continue here, as changes in the draft do not seem to get versioned_

**Terminals and Icons, Hybrid Co-Simulation, BuildConfiguration, Extra Directory and AdjointDerivatives**

FMI3.0alpha3 includes the modifications of more than 100 merged pull requests compared to FMI3.0alpha2 (see https://github.com/modelica/fmi-standard/commits/master for detailed information). The main changes are: 

* `new` Add terminals and icons to schema and docs (#614)
* `new` Add Clocks & Hybrid Co-Simulation API (#615)
* `new` Move BuildConfiguration to fmiModelDescription (#611)
* `new` Add extra directory for metadata transport (#586)
* `new` Add fmi3GetAdjointDerivative to C-API (#722)
* `changed` Define event indicators in <ModelStructure> (#587, #842)
* `changed` Add <Alias> element to model variables (#807, #834)
* `changed` Add <{Basic|Hybrid|Scheduled}CoSimulation> elements to XML (#841)
* `changed` Inline structs and add separate instantiate functions (#667, #821)
* `changed` Remove "Fatal" state and derive all state machines from a template (#739)
* `changed` Add Hybrid Co-Simulation and Scheduled Execution Simulation to interface types (#728)
* `changed` Port changes from 2.0.1 (#674)
* `changed` Clarify access rules for variables, (#726)
* `changed` Pass direction of zero-crossing in fmi3EnterEventMode() (#663)
* `changed` Remove causalities "inferred" and "triggered" (#640)
* `changed` Change parameters of fmi3EnterEventMode() (#651)
* `changed` Pass reason for entering Event Mode to FMU (#619)
* `changed` Use "discrete" as default variability for non-Float variables (#604)
* `changed` Add enter/exitConfigurationMode functions (#599)

I removed 
* Use new FMI logo (#706)
* `changed` Use "Apostrophe" instead of "Right Single Quotation Mark" in EBNF (#693)

**Comment by chrbertsch** [comment]
Closed with https://github.com/modelica/fmi-standard/releases/tag/v3.0-alpha.3

**Comment by beutlich** [comment]
Any chance to attach the PDF as asset to https://github.com/modelica/fmi-standard/releases/tag/v3.0-alpha.3? Thanks.

**Comment by chrbertsch** [comment]
We could attach the html with pictures included (https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/html-manage-images.adoc)
And from Chrome one one can printout an acceptable PDF.

**Comment by andreas-junghanns** [comment]
We looked at the CI but they have already deleted the products.
We would have to add the html created locally (not so nice).
(This was my call when Torsten created the release. We will have alpha4 soon - hopefully end of this week.)

@beutlich : Is this just for consistency, or do you actually need it?

**Comment by beutlich** [comment]
Consistency it is in this case. Would be good to have the actual artifacts available. But if there is alpha.4 released soon, I can live with it.
