### ISSUE TITLE
Clocks with Dimension allowed?

### ISSUE THREAD

**Issue by IZacharias** [modelica/fmi-standard#889]
According to the schema, a clock variable can be an array and have several dimensions:
![image](https://user-images.githubusercontent.com/33029000/78892458-ae247100-7a69-11ea-9c0f-33aafc6c9070.png)

This must not be allowed for clock variables (or does anyone know of a reasonable use case for this?). So the dimension element must be removed from the clock element.

**Comment by t-sommer** [comment]
Currently the `<Dimension>` sequence is defined in the base class `fmi3VariableBase`. We could either state in the docs that this is not allowed or force it via the XSD.

**Comment by t-sommer** [comment]
@pmai, what do you think?

**Comment by andreas-junghanns** [comment]
If the schema does not get more complicated, I would prefer forcing this via XSD.

**Comment by chrbertsch** [comment]
Regular FMI Design meeting

Pierre: xsd-Schema-wise we cannot override it. 
Do we have a problem with the arrays?

Irina: I think so

Pierre: Are these variables or scalar variables?

Irina: for structural parameters we have restrictions.

Claudio: What does it mean for a clock to be active? Perhaps this is where the problem lies.

Pierre: Its just multiple clocks

Claudio: What do we do with event indicators in ME?

Torsten: this is unrelated. I would follow Pierres argumentation. Also in Modelica one can express arrays of clocks.

Pierre: I would even allow for structural parameters to be arrays.

Torsten S: What about the dependencies? What happens when the clocks are arrays.

Irina: It would not fit with the API to have arrays.

...

Torsten B.: In the wider sense a clock is like a variable

...

Pierre: for the setClock API this is similar to the setBoolean API. This should work for clocks.
What about dependencies?

Claudio: For an array of input clocks ...

Pierre: as for booleans one could set the components of a clock array to individual values
If we cannot treat clocks as variables, we should define them to be something else. We should not only fix the syntax.

Irina: We would remove the variables from the varibles and make them a different type.

Andreas: We would need  a special way to identify clocks. 

TorstenS: We could define base classes

Pierre: I would allow arrays of clocks.

Andreas J: We should answer: Why should clocks not be arrays?

Pierre: I would avoid special cases. Perhaps in the next release we need them as arrays.

Torsten S: What are is an array of clocks? you could set them only at the same time. The information is in value reference.

Pierre :The API must support activating only part of the clocks of an array

Torsten: The clocks have a double meaning for clocks and model partition

Pierre: The clock and its activation are two different things.

Torsten S: Its like FMI 1,2 and 3 for scalar variables.  We should change the API to allow setting arrays of clocks. 

Pierre: If we treat the clocks as variables.

Pierre: We can have restrictions on variables.

Torsten: Then we have consensus. We should change the API

Claudio: Suppose we have an output clock tick. How can we identify which clock ticked?

Torsten: there is a boolean "clockTicked" and you have to find it out on your own. 

Irina: how can we reference a particular clock?  We have only a VR for the array. How we know which clock of the array is meant?

Torsten S: ...

Pierre: for the dependency information we have it more fine granuarly.

Christian B: Do we agree to allow arrays of clocks?

Claudio: we should try this.

Andreas J: We have to check that this can be handled by an importer. 
I can imagine how an exporter can do this?

Pierre: Modelica has to solve this on both sides

Claudio: We could collect other aspects of this issue. 
- dependencies, value references ...

Andreas:  the discussion should focus on two alternatives: 

1.  forbid arrays of clocks in the text
2.  fix the API to allow array clocks. Then we have to argue why this makes sense

Torsten B: The reason that clocks can be arrays in Modelica is that like any other object  it can be an array.

Christian: If we would forbid arrays in FMI 3.0 could we introduce it later?

Torsten B: We would have to change the API then.

Torsten S: the setClock function could be used 

Claudio: The default plan would be to allow arrays of clocks

Andreas J: we could remove get and setClock and treat them as boolean

Torsten S: It has different meaning.

Andreas J: if setting and getting a clock is the same as  setting other variables, why do we need  a special API?

Pierre: currently the one clock maps to one partition.  Isn't setting the clock the same as activating the partition?

Torsten S: you then cannot provide the activation time

Torsten B: I checked the specification and we would have to change a large portion of it, if we allow for for arrays of clocks. I would not be against leaving the clocks as scalars, one could scalarize Modelica array clocks.

Torsten S: We could allow it but just not use it in combination with model partitions.

Pierre: We have to clarify the Documentation anyway. We could restrict the clocks to be scalar for now. (we could fix the API anyway to prepare for the future)

Torsten S: But how to treat the subactive? for what does it refer?

Torsten S: What is subactive used for anyway? Could someone explain this?

Andreas J: Who needs this?

Torsten B: When you read the description of fmiSetClock:
"It has no meaning for communication time clock"
... there is non-normative text that I do not understand ...

Andreas J: If we do not understand it, we shall remove it.

Pierre: we talk about changes of variables at the wrong places.
We need a ticket that says: either we fix the explanation or we must drop it.

**Andreas J: We need a ticket to clarify or remove "subactive". I will create this ticket.**

Torsten B: I checked again and it is not contradicting. I want to correct what I stated earlier?

Pierre: Does subactive apply only for synchronous clocks?

Claudio: Perhaps it is in order to force the evaluation of the output function.

Andreas J: We started the subactive discussion because the subactive is the only difference between the set and get Variables API and the set clocks API

Pierre: this can be easily be fixed. We could introduce the safety check with the nVariables.

Pierre: for the activate partition part, we would have to use indices.

Andreas J: We could also state that it activates the whole array of clocks.

Pierre: It is strange that one could activate individual clocks but not not individual.

Andreas: The exporter would know this.

Claudio: But why then have different clocks?

Andreas: We keep the concept general on the abstract level.

Pierre: we could use the same size_T argument as for the dependencies. This has also the a special semantics so that one could activate either all or individual clocks at a time. So it is doable. 

Andreas: Do we need this complication? 
We have a principle to keep simple.

Claudio: there is syntactic and semantic simplicity ...

Andreas: One can argue to have simplicity in the general usage of concepts

**Pierre: I can do a basic PR outlining the needed API and xml changes as a starting point for the discussion.**
