### ISSUE TITLE
clarify meaning and use of `subactive` or remove from standard

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#890]
The description of `subactive` requires improvement:
 - What is the meaning?
 - What is the use?

If we cannot find such clarifications, we should remove `subactive` from the standard.

(see discussion in https://github.com/modelica/fmi-standard/issues/889#issuecomment-611565112 )

**Comment by clagms** [comment]
I think I now understand what this means!

The difference between partial evaluation and full evaluation of a clock lies in the fact that the states are modified in the former.
However, it is left implicit (or at least the sentence "Partial evaluation for a subactive clock: states are left unmodified" is not explicit enough) that function $f_j( x_{j-1} , u_j, t_j )$ is computed in both cases.
Now the non normative text "This mode can also be requested by the calling environment with..." starts to make sense, since one could set different inputs in between two partial evaluations, to get an approximation of the derivative of the state with respect to the input.

Does this make sense?

I still don't understand how/why modelica uses this as first tick, since I would expect the first tick to compute x_0 from x_start. But to actually record the value of x_0 a full evaluation is needed. Unless there's some kind of fixed point iteration that involves x_0... If that is the case, this definitely must be clarified.

**Comment by KarlWernersson** [comment]
Hi
It is correct how you understand it Claudio
You can see this quite simple in the first equation in section, 2.1.8.1.1 Synchronous clocks. and the subsequent explanation

**Comment by chrbertsch** [comment]
@KarlWernersson  and others: can we discuss/clarify this at the design meeting?

**Comment by chrbertsch** [comment]
I still do not get the meaning of "subactive". I even do not understand the English word ... Is subactive=passsive?

Synchronous clocks are only relevant for ME.
Why not evaluate outputs that depend on the discrete time states (that can change when the clock is active) just with an fmi3getXXX call? Is it forbidden to to access discrete time states associated with a clock from such an fmi3getXXX call? If yes: why, and where can I find this?

Shouldn't we use the meaning of a "clocked variable"  from the Modelica Speficiation
![grafik](https://user-images.githubusercontent.com/16363372/82726182-91bf5980-9ce2-11ea-8a14-92ca407bbd7b.png)

 together with an implicit hold operater ( which has to be explicit in Modelica)?

![grafik](https://user-images.githubusercontent.com/16363372/82726215-c3d0bb80-9ce2-11ea-8e6f-c36cca1856ec.png)

**Comment by andreas-junghanns** [comment]
All to Karl: Please clarify the definition and use-case for "subactive".

**Comment by clagms** [comment]
# Results from working group on clocks.

The following can be solved in https://github.com/modelica/fmi-standard/pull/1060

>``If an <<inputClock>> has `fmi3True` as an <<start>> value the master should activate the <<clock>> the first time it enters *Event Mode*.``

- [ ] We need to clarify here that, for synchronous clocks, activate means that subactive argument is false.
In other words, a synchronous clock is activated when fmi3SetClock is called for that clock with value=fmi3ClockActive and subactive=fmi3False, right?
This is related to the following comment in https://github.com/modelica/fmi-standard/issues/1000
> * Which combinations with `values` are allowed for synchronous clocks? (Can `values[i]=fmi3ClockActive`  and `subactive[i]=fmi3True`??) Why not use the `values` array with a (not yet exsisting) value `fmi3ClockSubactive` for that purpose?

>(xml-attributes `shiftCounter` and `resolution` in <<clock-type-definition>>)

- [ ] Make the above into links
