### ISSUE TITLE
Update and add tables with mathematical descriptions

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#926]
We need to update the ME and BSC tables with the math descriptions and add for HCS and SCS.

The tables need to have a clear structure, e.g. sections that apply to a single state (not "before state").
The tables need to be enhanced w.r.t. clocks.
The tables need to be enhanced w.r.t. Intermediate Update.

**Comment by andreas-junghanns** [comment]
11:00 WebEx 3 (TorstenB will start it), Day 2 of April 2020 FMI Design Meeting

**Comment by TorstenBlochwitz** [comment]
Discussion during FMI-Design Meeting:

General Proposals:
1. In Co-Simulation the description of the states contain lists of allowed and forbidden function calls and some description. This should be combined with the table of mathmatical description.

Needs to be discussed:
- keep the list of forbidden function calls?
- keep the of "Allwed Function calls" below the state machines?

Proposals for Model Exchange:
1. Something went wrong when the FMI spec was tranformed to ADOC. The list of States in 3.1 was changed into sections. We propose to move the description of the states from below the state machine to section 4.1. The large table could be splitted and copied into the sections which describe each state.
2. Add mathematical definitions regarding clocks and clocked equations from FCP001: fmi-design/FMI_ChangeProposals/FCP_001_MultiRateSampledDataSystems/FMI_Proposal_MultiRateSampledDataSystems.docx
3. The row in Event Mode in which fmi3SetTime is allowod must be deleted, this transition was removed from the state machine.

Karl will do the new structuring (point 1 from above) by this week. Then we should meet again to refine and continue.

Proposals for Co-Simulation:
1. Basic Co-Simulation should be structured in the same way as Model Exchange is.
2. In case of Hybrid Co-Simulation, Event Mode and Clocked staff must be added
3. Intermediate Update Mode must be described

Proposals for Scheduled Co-Simulation:
1. Section is completely empty. Irina will start. Who else can contribute?

**Comment by TorstenBlochwitz** [comment]
Discussion during FMI-Design Meeting:

General Proposals:
1. In Co-Simulation the description of the states contain lists of allowed and forbidden function calls and some description. This should be combined with the table of mathmatical description.

Needs to be discussed:
- keep the list of forbidden function calls?
- keep the of "Allwed Function calls" below the state machines?

Proposals for Model Exchange:
1. Something went wrong when the FMI spec was tranformed to ADOC. The list of States in 3.1 was changed into sections. We propose to move the description of the states from below the state machine to section 4.1. The large table could be splitted and copied into the sections which describe each state.
2. Add mathematical definitions regarding clocks and clocked equations from FCP001: fmi-design/FMI_ChangeProposals/FCP_001_MultiRateSampledDataSystems/FMI_Proposal_MultiRateSampledDataSystems.docx
3. The row in Event Mode in which fmi3SetTime is allowod must be deleted, this transition was removed from the state machine.

Karl will do the new structuring (point 1 from above) by this week. Then we should meet again to refine and continue.

Proposals for Co-Simulation:
1. Basic Co-Simulation should be structured in the same way as Model Exchange is.
2. In case of Hybrid Co-Simulation, Event Mode and Clocked staff must be added
3. Intermediate Update Mode must be described

Proposals for Scheduled Co-Simulation:
1. Section is completely empty. Irina will start. Who else can contribute?

**Comment by TorstenBlochwitz** [comment]
Discussion during FMI-Design Meeting:

General Proposals:
1. In Co-Simulation the description of the states contain lists of allowed and forbidden function calls and some description. This should be combined with the table of mathmatical description.

Needs to be discussed:
- keep the list of forbidden function calls?
- keep the of "Allwed Function calls" below the state machines?

Proposals for Model Exchange:
1. Something went wrong when the FMI spec was tranformed to ADOC. The list of States in 3.1 was changed into sections. We propose to move the description of the states from below the state machine to section 4.1. The large table could be splitted and copied into the sections which describe each state.
2. Add mathematical definitions regarding clocks and clocked equations from FCP001: fmi-design/FMI_ChangeProposals/FCP_001_MultiRateSampledDataSystems/FMI_Proposal_MultiRateSampledDataSystems.docx
3. The row in Event Mode in which fmi3SetTime is allowod must be deleted, this transition was removed from the state machine.

Karl will do the new structuring (point 1 from above) by this week. Then we should meet again to refine and continue.

Proposals for Co-Simulation:
1. Basic Co-Simulation should be structured in the same way as Model Exchange is.
2. In case of Hybrid Co-Simulation, Event Mode and Clocked staff must be added
3. Intermediate Update Mode must be described

Proposals for Scheduled Co-Simulation:
1. Section is completely empty. Irina will start. Who else can contribute?

**Comment by clagms** [comment]
While going over the mathematical definition of ME, here are some minor issues.
We should improve these when reformulating the new definitions.


- [ ] What does the term "phase" mean? Maybe we should replace it with something that tells the reader about the scope of the claim made. Does it apply to the next sentence only? Or to the whole section?

```
In this phase latexmath:[t_I = 0].
```


- [ ] Typo: Extra parenthesis in equation:

```
At a predefined time instant latexmath:[t_i=(T_{next}(t_{i-1}, 0)]
```


- [ ] Also, ambiguity: I understand that the $T_{next}$ function is the one that computes the $t_i$. However, I don't get why that function takes $t_{i-1}$ and $0$ as arguments.  $t_i, t_{i-1} \in \mathbb{\text{T}}$, right? So what is the signature of $T_{next}$?


- [ ] In section `3.1.1. Basic definitions`, it would be nice to include an illustration that "exercises" the different definitions of the super-dense time concepts, to help the reader get the intuition for what they stand.

Something like the following figure:
![image](https://user-images.githubusercontent.com/871103/80087461-661e4780-855b-11ea-8046-42f345fa0f26.png)

where:

- The points $(2,0), (3,0), (3,1), (3,2), (3,3)$ are all members of set $\mathbb{\text{T}}$
- $v \in \mathbb{R}$
- $(2,0) < (3,1) < (3,2)$
- $(3,2)^+ = (3,0)^+ = (3,3)^+ = \lim_{\epsilon \to 0} (3+\epsilon,3)$
- $(3,2)^- = (3,3)^- = (3,0)^- = \lim_{\epsilon \to 0} (3-\epsilon,0)$
- $^{\bullet}(3,2) = (3,1)$
- $^{\bullet}(3,0) = (3,0)^-$
- $v((3,2)) = 10$
- $v((3,2)^-) = v((3,0)) = 9$
- $v((3,2)^+) = v((3,3)) = 11$


- [ ] Weird use of quotes in the following:

> An event latexmath:[t = t_i] occurs at the smallest time instant "min t" with latexmath:[t>t_{i-1}] where "latexmath:[(z_j(t)>0) \neq (z_j(t_{i-1}) >0)]"

Why not just write the latex math formulas?


- [ ] Get rid of the notion of independent and dependent parameters. There should only be the notion of "parameters" and "calculated parameters".

- [ ] In the following sentence, 

```
Given the previous values of the discrete-time <<state,`states`>>, latexmath:[{}^{\bullet}\mathbf{x}_d(t)], at the actual time instant latexmath:[t], all other discrete-time variables, especially the discrete <<state,`states`>> latexmath:[\mathbf{x}_d(t)], can be computed.
```

Are we sure that the value of each discrete time variable **only** depends on the values of the other discrete time variables? What about the continuous inputs and states?


- [ ] Typo in

`At initialization or at an event insant`


- [ ] In the following sentence, 

```
an FMU can define the next time instant latexmath:[T_{next}]
```

why don't we just use $t_{i+1}$ to denote $T_{next}$? This is because $T_{next}$ is used as a function before, and now it is used as an value...


- [ ] I think the following sentence:

```
it must be explicitly defined again, if a previously defined latexmath:[T_{next}] was not triggered at the current event instant.
```

is more correct as follows:

```
it must be explicitly defined again, *even* if a previously defined latexmath:[T_{next}] was not triggered at the current event instant.
```


- [ ] In the table cell with the following text

```
A vector of Boolean variables with latexmath:[r_{i} := z_{i} > 0] 
```

we should use a different Index for the scalar elements of vector $z$. For instance, instead of $z_{i}$ we should use $z_{j}$. Otherwise, the index gets confused with $t_i$.


- [ ] Put a link in the following sentence, as the remark is pretty far down.

```
[For more details, see "Remark 3" below.]
```


- [ ] Same thing for the following sentence, as it is not clear where "below" points to.

```
A vector of floating point continuous-time variables representing the event indicators utilized to define state events, see below.
```

**Comment by andreas-junghanns** [comment]
@clagms : I fixed what I could with PR #1110. I marked here what I think was either fixed with #1110, or elsewhere or is a remark not relevant (anymore).

What is left here, is beyond me and requires a PR that you make and someone with the proper knowledge approves of.

If you do not answer within 24h, I will merge PR 1110.

**Comment by chrbertsch** [comment]
Ticket-viewing-meeting

@clagms : I will go through this and see what is left to do. The goal is to close and create a smaller ticket with left-overs that can be dealt with more easily. @TorstenBlochwitz : then I can have a look at this.

**Comment by clagms** [comment]
I've planned to go over this next Saturday (10 October).

**Comment by TorstenBlochwitz** [comment]
@clagms: Andreas and I will meet next week for the next WriteFest. At our last meeting we started to restructure the state machine sections. At this meeting we plan to continue. One idea is to merge the state machine sections with the mathematical description for each state in order to avoid ambiguities and to have one place where everything is described for one mode.

It would be great if (if you really want to work at the weekend) you concentrate to fix minor and obvious things. It would be not so good to create a big pull request we have to merge before we start.

**Comment by clagms** [comment]
It's best we close this and do another review iteration later, trying to elicit new problems :)
