### ISSUE TITLE
Fix table combinations of variability/causality description

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-standard#958]
In (3) and (4) of the table, calculatedParameters are described.
There they are marked as "dependent" - nothing else in the entire text really refers to "dependent".

Should this attribute value not be called "calculated" instead of "dependent"?
Or is this a math-thing?

**Comment by clagms** [comment]
In the following, "dependent" refers to the dependencies kind of the parameter:
![image](https://user-images.githubusercontent.com/871103/80810710-b2edc800-8bc4-11ea-853a-123fa041a067.png)

I interpret the text "dependent parameter" as being a "calculated parameter with a dependency kind = dependent".
This interpretation does not make much sense, since it excludes calculated parameters with dependencykind="constant".

I guess the text might be wrong, and should refer to "calculatedParameter" (instead of "parameter").

**Comment by andreas-junghanns** [comment]
See #1009.

**Comment by andreas-junghanns** [comment]
This has been sufficiently explained.
