### ISSUE TITLE
XSD/doc disagreement with GraphicalRepresentation attributes

### ISSUE THREAD

**Issue by nickbattle** [modelica/fmi-standard#966]
Section 2.2.6.1 says that a TerminalsAndIcons GraphicalRepresentation has various attributes (x1, y1, etc). But in the fmiTerminalsAndIcons.xsd, these attributes are not present.

The 2.2.6.2.7 Terminals GraphicalRepresentation in fmiTerminal.xsd looks to be correct - ie. the attributes agree with the document and it has *no* sub-elements. These attributes appear to be the same as those missing from fmi3TerminalsAndIcons.xsd, unless the document is incorrect.

**Comment by pmai** [comment]
The only problem currently is that the brain-damaged tool that we are using to generate the diagrams puts both the top-level GraphicalRepresentation element (which has no attributes but sub-elements) and the non-top-level terminal GraphicalRepresentation element (which has attributes and no sub-elements) into the same picture (because it has no way of specifiying which element to use), see #940 for details.
