### ISSUE TITLE
intermediateStepFinished?

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#991]
If I understand correct if the callbacks return intermediateStepFinished == false it indicates that the internal solver step is just an attempted step but you want to update input to help it on for the next attempt. 

Lets say now that you have two FMU's A and B both with inputs and outputs connected to each other. These are both fairly complicated models so several returns of intermediateStepFinished == false can occur.

If now FMU A return intermediateStepFinished == True, and FMU B return intermediateStepFinished == False, is there some way to recalculate the step for FMU A with updated input? As long as FMU B has not finished one would expect that the intermediate output from that fmu will change, but it is no longer possible for FMU A to update its input accordingly. 

Have i understood the use case for intermediateInput with intermediateStepFinished == false correctly?

Do we need to fix this? I.e do we need the master to control when to finish these step calculation similar to event iteration.

**Comment by chrbertsch** [comment]
I agree with your understanding, but I think the master has all the information to decide what to do.

> If now FMU A return intermediateStepFinished == True, and FMU B return intermediateStepFinished == False, is there some way to recalculate the step for FMU A with updated input? 

One could use the means of rejecting and re-doing a timestep of FMU A with the help fmi3Get/SetState

**Comment by robbr48** [comment]
`intermediateStepFinished == false` is only intended to be used for variables with a communication delay, which must be greater than the internal solver step in the FMU. This will prevent the lockup situation you describe. The master can interpolate intermediate inputs for FMU A without depending on a recalculation in FMU B, since the time frame where the two FMUs are independent is always greater than the internal step. This requirement should be added to the specification. I can make a PR.

**Comment by klausschuch** [comment]
@KarlWernersson 
I think that we don't have to extend the specification.
If there are 2 FMUs (and for simplicity both dostep functions are called same communication steps size), the master has two options: (a) call both dostep functions sequentially or (b) call both dostep functions in parallel in two separate threads.

(a) If the master calls both sequentially, the master has gathered all information about one of the FMUs already before the dostep function of the other FMU gets called.
(b) If the master calls both in parallel, the master shouldn't exchange any information between the two FMUs before both dostep functions have ended anyway. (Unless the master wants to implements a complicated synching schema between FMUs within their dostep calls to avoid race conditions)

Hence, for intermediate update inputs, the master should use only information that is known before the dostep call of an FMU.
Such inputs could be: just time depending inputs defined by a user, inputs interpolated because the other FMU already calculated, (fancy) extrapolated inputs based on data collected up to the start of the dostep call, ...

@robbr48
I think your suggest PR is too restrictive and basically only considers transmission line elements.

**Comment by andreas-junghanns** [comment]
@KarlWernersson : Did today´s discussion help clarify this issue? Can we close?
